/* AppModule.c generated by valac 0.22.1, the Vala compiler
 * generated from AppModule.vala, do not modify */

/*
 * AppModule.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gmodule.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define QETESH_TYPE_APP_MODULE (qetesh_app_module_get_type ())
#define QETESH_APP_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_APP_MODULE, QeteshAppModule))
#define QETESH_APP_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_APP_MODULE, QeteshAppModuleClass))
#define QETESH_IS_APP_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_APP_MODULE))
#define QETESH_IS_APP_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_APP_MODULE))
#define QETESH_APP_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_APP_MODULE, QeteshAppModuleClass))

typedef struct _QeteshAppModule QeteshAppModule;
typedef struct _QeteshAppModuleClass QeteshAppModuleClass;
typedef struct _QeteshAppModulePrivate QeteshAppModulePrivate;

#define QETESH_TYPE_QWEB_APP (qetesh_qweb_app_get_type ())
#define QETESH_QWEB_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QWEB_APP, QeteshQWebApp))
#define QETESH_QWEB_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_QWEB_APP, QeteshQWebAppClass))
#define QETESH_IS_QWEB_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QWEB_APP))
#define QETESH_IS_QWEB_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_QWEB_APP))
#define QETESH_QWEB_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_QWEB_APP, QeteshQWebAppClass))

typedef struct _QeteshQWebApp QeteshQWebApp;
typedef struct _QeteshQWebAppClass QeteshQWebAppClass;

#define QETESH_TYPE_WEB_APP_CONTEXT (qetesh_web_app_context_get_type ())
#define QETESH_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext))
#define QETESH_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))
#define QETESH_IS_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_IS_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_WEB_APP_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))

typedef struct _QeteshWebAppContext QeteshWebAppContext;
typedef struct _QeteshWebAppContextClass QeteshWebAppContextClass;
#define _g_module_close0(var) ((var == NULL) ? NULL : (var = (g_module_close (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;

#define QETESH_TYPE_EVENT_MANAGER (qetesh_event_manager_get_type ())
#define QETESH_EVENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_EVENT_MANAGER, QeteshEventManager))
#define QETESH_EVENT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_EVENT_MANAGER, QeteshEventManagerClass))
#define QETESH_IS_EVENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_EVENT_MANAGER))
#define QETESH_IS_EVENT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_EVENT_MANAGER))
#define QETESH_EVENT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_EVENT_MANAGER, QeteshEventManagerClass))

typedef struct _QeteshEventManager QeteshEventManager;
typedef struct _QeteshEventManagerClass QeteshEventManagerClass;

#define QETESH_TYPE_HTTP_REQUEST (qetesh_http_request_get_type ())
#define QETESH_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequest))
#define QETESH_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequestClass))
#define QETESH_IS_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTTP_REQUEST))
#define QETESH_IS_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTTP_REQUEST))
#define QETESH_HTTP_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequestClass))

typedef struct _QeteshHTTPRequest QeteshHTTPRequest;
typedef struct _QeteshHTTPRequestClass QeteshHTTPRequestClass;

#define QETESH_TYPE_HTTP_RESPONSE (qetesh_http_response_get_type ())
#define QETESH_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse))
#define QETESH_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))
#define QETESH_IS_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_IS_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_HTTP_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))

typedef struct _QeteshHTTPResponse QeteshHTTPResponse;
typedef struct _QeteshHTTPResponseClass QeteshHTTPResponseClass;

#define QETESH_TYPE_JSON_RESPONSE (qetesh_json_response_get_type ())
#define QETESH_JSON_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponse))
#define QETESH_JSON_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponseClass))
#define QETESH_IS_JSON_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_JSON_RESPONSE))
#define QETESH_IS_JSON_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_JSON_RESPONSE))
#define QETESH_JSON_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponseClass))

typedef struct _QeteshJSONResponse QeteshJSONResponse;
typedef struct _QeteshJSONResponseClass QeteshJSONResponseClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())

#define QETESH_TYPE_QWEB_NODE (qetesh_qweb_node_get_type ())
#define QETESH_QWEB_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QWEB_NODE, QeteshQWebNode))
#define QETESH_QWEB_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_QWEB_NODE, QeteshQWebNodeClass))
#define QETESH_IS_QWEB_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QWEB_NODE))
#define QETESH_IS_QWEB_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_QWEB_NODE))
#define QETESH_QWEB_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_QWEB_NODE, QeteshQWebNodeClass))

typedef struct _QeteshQWebNode QeteshQWebNode;
typedef struct _QeteshQWebNodeClass QeteshQWebNodeClass;

#define QETESH_HTTP_REQUEST_TYPE_REQUEST_METHOD (qetesh_http_request_request_method_get_type ())

#define QETESH_TYPE_QPLUGIN (qetesh_qplugin_get_type ())
#define QETESH_QPLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QPLUGIN, QeteshQPlugin))
#define QETESH_IS_QPLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QPLUGIN))
#define QETESH_QPLUGIN_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), QETESH_TYPE_QPLUGIN, QeteshQPluginIface))

typedef struct _QeteshQPlugin QeteshQPlugin;
typedef struct _QeteshQPluginIface QeteshQPluginIface;

struct _QeteshAppModule {
	GObject parent_instance;
	QeteshAppModulePrivate * priv;
};

struct _QeteshAppModuleClass {
	GObjectClass parent_class;
};

struct _QeteshAppModulePrivate {
	GModule* module;
	gchar* _Nick;
	gchar* loaderName;
	gchar* path;
	QeteshQWebApp* _WebApp;
	QeteshWebAppContext* _Context;
};

typedef enum  {
	QETESH_ERRORS_QMODULE_ERROR_LOAD,
	QETESH_ERRORS_QMODULE_ERROR_CONFIG,
	QETESH_ERRORS_QMODULE_ERROR_STRUCTURE
} QeteshErrorsQModuleError;
#define QETESH_ERRORS_QMODULE_ERROR qetesh_errors_qmodule_error_quark ()
struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;

typedef enum  {
	QETESH_HTTP_REQUEST_REQUEST_METHOD_GET,
	QETESH_HTTP_REQUEST_REQUEST_METHOD_POST,
	QETESH_HTTP_REQUEST_REQUEST_METHOD_PUT,
	QETESH_HTTP_REQUEST_REQUEST_METHOD_HEAD,
	QETESH_HTTP_REQUEST_REQUEST_METHOD_INVALID
} QeteshHTTPRequestRequestMethod;

typedef GType (*QeteshAppModuleModInitFunc) (QeteshWebAppContext* ctx);
struct _QeteshQPluginIface {
	GTypeInterface parent_iface;
	QeteshQWebApp* (*GetModObject) (QeteshQPlugin* self, QeteshWebAppContext* ctx);
};


static gpointer qetesh_app_module_parent_class = NULL;

GType qetesh_app_module_get_type (void) G_GNUC_CONST;
GType qetesh_qweb_app_get_type (void) G_GNUC_CONST;
GType qetesh_web_app_context_get_type (void) G_GNUC_CONST;
#define QETESH_APP_MODULE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_APP_MODULE, QeteshAppModulePrivate))
enum  {
	QETESH_APP_MODULE_DUMMY_PROPERTY,
	QETESH_APP_MODULE_NICK,
	QETESH_APP_MODULE_WEB_APP,
	QETESH_APP_MODULE_CONTEXT
};
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
GQuark qetesh_errors_qmodule_error_quark (void);
QeteshAppModule* qetesh_app_module_new (const gchar* modPath, const gchar* nick, const gchar* loader, QeteshWebServerContext* sc, GError** error);
QeteshAppModule* qetesh_app_module_construct (GType object_type, const gchar* modPath, const gchar* nick, const gchar* loader, QeteshWebServerContext* sc, GError** error);
static void qetesh_app_module_set_Nick (QeteshAppModule* self, const gchar* value);
QeteshWebAppContext* qetesh_web_app_context_new (void);
QeteshWebAppContext* qetesh_web_app_context_construct (GType object_type);
static void qetesh_app_module_set_Context (QeteshAppModule* self, QeteshWebAppContext* value);
QeteshWebAppContext* qetesh_app_module_get_Context (QeteshAppModule* self);
void qetesh_web_app_context_set_Server (QeteshWebAppContext* self, QeteshWebServerContext* value);
QeteshEventManager* qetesh_event_manager_new (void);
QeteshEventManager* qetesh_event_manager_construct (GType object_type);
GType qetesh_event_manager_get_type (void) G_GNUC_CONST;
void qetesh_web_app_context_set_Events (QeteshWebAppContext* self, QeteshEventManager* value);
void qetesh_web_app_context_set_Mod (QeteshWebAppContext* self, QeteshAppModule* value);
QeteshQWebApp* qetesh_app_module_GetApp (QeteshAppModule* self, GError** error);
static void qetesh_app_module_set_WebApp (QeteshAppModule* self, QeteshQWebApp* value);
GType qetesh_http_request_get_type (void) G_GNUC_CONST;
void qetesh_app_module_Handle (QeteshAppModule* self, QeteshHTTPRequest* req);
GType qetesh_http_response_get_type (void) G_GNUC_CONST;
void qetesh_http_request_Route (QeteshHTTPRequest* self, QeteshWebAppContext* cxt, QeteshHTTPResponse* resp);
QeteshJSONResponse* qetesh_json_response_new (QeteshWebAppContext* ctx);
QeteshJSONResponse* qetesh_json_response_construct (GType object_type, QeteshWebAppContext* ctx);
GType qetesh_json_response_get_type (void) G_GNUC_CONST;
QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
GType qetesh_qweb_node_get_type (void) G_GNUC_CONST;
QeteshQWebApp* qetesh_app_module_get_WebApp (QeteshAppModule* self);
QeteshQWebNode* qetesh_qweb_app_GetNode (QeteshQWebApp* self, QeteshHTTPRequest* req);
const gchar* qetesh_qweb_node_get_Path (QeteshQWebNode* self);
GType qetesh_http_request_request_method_get_type (void) G_GNUC_CONST;
QeteshHTTPRequestRequestMethod qetesh_http_request_get_Method (QeteshHTTPRequest* self);
QeteshHTTPResponse* qetesh_http_request_get_HResponse (QeteshHTTPRequest* self);
GeeLinkedList* qetesh_http_response_get_Messages (QeteshHTTPResponse* self);
void qetesh_http_response_set_ResponseCode (QeteshHTTPResponse* self, gint value);
void qetesh_http_response_set_ResponseMessage (QeteshHTTPResponse* self, const gchar* value);
GType qetesh_qplugin_get_type (void) G_GNUC_CONST;
QeteshQWebApp* qetesh_qplugin_GetModObject (QeteshQPlugin* self, QeteshWebAppContext* ctx);
const gchar* qetesh_app_module_get_Nick (QeteshAppModule* self);
static void qetesh_app_module_finalize (GObject* obj);
static void _vala_qetesh_app_module_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_app_module_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
* Create a new AppModule and load the module
* 
* @param modPath Path to the module .so/.dll file
* @param module nickname, for identification
* @param loader name of the module loader class
**/
QeteshAppModule* qetesh_app_module_construct (GType object_type, const gchar* modPath, const gchar* nick, const gchar* loader, QeteshWebServerContext* sc, GError** error) {
	QeteshAppModule * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GModule* _tmp6_ = NULL;
	GModule* _tmp7_ = NULL;
	QeteshWebAppContext* _tmp9_ = NULL;
	QeteshWebAppContext* _tmp10_ = NULL;
	QeteshWebAppContext* _tmp11_ = NULL;
	QeteshWebServerContext* _tmp12_ = NULL;
	QeteshWebAppContext* _tmp13_ = NULL;
	QeteshEventManager* _tmp14_ = NULL;
	QeteshEventManager* _tmp15_ = NULL;
	QeteshWebAppContext* _tmp16_ = NULL;
	QeteshQWebApp* _tmp17_ = NULL;
	QeteshQWebApp* _tmp18_ = NULL;
	QeteshQWebApp* _tmp19_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (modPath != NULL, NULL);
	g_return_val_if_fail (nick != NULL, NULL);
	g_return_val_if_fail (loader != NULL, NULL);
	g_return_val_if_fail (sc != NULL, NULL);
	self = (QeteshAppModule*) g_object_new (object_type, NULL);
	_tmp0_ = nick;
	qetesh_app_module_set_Nick (self, _tmp0_);
	_tmp1_ = loader;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->loaderName);
	self->priv->loaderName = _tmp2_;
	_tmp3_ = modPath;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (self->priv->path);
	self->priv->path = _tmp4_;
	_tmp5_ = self->priv->path;
	_tmp6_ = g_module_open (_tmp5_, G_MODULE_BIND_LAZY);
	_g_module_close0 (self->priv->module);
	self->priv->module = _tmp6_;
	_tmp7_ = self->priv->module;
	if (_tmp7_ == NULL) {
		GError* _tmp8_ = NULL;
		_tmp8_ = g_error_new_literal (QETESH_ERRORS_QMODULE_ERROR, QETESH_ERRORS_QMODULE_ERROR_LOAD, "Unable to load module");
		_inner_error_ = _tmp8_;
		if (_inner_error_->domain == QETESH_ERRORS_QMODULE_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp9_ = qetesh_web_app_context_new ();
	_tmp10_ = _tmp9_;
	qetesh_app_module_set_Context (self, _tmp10_);
	_g_object_unref0 (_tmp10_);
	_tmp11_ = self->priv->_Context;
	_tmp12_ = sc;
	qetesh_web_app_context_set_Server (_tmp11_, _tmp12_);
	_tmp13_ = self->priv->_Context;
	_tmp14_ = qetesh_event_manager_new ();
	_tmp15_ = _tmp14_;
	qetesh_web_app_context_set_Events (_tmp13_, _tmp15_);
	_g_object_unref0 (_tmp15_);
	_tmp16_ = self->priv->_Context;
	qetesh_web_app_context_set_Mod (_tmp16_, self);
	_tmp18_ = qetesh_app_module_GetApp (self, &_inner_error_);
	_tmp17_ = _tmp18_;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == QETESH_ERRORS_QMODULE_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp19_ = _tmp17_;
	qetesh_app_module_set_WebApp (self, _tmp19_);
	_g_object_unref0 (_tmp19_);
	g_signal_emit_by_name (self, "application-start");
	return self;
}


QeteshAppModule* qetesh_app_module_new (const gchar* modPath, const gchar* nick, const gchar* loader, QeteshWebServerContext* sc, GError** error) {
	return qetesh_app_module_construct (QETESH_TYPE_APP_MODULE, modPath, nick, loader, sc, error);
}


/**
* Handle a request
**/
void qetesh_app_module_Handle (QeteshAppModule* self, QeteshHTTPRequest* req) {
	QeteshHTTPRequest* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	QeteshWebAppContext* _tmp2_ = NULL;
	QeteshJSONResponse* _tmp3_ = NULL;
	QeteshJSONResponse* _tmp4_ = NULL;
	QeteshWebAppContext* _tmp5_ = NULL;
	QeteshWebServerContext* _tmp6_ = NULL;
	QeteshWebServerContext* _tmp7_ = NULL;
	QeteshErrorManager* _tmp8_ = NULL;
	QeteshQWebNode* node = NULL;
	QeteshQWebApp* _tmp9_ = NULL;
	QeteshHTTPRequest* _tmp10_ = NULL;
	QeteshQWebNode* _tmp11_ = NULL;
	QeteshQWebNode* _tmp12_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (req != NULL);
	_tmp0_ = req;
	_tmp1_ = self->priv->_Context;
	_tmp2_ = self->priv->_Context;
	_tmp3_ = qetesh_json_response_new (_tmp2_);
	_tmp4_ = _tmp3_;
	qetesh_http_request_Route (_tmp0_, _tmp1_, (QeteshHTTPResponse*) _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = self->priv->_Context;
	_tmp6_ = qetesh_web_app_context_get_Server (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = _tmp7_->Err;
	qetesh_error_manager_WriteMessage (_tmp8_, "Finding node...", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_tmp9_ = self->priv->_WebApp;
	_tmp10_ = req;
	_tmp11_ = qetesh_qweb_app_GetNode (_tmp9_, _tmp10_);
	node = _tmp11_;
	_tmp12_ = node;
	if (_tmp12_ != NULL) {
		QeteshWebAppContext* _tmp13_ = NULL;
		QeteshWebServerContext* _tmp14_ = NULL;
		QeteshWebServerContext* _tmp15_ = NULL;
		QeteshErrorManager* _tmp16_ = NULL;
		QeteshQWebNode* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		QeteshHTTPRequest* _tmp22_ = NULL;
		QeteshHTTPRequestRequestMethod _tmp23_ = 0;
		QeteshHTTPRequestRequestMethod _tmp24_ = 0;
		_tmp13_ = self->priv->_Context;
		_tmp14_ = qetesh_web_app_context_get_Server (_tmp13_);
		_tmp15_ = _tmp14_;
		_tmp16_ = _tmp15_->Err;
		_tmp17_ = node;
		_tmp18_ = qetesh_qweb_node_get_Path (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = g_strdup_printf ("Found node: %s", _tmp19_);
		_tmp21_ = _tmp20_;
		qetesh_error_manager_WriteMessage (_tmp16_, _tmp21_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
		_g_free0 (_tmp21_);
		_tmp22_ = req;
		_tmp23_ = qetesh_http_request_get_Method (_tmp22_);
		_tmp24_ = _tmp23_;
		if (_tmp24_ == QETESH_HTTP_REQUEST_REQUEST_METHOD_GET) {
			QeteshQWebNode* _tmp25_ = NULL;
			QeteshHTTPRequest* _tmp26_ = NULL;
			_tmp25_ = node;
			_tmp26_ = req;
			g_signal_emit_by_name (_tmp25_, "get", _tmp26_);
		} else {
			QeteshHTTPRequest* _tmp27_ = NULL;
			QeteshHTTPRequestRequestMethod _tmp28_ = 0;
			QeteshHTTPRequestRequestMethod _tmp29_ = 0;
			_tmp27_ = req;
			_tmp28_ = qetesh_http_request_get_Method (_tmp27_);
			_tmp29_ = _tmp28_;
			if (_tmp29_ == QETESH_HTTP_REQUEST_REQUEST_METHOD_POST) {
				QeteshQWebNode* _tmp30_ = NULL;
				QeteshHTTPRequest* _tmp31_ = NULL;
				_tmp30_ = node;
				_tmp31_ = req;
				g_signal_emit_by_name (_tmp30_, "post", _tmp31_);
			}
		}
	} else {
		QeteshWebAppContext* _tmp32_ = NULL;
		QeteshWebServerContext* _tmp33_ = NULL;
		QeteshWebServerContext* _tmp34_ = NULL;
		QeteshErrorManager* _tmp35_ = NULL;
		QeteshHTTPRequest* _tmp36_ = NULL;
		QeteshHTTPResponse* _tmp37_ = NULL;
		QeteshHTTPResponse* _tmp38_ = NULL;
		GeeLinkedList* _tmp39_ = NULL;
		GeeLinkedList* _tmp40_ = NULL;
		QeteshHTTPRequest* _tmp41_ = NULL;
		QeteshHTTPResponse* _tmp42_ = NULL;
		QeteshHTTPResponse* _tmp43_ = NULL;
		QeteshHTTPRequest* _tmp44_ = NULL;
		QeteshHTTPResponse* _tmp45_ = NULL;
		QeteshHTTPResponse* _tmp46_ = NULL;
		_tmp32_ = self->priv->_Context;
		_tmp33_ = qetesh_web_app_context_get_Server (_tmp32_);
		_tmp34_ = _tmp33_;
		_tmp35_ = _tmp34_->Err;
		qetesh_error_manager_WriteMessage (_tmp35_, "Node not found (404)", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
		_tmp36_ = req;
		_tmp37_ = qetesh_http_request_get_HResponse (_tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = qetesh_http_response_get_Messages (_tmp38_);
		_tmp40_ = _tmp39_;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp40_, "Path not configured - 404");
		_tmp41_ = req;
		_tmp42_ = qetesh_http_request_get_HResponse (_tmp41_);
		_tmp43_ = _tmp42_;
		qetesh_http_response_set_ResponseCode (_tmp43_, 404);
		_tmp44_ = req;
		_tmp45_ = qetesh_http_request_get_HResponse (_tmp44_);
		_tmp46_ = _tmp45_;
		qetesh_http_response_set_ResponseMessage (_tmp46_, "Path not found");
	}
	_g_object_unref0 (node);
}


/**
* Activate the module's loader and main class entry point
* 
* @returns Web app object
**/
QeteshQWebApp* qetesh_app_module_GetApp (QeteshAppModule* self, GError** error) {
	QeteshQWebApp* result = NULL;
	QeteshWebAppContext* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	QeteshWebServerContext* _tmp2_ = NULL;
	QeteshErrorManager* _tmp3_ = NULL;
	void* initFunc = NULL;
	GModule* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	QeteshWebAppContext* _tmp8_ = NULL;
	QeteshWebServerContext* _tmp9_ = NULL;
	QeteshWebServerContext* _tmp10_ = NULL;
	QeteshErrorManager* _tmp11_ = NULL;
	GType t = 0UL;
	void* _tmp12_ = NULL;
	QeteshWebAppContext* _tmp13_ = NULL;
	GType _tmp14_ = 0UL;
	QeteshWebAppContext* _tmp15_ = NULL;
	QeteshWebServerContext* _tmp16_ = NULL;
	QeteshWebServerContext* _tmp17_ = NULL;
	QeteshErrorManager* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	QeteshQPlugin* p = NULL;
	const gchar* _tmp22_ = NULL;
	GType _tmp23_ = 0UL;
	GObject* _tmp24_ = NULL;
	GObject* _tmp25_ = NULL;
	QeteshWebAppContext* _tmp26_ = NULL;
	QeteshWebServerContext* _tmp27_ = NULL;
	QeteshWebServerContext* _tmp28_ = NULL;
	QeteshErrorManager* _tmp29_ = NULL;
	QeteshWebAppContext* _tmp30_ = NULL;
	QeteshQWebApp* _tmp31_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Context;
	_tmp1_ = qetesh_web_app_context_get_Server (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_->Err;
	qetesh_error_manager_WriteMessage (_tmp3_, "AppModule attempting to get app object", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	initFunc = NULL;
	_tmp4_ = self->priv->module;
	_tmp6_ = g_module_symbol (_tmp4_, "mod_init", &_tmp5_);
	initFunc = _tmp5_;
	if (!_tmp6_) {
		GError* _tmp7_ = NULL;
		_tmp7_ = g_error_new_literal (QETESH_ERRORS_QMODULE_ERROR, QETESH_ERRORS_QMODULE_ERROR_LOAD, "Unable to get init symbol from module");
		_inner_error_ = _tmp7_;
		if (_inner_error_->domain == QETESH_ERRORS_QMODULE_ERROR) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp8_ = self->priv->_Context;
	_tmp9_ = qetesh_web_app_context_get_Server (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = _tmp10_->Err;
	qetesh_error_manager_WriteMessage (_tmp11_, "Attempting to create type", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_tmp12_ = initFunc;
	_tmp13_ = self->priv->_Context;
	_tmp14_ = ((QeteshAppModuleModInitFunc) _tmp12_) (_tmp13_);
	t = _tmp14_;
	_tmp15_ = self->priv->_Context;
	_tmp16_ = qetesh_web_app_context_get_Server (_tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = _tmp17_->Err;
	_tmp19_ = g_type_name (t);
	_tmp20_ = g_strdup_printf ("Plugin type found: %s", _tmp19_);
	_tmp21_ = _tmp20_;
	qetesh_error_manager_WriteMessage (_tmp18_, _tmp21_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_g_free0 (_tmp21_);
	_tmp22_ = self->priv->loaderName;
	_tmp23_ = g_type_from_name (_tmp22_);
	_tmp24_ = g_object_new (_tmp23_, NULL);
	_tmp25_ = G_IS_INITIALLY_UNOWNED (_tmp24_) ? g_object_ref_sink (_tmp24_) : _tmp24_;
	p = G_TYPE_CHECK_INSTANCE_CAST (_tmp25_, QETESH_TYPE_QPLUGIN, QeteshQPlugin);
	_tmp26_ = self->priv->_Context;
	_tmp27_ = qetesh_web_app_context_get_Server (_tmp26_);
	_tmp28_ = _tmp27_;
	_tmp29_ = _tmp28_->Err;
	qetesh_error_manager_WriteMessage (_tmp29_, "Created loader object", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_tmp30_ = self->priv->_Context;
	_tmp31_ = qetesh_qplugin_GetModObject (p, _tmp30_);
	result = _tmp31_;
	_g_object_unref0 (p);
	return result;
}


const gchar* qetesh_app_module_get_Nick (QeteshAppModule* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Nick;
	result = _tmp0_;
	return result;
}


static void qetesh_app_module_set_Nick (QeteshAppModule* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_Nick);
	self->priv->_Nick = _tmp1_;
	g_object_notify ((GObject *) self, "Nick");
}


QeteshQWebApp* qetesh_app_module_get_WebApp (QeteshAppModule* self) {
	QeteshQWebApp* result;
	QeteshQWebApp* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_WebApp;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void qetesh_app_module_set_WebApp (QeteshAppModule* self, QeteshQWebApp* value) {
	QeteshQWebApp* _tmp0_ = NULL;
	QeteshQWebApp* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_WebApp);
	self->priv->_WebApp = _tmp1_;
	g_object_notify ((GObject *) self, "WebApp");
}


QeteshWebAppContext* qetesh_app_module_get_Context (QeteshAppModule* self) {
	QeteshWebAppContext* result;
	QeteshWebAppContext* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Context;
	result = _tmp0_;
	return result;
}


static void qetesh_app_module_set_Context (QeteshAppModule* self, QeteshWebAppContext* value) {
	QeteshWebAppContext* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Context);
	self->priv->_Context = _tmp1_;
	g_object_notify ((GObject *) self, "Context");
}


static void qetesh_app_module_class_init (QeteshAppModuleClass * klass) {
	qetesh_app_module_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshAppModulePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_app_module_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_app_module_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_app_module_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_APP_MODULE_NICK, g_param_spec_string ("Nick", "Nick", "Nick", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_APP_MODULE_WEB_APP, g_param_spec_object ("WebApp", "WebApp", "WebApp", QETESH_TYPE_QWEB_APP, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_APP_MODULE_CONTEXT, g_param_spec_object ("Context", "Context", "Context", QETESH_TYPE_WEB_APP_CONTEXT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("application_start", QETESH_TYPE_APP_MODULE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void qetesh_app_module_instance_init (QeteshAppModule * self) {
	self->priv = QETESH_APP_MODULE_GET_PRIVATE (self);
}


static void qetesh_app_module_finalize (GObject* obj) {
	QeteshAppModule * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_APP_MODULE, QeteshAppModule);
	_g_module_close0 (self->priv->module);
	self->priv->module = NULL;
	_g_module_close0 (self->priv->module);
	_g_free0 (self->priv->_Nick);
	_g_free0 (self->priv->loaderName);
	_g_free0 (self->priv->path);
	_g_object_unref0 (self->priv->_WebApp);
	_g_object_unref0 (self->priv->_Context);
	G_OBJECT_CLASS (qetesh_app_module_parent_class)->finalize (obj);
}


/**
* A single module that has been, or is to be, loaded
**/
GType qetesh_app_module_get_type (void) {
	static volatile gsize qetesh_app_module_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_app_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshAppModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_app_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshAppModule), 0, (GInstanceInitFunc) qetesh_app_module_instance_init, NULL };
		GType qetesh_app_module_type_id;
		qetesh_app_module_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshAppModule", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_app_module_type_id__volatile, qetesh_app_module_type_id);
	}
	return qetesh_app_module_type_id__volatile;
}


static void _vala_qetesh_app_module_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshAppModule * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_APP_MODULE, QeteshAppModule);
	switch (property_id) {
		case QETESH_APP_MODULE_NICK:
		g_value_set_string (value, qetesh_app_module_get_Nick (self));
		break;
		case QETESH_APP_MODULE_WEB_APP:
		g_value_set_object (value, qetesh_app_module_get_WebApp (self));
		break;
		case QETESH_APP_MODULE_CONTEXT:
		g_value_set_object (value, qetesh_app_module_get_Context (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_app_module_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshAppModule * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_APP_MODULE, QeteshAppModule);
	switch (property_id) {
		case QETESH_APP_MODULE_NICK:
		qetesh_app_module_set_Nick (self, g_value_get_string (value));
		break;
		case QETESH_APP_MODULE_WEB_APP:
		qetesh_app_module_set_WebApp (self, g_value_get_object (value));
		break;
		case QETESH_APP_MODULE_CONTEXT:
		qetesh_app_module_set_Context (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


QeteshQWebApp* qetesh_qplugin_GetModObject (QeteshQPlugin* self, QeteshWebAppContext* ctx) {
	g_return_val_if_fail (self != NULL, NULL);
	return QETESH_QPLUGIN_GET_INTERFACE (self)->GetModObject (self, ctx);
}


static void qetesh_qplugin_base_init (QeteshQPluginIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


/**
* Interface that module loader classes must meet
**/
GType qetesh_qplugin_get_type (void) {
	static volatile gsize qetesh_qplugin_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_qplugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshQPluginIface), (GBaseInitFunc) qetesh_qplugin_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType qetesh_qplugin_type_id;
		qetesh_qplugin_type_id = g_type_register_static (G_TYPE_INTERFACE, "QeteshQPlugin", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (qetesh_qplugin_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&qetesh_qplugin_type_id__volatile, qetesh_qplugin_type_id);
	}
	return qetesh_qplugin_type_id__volatile;
}



