/* ConfigFile.c generated by valac 0.22.1, the Vala compiler
 * generated from ConfigFile.vala, do not modify */

/*
 * ConfigFile.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <gobject/gvaluecollector.h>


#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;
typedef struct _QeteshConfigFilePrivate QeteshConfigFilePrivate;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;

#define QETESH_CONFIG_FILE_TYPE_MOD_CONFIG (qetesh_config_file_mod_config_get_type ())
#define QETESH_CONFIG_FILE_MOD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfig))
#define QETESH_CONFIG_FILE_MOD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfigClass))
#define QETESH_CONFIG_FILE_IS_MOD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG))
#define QETESH_CONFIG_FILE_IS_MOD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG))
#define QETESH_CONFIG_FILE_MOD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfigClass))

typedef struct _QeteshConfigFileModConfig QeteshConfigFileModConfig;
typedef struct _QeteshConfigFileModConfigClass QeteshConfigFileModConfigClass;

#define QETESH_CONFIG_FILE_TYPE_DB_CONFIG (qetesh_config_file_db_config_get_type ())
#define QETESH_CONFIG_FILE_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfig))
#define QETESH_CONFIG_FILE_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_DB_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))

typedef struct _QeteshConfigFileDBConfig QeteshConfigFileDBConfig;
typedef struct _QeteshConfigFileDBConfigClass QeteshConfigFileDBConfigClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define QETESH_TYPE_CONFIG_FILE_PARSER (qetesh_config_file_parser_get_type ())
#define QETESH_CONFIG_FILE_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParser))
#define QETESH_CONFIG_FILE_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParserClass))
#define QETESH_IS_CONFIG_FILE_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE_PARSER))
#define QETESH_IS_CONFIG_FILE_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE_PARSER))
#define QETESH_CONFIG_FILE_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParserClass))

typedef struct _QeteshConfigFileParser QeteshConfigFileParser;
typedef struct _QeteshConfigFileParserClass QeteshConfigFileParserClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _QeteshConfigFileModConfigPrivate QeteshConfigFileModConfigPrivate;
typedef struct _QeteshConfigFileParamSpecModConfig QeteshConfigFileParamSpecModConfig;
typedef struct _QeteshConfigFileDBConfigPrivate QeteshConfigFileDBConfigPrivate;
typedef struct _QeteshConfigFileParamSpecDBConfig QeteshConfigFileParamSpecDBConfig;

struct _QeteshConfigFile {
	GObject parent_instance;
	QeteshConfigFilePrivate * priv;
};

struct _QeteshConfigFileClass {
	GObjectClass parent_class;
};

struct _QeteshConfigFilePrivate {
	QeteshWebServerContext* context;
	gchar* filePath;
	guint16 _ListenPort;
	gint _MaxThreads;
	gchar* _ListenAddr;
	gchar* _LogFile;
	gint _LogLevel;
	GeeLinkedList* _Modules;
	GeeLinkedList* _Databases;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;

struct _QeteshConfigFileModConfig {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshConfigFileModConfigPrivate * priv;
	gchar* LibPath;
	gchar* LoaderName;
	gchar* Nick;
	GeeLinkedList* Hosts;
};

struct _QeteshConfigFileModConfigClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshConfigFileModConfig *self);
};

struct _QeteshConfigFileParamSpecModConfig {
	GParamSpec parent_instance;
};

struct _QeteshConfigFileDBConfig {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshConfigFileDBConfigPrivate * priv;
	GeeLinkedList* AllowedTypes;
	gchar* Connector;
	gchar* Host;
	guint16 Port;
	gchar* Username;
	gchar* Password;
	gchar* DBName;
	gchar* Nick;
};

struct _QeteshConfigFileDBConfigClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshConfigFileDBConfig *self);
};

struct _QeteshConfigFileParamSpecDBConfig {
	GParamSpec parent_instance;
};


static gpointer qetesh_config_file_parent_class = NULL;
static gpointer qetesh_config_file_mod_config_parent_class = NULL;
static gpointer qetesh_config_file_db_config_parent_class = NULL;

GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
gpointer qetesh_config_file_mod_config_ref (gpointer instance);
void qetesh_config_file_mod_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_mod_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_mod_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_mod_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_mod_config (const GValue* value);
GType qetesh_config_file_mod_config_get_type (void) G_GNUC_CONST;
gpointer qetesh_config_file_db_config_ref (gpointer instance);
void qetesh_config_file_db_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_db_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_db_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_db_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_db_config (const GValue* value);
GType qetesh_config_file_db_config_get_type (void) G_GNUC_CONST;
#define QETESH_CONFIG_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_CONFIG_FILE, QeteshConfigFilePrivate))
enum  {
	QETESH_CONFIG_FILE_DUMMY_PROPERTY,
	QETESH_CONFIG_FILE_MAX_THREADS,
	QETESH_CONFIG_FILE_LISTEN_ADDR,
	QETESH_CONFIG_FILE_LOG_FILE,
	QETESH_CONFIG_FILE_LOG_LEVEL,
	QETESH_CONFIG_FILE_MODULES,
	QETESH_CONFIG_FILE_DATABASES
};
#define QETESH_CONFIG_FILE_DLISTEN_PORT ((guint16) 8041)
#define QETESH_CONFIG_FILE_DMAX_THREADS 1000
#define QETESH_CONFIG_FILE_DLISTEN_ADDR "0.0.0.0"
#define QETESH_CONFIG_FILE_DCACHE_DIR "/tmp/qetesh"
#define QETESH_CONFIG_FILE_DCONFIG_FILE "/usr/local/etc/qetesh.conf"
#define QETESH_CONFIG_FILE_DLOG_FILE "/var/log/qetesh.log"
QeteshConfigFile* qetesh_config_file_new (QeteshWebServerContext* sc, const gchar* path);
QeteshConfigFile* qetesh_config_file_construct (GType object_type, QeteshWebServerContext* sc, const gchar* path);
void qetesh_config_file_set_ListenPort (QeteshConfigFile* self, guint16 value);
void qetesh_config_file_set_ListenAddr (QeteshConfigFile* self, const gchar* value);
void qetesh_config_file_set_MaxThreads (QeteshConfigFile* self, gint value);
void qetesh_config_file_set_LogFile (QeteshConfigFile* self, const gchar* value);
static void qetesh_config_file_set_Modules (QeteshConfigFile* self, GeeLinkedList* value);
static void qetesh_config_file_set_Databases (QeteshConfigFile* self, GeeLinkedList* value);
void qetesh_config_file_ReParse (QeteshConfigFile* self);
GType qetesh_config_file_parser_get_type (void) G_GNUC_CONST;
QeteshConfigFileParser* qetesh_config_file_parser_new (GDataInputStream* confFile, QeteshWebServerContext* sc);
QeteshConfigFileParser* qetesh_config_file_parser_construct (GType object_type, GDataInputStream* confFile, QeteshWebServerContext* sc);
void qetesh_config_file_parser_ReadInto (QeteshConfigFileParser* self, QeteshConfigFile* cfg);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
guint16 qetesh_config_file_get_ListenPort (QeteshConfigFile* self);
gint qetesh_config_file_get_MaxThreads (QeteshConfigFile* self);
const gchar* qetesh_config_file_get_ListenAddr (QeteshConfigFile* self);
const gchar* qetesh_config_file_get_LogFile (QeteshConfigFile* self);
gint qetesh_config_file_get_LogLevel (QeteshConfigFile* self);
void qetesh_config_file_set_LogLevel (QeteshConfigFile* self, gint value);
GeeLinkedList* qetesh_config_file_get_Modules (QeteshConfigFile* self);
GeeLinkedList* qetesh_config_file_get_Databases (QeteshConfigFile* self);
enum  {
	QETESH_CONFIG_FILE_MOD_CONFIG_DUMMY_PROPERTY
};
QeteshConfigFileModConfig* qetesh_config_file_mod_config_new (void);
QeteshConfigFileModConfig* qetesh_config_file_mod_config_construct (GType object_type);
static void qetesh_config_file_mod_config_finalize (QeteshConfigFileModConfig* obj);
enum  {
	QETESH_CONFIG_FILE_DB_CONFIG_DUMMY_PROPERTY
};
QeteshConfigFileDBConfig* qetesh_config_file_db_config_new (void);
QeteshConfigFileDBConfig* qetesh_config_file_db_config_construct (GType object_type);
static void qetesh_config_file_db_config_finalize (QeteshConfigFileDBConfig* obj);
static void qetesh_config_file_finalize (GObject* obj);
static void _vala_qetesh_config_file_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_config_file_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Load and parse a new config file
 * 
 * @param path Full file path to config file
**/
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


QeteshConfigFile* qetesh_config_file_construct (GType object_type, QeteshWebServerContext* sc, const gchar* path) {
	QeteshConfigFile * self = NULL;
	QeteshWebServerContext* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	GeeLinkedList* _tmp2_ = NULL;
	GeeLinkedList* _tmp3_ = NULL;
	GeeLinkedList* _tmp4_ = NULL;
	GeeLinkedList* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	g_return_val_if_fail (sc != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	self = (QeteshConfigFile*) g_object_new (object_type, NULL);
	_tmp0_ = sc;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->context);
	self->priv->context = _tmp1_;
	qetesh_config_file_set_ListenPort (self, QETESH_CONFIG_FILE_DLISTEN_PORT);
	qetesh_config_file_set_ListenAddr (self, QETESH_CONFIG_FILE_DLISTEN_ADDR);
	qetesh_config_file_set_MaxThreads (self, QETESH_CONFIG_FILE_DMAX_THREADS);
	qetesh_config_file_set_LogFile (self, QETESH_CONFIG_FILE_DLOG_FILE);
	_tmp2_ = gee_linked_list_new (QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, (GBoxedCopyFunc) qetesh_config_file_mod_config_ref, qetesh_config_file_mod_config_unref, NULL, NULL, NULL);
	_tmp3_ = _tmp2_;
	qetesh_config_file_set_Modules (self, _tmp3_);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = gee_linked_list_new (QETESH_CONFIG_FILE_TYPE_DB_CONFIG, (GBoxedCopyFunc) qetesh_config_file_db_config_ref, qetesh_config_file_db_config_unref, NULL, NULL, NULL);
	_tmp5_ = _tmp4_;
	qetesh_config_file_set_Databases (self, _tmp5_);
	_g_object_unref0 (_tmp5_);
	_tmp6_ = path;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->priv->filePath);
	self->priv->filePath = _tmp7_;
	qetesh_config_file_ReParse (self);
	return self;
}


QeteshConfigFile* qetesh_config_file_new (QeteshWebServerContext* sc, const gchar* path) {
	return qetesh_config_file_construct (QETESH_TYPE_CONFIG_FILE, sc, path);
}


/**
 * Parse the current config file again to check for changes
 * TODO: implement reload function for server
**/
void qetesh_config_file_ReParse (QeteshConfigFile* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GFile* confFile = NULL;
		const gchar* _tmp0_ = NULL;
		GFile* _tmp1_ = NULL;
		GFileInputStream* _tmp2_ = NULL;
		GFileInputStream* _tmp3_ = NULL;
		QeteshConfigFileParser* parser = NULL;
		GFileInputStream* _tmp4_ = NULL;
		GDataInputStream* _tmp5_ = NULL;
		GDataInputStream* _tmp6_ = NULL;
		QeteshWebServerContext* _tmp7_ = NULL;
		QeteshConfigFileParser* _tmp8_ = NULL;
		QeteshConfigFileParser* _tmp9_ = NULL;
		QeteshConfigFileParser* _tmp10_ = NULL;
		_tmp0_ = self->priv->filePath;
		_tmp1_ = g_file_new_for_path (_tmp0_);
		confFile = _tmp1_;
		_tmp3_ = g_file_read (confFile, NULL, &_inner_error_);
		_tmp2_ = _tmp3_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (confFile);
			goto __catch4_g_error;
		}
		_tmp4_ = _tmp2_;
		_tmp5_ = g_data_input_stream_new ((GInputStream*) _tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = self->priv->context;
		_tmp8_ = qetesh_config_file_parser_new (_tmp6_, _tmp7_);
		_tmp9_ = _tmp8_;
		_g_object_unref0 (_tmp6_);
		_g_object_unref0 (_tmp4_);
		parser = _tmp9_;
		_tmp10_ = parser;
		qetesh_config_file_parser_ReadInto (_tmp10_, self);
		_g_object_unref0 (parser);
		_g_object_unref0 (confFile);
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		QeteshWebServerContext* _tmp11_ = NULL;
		QeteshErrorManager* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp11_ = self->priv->context;
		_tmp12_ = _tmp11_->Err;
		_tmp13_ = self->priv->filePath;
		_tmp14_ = g_strdup_printf ("Unable to open config file: %s", _tmp13_);
		_tmp15_ = _tmp14_;
		qetesh_error_manager_WriteMessage (_tmp12_, _tmp15_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING, NULL);
		_g_free0 (_tmp15_);
		_g_error_free0 (e);
	}
	__finally4:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


guint16 qetesh_config_file_get_ListenPort (QeteshConfigFile* self) {
	guint16 result;
	guint16 _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_ListenPort;
	result = _tmp0_;
	return result;
}


void qetesh_config_file_set_ListenPort (QeteshConfigFile* self, guint16 value) {
	guint16 _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ListenPort = _tmp0_;
}


gint qetesh_config_file_get_MaxThreads (QeteshConfigFile* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_MaxThreads;
	result = _tmp0_;
	return result;
}


void qetesh_config_file_set_MaxThreads (QeteshConfigFile* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_MaxThreads = _tmp0_;
	g_object_notify ((GObject *) self, "MaxThreads");
}


const gchar* qetesh_config_file_get_ListenAddr (QeteshConfigFile* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ListenAddr;
	result = _tmp0_;
	return result;
}


void qetesh_config_file_set_ListenAddr (QeteshConfigFile* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ListenAddr);
	self->priv->_ListenAddr = _tmp1_;
	g_object_notify ((GObject *) self, "ListenAddr");
}


const gchar* qetesh_config_file_get_LogFile (QeteshConfigFile* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_LogFile;
	result = _tmp0_;
	return result;
}


void qetesh_config_file_set_LogFile (QeteshConfigFile* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_LogFile);
	self->priv->_LogFile = _tmp1_;
	g_object_notify ((GObject *) self, "LogFile");
}


gint qetesh_config_file_get_LogLevel (QeteshConfigFile* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_LogLevel;
	result = _tmp0_;
	return result;
}


void qetesh_config_file_set_LogLevel (QeteshConfigFile* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_LogLevel = _tmp0_;
	g_object_notify ((GObject *) self, "LogLevel");
}


GeeLinkedList* qetesh_config_file_get_Modules (QeteshConfigFile* self) {
	GeeLinkedList* result;
	GeeLinkedList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Modules;
	result = _tmp0_;
	return result;
}


static void qetesh_config_file_set_Modules (QeteshConfigFile* self, GeeLinkedList* value) {
	GeeLinkedList* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Modules);
	self->priv->_Modules = _tmp1_;
	g_object_notify ((GObject *) self, "Modules");
}


GeeLinkedList* qetesh_config_file_get_Databases (QeteshConfigFile* self) {
	GeeLinkedList* result;
	GeeLinkedList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Databases;
	result = _tmp0_;
	return result;
}


static void qetesh_config_file_set_Databases (QeteshConfigFile* self, GeeLinkedList* value) {
	GeeLinkedList* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Databases);
	self->priv->_Databases = _tmp1_;
	g_object_notify ((GObject *) self, "Databases");
}


/**
 * Create a new, blank module config
**/
QeteshConfigFileModConfig* qetesh_config_file_mod_config_construct (GType object_type) {
	QeteshConfigFileModConfig* self = NULL;
	GeeLinkedList* _tmp0_ = NULL;
	self = (QeteshConfigFileModConfig*) g_type_create_instance (object_type);
	_tmp0_ = gee_linked_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_g_object_unref0 (self->Hosts);
	self->Hosts = _tmp0_;
	return self;
}


QeteshConfigFileModConfig* qetesh_config_file_mod_config_new (void) {
	return qetesh_config_file_mod_config_construct (QETESH_CONFIG_FILE_TYPE_MOD_CONFIG);
}


static void qetesh_config_file_value_mod_config_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void qetesh_config_file_value_mod_config_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		qetesh_config_file_mod_config_unref (value->data[0].v_pointer);
	}
}


static void qetesh_config_file_value_mod_config_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = qetesh_config_file_mod_config_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer qetesh_config_file_value_mod_config_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* qetesh_config_file_value_mod_config_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		QeteshConfigFileModConfig* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = qetesh_config_file_mod_config_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* qetesh_config_file_value_mod_config_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	QeteshConfigFileModConfig** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = qetesh_config_file_mod_config_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* qetesh_config_file_param_spec_mod_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	QeteshConfigFileParamSpecModConfig* spec;
	g_return_val_if_fail (g_type_is_a (object_type, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer qetesh_config_file_value_get_mod_config (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG), NULL);
	return value->data[0].v_pointer;
}


void qetesh_config_file_value_set_mod_config (GValue* value, gpointer v_object) {
	QeteshConfigFileModConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		qetesh_config_file_mod_config_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_config_file_mod_config_unref (old);
	}
}


void qetesh_config_file_value_take_mod_config (GValue* value, gpointer v_object) {
	QeteshConfigFileModConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_config_file_mod_config_unref (old);
	}
}


static void qetesh_config_file_mod_config_class_init (QeteshConfigFileModConfigClass * klass) {
	qetesh_config_file_mod_config_parent_class = g_type_class_peek_parent (klass);
	QETESH_CONFIG_FILE_MOD_CONFIG_CLASS (klass)->finalize = qetesh_config_file_mod_config_finalize;
}


static void qetesh_config_file_mod_config_instance_init (QeteshConfigFileModConfig * self) {
	self->ref_count = 1;
}


static void qetesh_config_file_mod_config_finalize (QeteshConfigFileModConfig* obj) {
	QeteshConfigFileModConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfig);
	_g_free0 (self->LibPath);
	_g_free0 (self->LoaderName);
	_g_free0 (self->Nick);
	_g_object_unref0 (self->Hosts);
}


/**
 * Module configuration
**/
GType qetesh_config_file_mod_config_get_type (void) {
	static volatile gsize qetesh_config_file_mod_config_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_config_file_mod_config_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { qetesh_config_file_value_mod_config_init, qetesh_config_file_value_mod_config_free_value, qetesh_config_file_value_mod_config_copy_value, qetesh_config_file_value_mod_config_peek_pointer, "p", qetesh_config_file_value_mod_config_collect_value, "p", qetesh_config_file_value_mod_config_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (QeteshConfigFileModConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_config_file_mod_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshConfigFileModConfig), 0, (GInstanceInitFunc) qetesh_config_file_mod_config_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType qetesh_config_file_mod_config_type_id;
		qetesh_config_file_mod_config_type_id = g_type_register_fundamental (g_type_fundamental_next (), "QeteshConfigFileModConfig", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&qetesh_config_file_mod_config_type_id__volatile, qetesh_config_file_mod_config_type_id);
	}
	return qetesh_config_file_mod_config_type_id__volatile;
}


gpointer qetesh_config_file_mod_config_ref (gpointer instance) {
	QeteshConfigFileModConfig* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void qetesh_config_file_mod_config_unref (gpointer instance) {
	QeteshConfigFileModConfig* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		QETESH_CONFIG_FILE_MOD_CONFIG_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


/**
 * Create a new, blank database config
**/
QeteshConfigFileDBConfig* qetesh_config_file_db_config_construct (GType object_type) {
	QeteshConfigFileDBConfig* self = NULL;
	GeeLinkedList* _tmp0_ = NULL;
	self = (QeteshConfigFileDBConfig*) g_type_create_instance (object_type);
	_tmp0_ = gee_linked_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_g_object_unref0 (self->AllowedTypes);
	self->AllowedTypes = _tmp0_;
	return self;
}


QeteshConfigFileDBConfig* qetesh_config_file_db_config_new (void) {
	return qetesh_config_file_db_config_construct (QETESH_CONFIG_FILE_TYPE_DB_CONFIG);
}


static void qetesh_config_file_value_db_config_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void qetesh_config_file_value_db_config_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		qetesh_config_file_db_config_unref (value->data[0].v_pointer);
	}
}


static void qetesh_config_file_value_db_config_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = qetesh_config_file_db_config_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer qetesh_config_file_value_db_config_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* qetesh_config_file_value_db_config_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		QeteshConfigFileDBConfig* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = qetesh_config_file_db_config_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* qetesh_config_file_value_db_config_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	QeteshConfigFileDBConfig** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = qetesh_config_file_db_config_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* qetesh_config_file_param_spec_db_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	QeteshConfigFileParamSpecDBConfig* spec;
	g_return_val_if_fail (g_type_is_a (object_type, QETESH_CONFIG_FILE_TYPE_DB_CONFIG), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer qetesh_config_file_value_get_db_config (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_DB_CONFIG), NULL);
	return value->data[0].v_pointer;
}


void qetesh_config_file_value_set_db_config (GValue* value, gpointer v_object) {
	QeteshConfigFileDBConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_DB_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_CONFIG_FILE_TYPE_DB_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		qetesh_config_file_db_config_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_config_file_db_config_unref (old);
	}
}


void qetesh_config_file_value_take_db_config (GValue* value, gpointer v_object) {
	QeteshConfigFileDBConfig* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_CONFIG_FILE_TYPE_DB_CONFIG));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_CONFIG_FILE_TYPE_DB_CONFIG));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_config_file_db_config_unref (old);
	}
}


static void qetesh_config_file_db_config_class_init (QeteshConfigFileDBConfigClass * klass) {
	qetesh_config_file_db_config_parent_class = g_type_class_peek_parent (klass);
	QETESH_CONFIG_FILE_DB_CONFIG_CLASS (klass)->finalize = qetesh_config_file_db_config_finalize;
}


static void qetesh_config_file_db_config_instance_init (QeteshConfigFileDBConfig * self) {
	self->ref_count = 1;
}


static void qetesh_config_file_db_config_finalize (QeteshConfigFileDBConfig* obj) {
	QeteshConfigFileDBConfig * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfig);
	_g_object_unref0 (self->AllowedTypes);
	_g_free0 (self->Connector);
	_g_free0 (self->Host);
	_g_free0 (self->Username);
	_g_free0 (self->Password);
	_g_free0 (self->DBName);
	_g_free0 (self->Nick);
}


/**
 * Database configuration
**/
GType qetesh_config_file_db_config_get_type (void) {
	static volatile gsize qetesh_config_file_db_config_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_config_file_db_config_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { qetesh_config_file_value_db_config_init, qetesh_config_file_value_db_config_free_value, qetesh_config_file_value_db_config_copy_value, qetesh_config_file_value_db_config_peek_pointer, "p", qetesh_config_file_value_db_config_collect_value, "p", qetesh_config_file_value_db_config_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (QeteshConfigFileDBConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_config_file_db_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshConfigFileDBConfig), 0, (GInstanceInitFunc) qetesh_config_file_db_config_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType qetesh_config_file_db_config_type_id;
		qetesh_config_file_db_config_type_id = g_type_register_fundamental (g_type_fundamental_next (), "QeteshConfigFileDBConfig", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&qetesh_config_file_db_config_type_id__volatile, qetesh_config_file_db_config_type_id);
	}
	return qetesh_config_file_db_config_type_id__volatile;
}


gpointer qetesh_config_file_db_config_ref (gpointer instance) {
	QeteshConfigFileDBConfig* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void qetesh_config_file_db_config_unref (gpointer instance) {
	QeteshConfigFileDBConfig* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		QETESH_CONFIG_FILE_DB_CONFIG_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void qetesh_config_file_class_init (QeteshConfigFileClass * klass) {
	qetesh_config_file_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshConfigFilePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_config_file_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_config_file_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_config_file_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_MAX_THREADS, g_param_spec_int ("MaxThreads", "MaxThreads", "MaxThreads", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_LISTEN_ADDR, g_param_spec_string ("ListenAddr", "ListenAddr", "ListenAddr", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_LOG_FILE, g_param_spec_string ("LogFile", "LogFile", "LogFile", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_LOG_LEVEL, g_param_spec_int ("LogLevel", "LogLevel", "LogLevel", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_MODULES, g_param_spec_object ("Modules", "Modules", "Modules", GEE_TYPE_LINKED_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_CONFIG_FILE_DATABASES, g_param_spec_object ("Databases", "Databases", "Databases", GEE_TYPE_LINKED_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void qetesh_config_file_instance_init (QeteshConfigFile * self) {
	self->priv = QETESH_CONFIG_FILE_GET_PRIVATE (self);
}


static void qetesh_config_file_finalize (GObject* obj) {
	QeteshConfigFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_CONFIG_FILE, QeteshConfigFile);
	_g_object_unref0 (self->priv->context);
	_g_free0 (self->priv->filePath);
	_g_free0 (self->priv->_ListenAddr);
	_g_free0 (self->priv->_LogFile);
	_g_object_unref0 (self->priv->_Modules);
	_g_object_unref0 (self->priv->_Databases);
	G_OBJECT_CLASS (qetesh_config_file_parent_class)->finalize (obj);
}


/**
 * Configuration file interface
 * 
 * Provides simple access to a Qetesh configuration file.
 * Can be used by modules for their own config file in the same
 * format if desired.
 *
**/
GType qetesh_config_file_get_type (void) {
	static volatile gsize qetesh_config_file_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_config_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshConfigFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_config_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshConfigFile), 0, (GInstanceInitFunc) qetesh_config_file_instance_init, NULL };
		GType qetesh_config_file_type_id;
		qetesh_config_file_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshConfigFile", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_config_file_type_id__volatile, qetesh_config_file_type_id);
	}
	return qetesh_config_file_type_id__volatile;
}


static void _vala_qetesh_config_file_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshConfigFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_CONFIG_FILE, QeteshConfigFile);
	switch (property_id) {
		case QETESH_CONFIG_FILE_MAX_THREADS:
		g_value_set_int (value, qetesh_config_file_get_MaxThreads (self));
		break;
		case QETESH_CONFIG_FILE_LISTEN_ADDR:
		g_value_set_string (value, qetesh_config_file_get_ListenAddr (self));
		break;
		case QETESH_CONFIG_FILE_LOG_FILE:
		g_value_set_string (value, qetesh_config_file_get_LogFile (self));
		break;
		case QETESH_CONFIG_FILE_LOG_LEVEL:
		g_value_set_int (value, qetesh_config_file_get_LogLevel (self));
		break;
		case QETESH_CONFIG_FILE_MODULES:
		g_value_set_object (value, qetesh_config_file_get_Modules (self));
		break;
		case QETESH_CONFIG_FILE_DATABASES:
		g_value_set_object (value, qetesh_config_file_get_Databases (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_config_file_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshConfigFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_CONFIG_FILE, QeteshConfigFile);
	switch (property_id) {
		case QETESH_CONFIG_FILE_MAX_THREADS:
		qetesh_config_file_set_MaxThreads (self, g_value_get_int (value));
		break;
		case QETESH_CONFIG_FILE_LISTEN_ADDR:
		qetesh_config_file_set_ListenAddr (self, g_value_get_string (value));
		break;
		case QETESH_CONFIG_FILE_LOG_FILE:
		qetesh_config_file_set_LogFile (self, g_value_get_string (value));
		break;
		case QETESH_CONFIG_FILE_LOG_LEVEL:
		qetesh_config_file_set_LogLevel (self, g_value_get_int (value));
		break;
		case QETESH_CONFIG_FILE_MODULES:
		qetesh_config_file_set_Modules (self, g_value_get_object (value));
		break;
		case QETESH_CONFIG_FILE_DATABASES:
		qetesh_config_file_set_Databases (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



