/* ConfigFileParser.c generated by valac 0.22.1, the Vala compiler
 * generated from ConfigFileParser.vala, do not modify */

/*
 * ConfigFileParser.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define QETESH_TYPE_CONFIG_FILE_PARSER (qetesh_config_file_parser_get_type ())
#define QETESH_CONFIG_FILE_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParser))
#define QETESH_CONFIG_FILE_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParserClass))
#define QETESH_IS_CONFIG_FILE_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE_PARSER))
#define QETESH_IS_CONFIG_FILE_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE_PARSER))
#define QETESH_CONFIG_FILE_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParserClass))

typedef struct _QeteshConfigFileParser QeteshConfigFileParser;
typedef struct _QeteshConfigFileParserClass QeteshConfigFileParserClass;
typedef struct _QeteshConfigFileParserPrivate QeteshConfigFileParserPrivate;

#define QETESH_CONFIG_FILE_TYPE_MOD_CONFIG (qetesh_config_file_mod_config_get_type ())
#define QETESH_CONFIG_FILE_MOD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfig))
#define QETESH_CONFIG_FILE_MOD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfigClass))
#define QETESH_CONFIG_FILE_IS_MOD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG))
#define QETESH_CONFIG_FILE_IS_MOD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG))
#define QETESH_CONFIG_FILE_MOD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_MOD_CONFIG, QeteshConfigFileModConfigClass))

typedef struct _QeteshConfigFileModConfig QeteshConfigFileModConfig;
typedef struct _QeteshConfigFileModConfigClass QeteshConfigFileModConfigClass;

#define QETESH_CONFIG_FILE_TYPE_DB_CONFIG (qetesh_config_file_db_config_get_type ())
#define QETESH_CONFIG_FILE_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfig))
#define QETESH_CONFIG_FILE_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_DB_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))

typedef struct _QeteshConfigFileDBConfig QeteshConfigFileDBConfig;
typedef struct _QeteshConfigFileDBConfigClass QeteshConfigFileDBConfigClass;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
#define _qetesh_config_file_mod_config_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_config_file_mod_config_unref (var), NULL)))
#define _qetesh_config_file_db_config_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_config_file_db_config_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
typedef struct _QeteshConfigFileModConfigPrivate QeteshConfigFileModConfigPrivate;
typedef struct _QeteshConfigFileDBConfigPrivate QeteshConfigFileDBConfigPrivate;

struct _QeteshConfigFileParser {
	GObject parent_instance;
	QeteshConfigFileParserPrivate * priv;
};

struct _QeteshConfigFileParserClass {
	GObjectClass parent_class;
};

struct _QeteshConfigFileParserPrivate {
	QeteshConfigFileModConfig* currentMod;
	QeteshConfigFileDBConfig* currentDB;
	QeteshWebServerContext* context;
	GDataInputStream* file;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;

struct _QeteshConfigFileModConfig {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshConfigFileModConfigPrivate * priv;
	gchar* LibPath;
	gchar* LoaderName;
	gchar* Nick;
	GeeLinkedList* Hosts;
};

struct _QeteshConfigFileModConfigClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshConfigFileModConfig *self);
};

struct _QeteshConfigFileDBConfig {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshConfigFileDBConfigPrivate * priv;
	GeeLinkedList* AllowedTypes;
	gchar* Connector;
	gchar* Host;
	guint16 Port;
	gchar* Username;
	gchar* Password;
	gchar* DBName;
	gchar* Nick;
};

struct _QeteshConfigFileDBConfigClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshConfigFileDBConfig *self);
};


static gpointer qetesh_config_file_parser_parent_class = NULL;

GType qetesh_config_file_parser_get_type (void) G_GNUC_CONST;
gpointer qetesh_config_file_mod_config_ref (gpointer instance);
void qetesh_config_file_mod_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_mod_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_mod_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_mod_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_mod_config (const GValue* value);
GType qetesh_config_file_mod_config_get_type (void) G_GNUC_CONST;
gpointer qetesh_config_file_db_config_ref (gpointer instance);
void qetesh_config_file_db_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_db_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_db_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_db_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_db_config (const GValue* value);
GType qetesh_config_file_db_config_get_type (void) G_GNUC_CONST;
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
#define QETESH_CONFIG_FILE_PARSER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParserPrivate))
enum  {
	QETESH_CONFIG_FILE_PARSER_DUMMY_PROPERTY
};
QeteshConfigFileParser* qetesh_config_file_parser_new (GDataInputStream* confFile, QeteshWebServerContext* sc);
QeteshConfigFileParser* qetesh_config_file_parser_construct (GType object_type, GDataInputStream* confFile, QeteshWebServerContext* sc);
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
void qetesh_config_file_parser_ReadInto (QeteshConfigFileParser* self, QeteshConfigFile* cfg);
GeeLinkedList* qetesh_config_file_get_Modules (QeteshConfigFile* self);
GeeLinkedList* qetesh_config_file_get_Databases (QeteshConfigFile* self);
static void qetesh_config_file_parser_ParseModule (QeteshConfigFileParser* self, const gchar* dir, const gchar* arg);
static void qetesh_config_file_parser_ParseDatabase (QeteshConfigFileParser* self, const gchar* dir, const gchar* arg);
void qetesh_config_file_set_ListenAddr (QeteshConfigFile* self, const gchar* value);
void qetesh_config_file_set_ListenPort (QeteshConfigFile* self, guint16 value);
void qetesh_config_file_set_MaxThreads (QeteshConfigFile* self, gint value);
QeteshConfigFileModConfig* qetesh_config_file_mod_config_new (void);
QeteshConfigFileModConfig* qetesh_config_file_mod_config_construct (GType object_type);
QeteshConfigFileDBConfig* qetesh_config_file_db_config_new (void);
QeteshConfigFileDBConfig* qetesh_config_file_db_config_construct (GType object_type);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
static void qetesh_config_file_parser_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


QeteshConfigFileParser* qetesh_config_file_parser_construct (GType object_type, GDataInputStream* confFile, QeteshWebServerContext* sc) {
	QeteshConfigFileParser * self = NULL;
	QeteshWebServerContext* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	GDataInputStream* _tmp2_ = NULL;
	GDataInputStream* _tmp3_ = NULL;
	g_return_val_if_fail (confFile != NULL, NULL);
	g_return_val_if_fail (sc != NULL, NULL);
	self = (QeteshConfigFileParser*) g_object_new (object_type, NULL);
	_tmp0_ = sc;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->context);
	self->priv->context = _tmp1_;
	_tmp2_ = confFile;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->priv->file);
	self->priv->file = _tmp3_;
	return self;
}


QeteshConfigFileParser* qetesh_config_file_parser_new (GDataInputStream* confFile, QeteshWebServerContext* sc) {
	return qetesh_config_file_parser_construct (QETESH_TYPE_CONFIG_FILE_PARSER, confFile, sc);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) (-1), 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp5_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally6;
	__catch6_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally6:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


void qetesh_config_file_parser_ReadInto (QeteshConfigFileParser* self, QeteshConfigFile* cfg) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cfg != NULL);
	{
		gchar* line = NULL;
		while (TRUE) {
			gchar* _tmp0_ = NULL;
			GDataInputStream* _tmp1_ = NULL;
			gchar* _tmp2_ = NULL;
			const gchar* _tmp3_ = NULL;
			const gchar* _tmp4_ = NULL;
			gchar* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			gchar* statement = NULL;
			const gchar* _tmp8_ = NULL;
			gchar** _tmp9_ = NULL;
			gchar** _tmp10_ = NULL;
			gchar** _tmp11_ = NULL;
			gint _tmp11__length1 = 0;
			const gchar* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			gchar** parts = NULL;
			const gchar* _tmp18_ = NULL;
			gchar** _tmp19_ = NULL;
			gchar** _tmp20_ = NULL;
			gint parts_length1 = 0;
			gint _parts_size_ = 0;
			gchar** _tmp21_ = NULL;
			gint _tmp21__length1 = 0;
			const gchar* _tmp22_ = NULL;
			gchar** _tmp33_ = NULL;
			gint _tmp33__length1 = 0;
			gchar* dir = NULL;
			gchar** _tmp34_ = NULL;
			gint _tmp34__length1 = 0;
			const gchar* _tmp35_ = NULL;
			gchar* _tmp36_ = NULL;
			gchar* arg = NULL;
			gchar** _tmp37_ = NULL;
			gint _tmp37__length1 = 0;
			const gchar* _tmp38_ = NULL;
			gchar* _tmp39_ = NULL;
			QeteshConfigFileModConfig* _tmp40_ = NULL;
			QeteshConfigFileDBConfig* _tmp43_ = NULL;
			const gchar* _tmp46_ = NULL;
			const gchar* _tmp47_ = NULL;
			GQuark _tmp49_ = 0U;
			static GQuark _tmp48_label0 = 0;
			static GQuark _tmp48_label1 = 0;
			static GQuark _tmp48_label2 = 0;
			static GQuark _tmp48_label3 = 0;
			static GQuark _tmp48_label4 = 0;
			_tmp1_ = self->priv->file;
			_tmp2_ = g_data_input_stream_read_line (_tmp1_, NULL, NULL, &_inner_error_);
			_tmp0_ = _tmp2_;
			if (_inner_error_ != NULL) {
				_g_free0 (line);
				goto __catch5_g_error;
			}
			_g_free0 (line);
			line = _tmp0_;
			_tmp3_ = line;
			if (!(_tmp3_ != NULL)) {
				break;
			}
			_tmp4_ = line;
			_tmp5_ = string_strip (_tmp4_);
			_tmp6_ = _tmp5_;
			_tmp7_ = g_strcmp0 (_tmp6_, "") == 0;
			_g_free0 (_tmp6_);
			if (_tmp7_) {
				continue;
			}
			_tmp8_ = line;
			_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, "#", 1);
			_tmp11_ = _tmp10_;
			_tmp11__length1 = _vala_array_length (_tmp9_);
			_tmp12_ = _tmp11_[0];
			_tmp13_ = string_strip (_tmp12_);
			_tmp14_ = _tmp13_;
			_tmp15_ = string_replace (_tmp14_, "	", "");
			_tmp16_ = _tmp15_;
			_g_free0 (_tmp14_);
			_tmp11_ = (_vala_array_free (_tmp11_, _tmp11__length1, (GDestroyNotify) g_free), NULL);
			statement = _tmp16_;
			_tmp17_ = statement;
			if (g_strcmp0 (_tmp17_, "") == 0) {
				_g_free0 (statement);
				continue;
			}
			_tmp18_ = statement;
			_tmp20_ = _tmp19_ = g_strsplit (_tmp18_, " ", 2);
			parts = _tmp20_;
			parts_length1 = _vala_array_length (_tmp19_);
			_parts_size_ = parts_length1;
			_tmp21_ = parts;
			_tmp21__length1 = parts_length1;
			_tmp22_ = _tmp21_[0];
			if (g_strcmp0 (_tmp22_, "}") == 0) {
				QeteshConfigFileModConfig* _tmp23_ = NULL;
				_tmp23_ = self->priv->currentMod;
				if (_tmp23_ != NULL) {
					QeteshConfigFile* _tmp24_ = NULL;
					GeeLinkedList* _tmp25_ = NULL;
					GeeLinkedList* _tmp26_ = NULL;
					QeteshConfigFileModConfig* _tmp27_ = NULL;
					_tmp24_ = cfg;
					_tmp25_ = qetesh_config_file_get_Modules (_tmp24_);
					_tmp26_ = _tmp25_;
					_tmp27_ = self->priv->currentMod;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp26_, _tmp27_);
					_qetesh_config_file_mod_config_unref0 (self->priv->currentMod);
					self->priv->currentMod = NULL;
				} else {
					QeteshConfigFileDBConfig* _tmp28_ = NULL;
					_tmp28_ = self->priv->currentDB;
					if (_tmp28_ != NULL) {
						QeteshConfigFile* _tmp29_ = NULL;
						GeeLinkedList* _tmp30_ = NULL;
						GeeLinkedList* _tmp31_ = NULL;
						QeteshConfigFileDBConfig* _tmp32_ = NULL;
						_tmp29_ = cfg;
						_tmp30_ = qetesh_config_file_get_Databases (_tmp29_);
						_tmp31_ = _tmp30_;
						_tmp32_ = self->priv->currentDB;
						gee_abstract_collection_add ((GeeAbstractCollection*) _tmp31_, _tmp32_);
						_qetesh_config_file_db_config_unref0 (self->priv->currentDB);
						self->priv->currentDB = NULL;
					}
				}
			}
			_tmp33_ = parts;
			_tmp33__length1 = parts_length1;
			if (_tmp33__length1 != 2) {
				parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (statement);
				continue;
			}
			_tmp34_ = parts;
			_tmp34__length1 = parts_length1;
			_tmp35_ = _tmp34_[0];
			_tmp36_ = g_strdup (_tmp35_);
			dir = _tmp36_;
			_tmp37_ = parts;
			_tmp37__length1 = parts_length1;
			_tmp38_ = _tmp37_[1];
			_tmp39_ = g_strdup (_tmp38_);
			arg = _tmp39_;
			_tmp40_ = self->priv->currentMod;
			if (_tmp40_ != NULL) {
				const gchar* _tmp41_ = NULL;
				const gchar* _tmp42_ = NULL;
				_tmp41_ = dir;
				_tmp42_ = arg;
				qetesh_config_file_parser_ParseModule (self, _tmp41_, _tmp42_);
				_g_free0 (arg);
				_g_free0 (dir);
				parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (statement);
				continue;
			}
			_tmp43_ = self->priv->currentDB;
			if (_tmp43_ != NULL) {
				const gchar* _tmp44_ = NULL;
				const gchar* _tmp45_ = NULL;
				_tmp44_ = dir;
				_tmp45_ = arg;
				qetesh_config_file_parser_ParseDatabase (self, _tmp44_, _tmp45_);
				_g_free0 (arg);
				_g_free0 (dir);
				parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (statement);
				continue;
			}
			_tmp46_ = dir;
			_tmp47_ = _tmp46_;
			_tmp49_ = (NULL == _tmp47_) ? 0 : g_quark_from_string (_tmp47_);
			if (_tmp49_ == ((0 != _tmp48_label0) ? _tmp48_label0 : (_tmp48_label0 = g_quark_from_static_string ("BindAddress")))) {
				switch (0) {
					default:
					{
						QeteshConfigFile* _tmp50_ = NULL;
						const gchar* _tmp51_ = NULL;
						_tmp50_ = cfg;
						_tmp51_ = arg;
						qetesh_config_file_set_ListenAddr (_tmp50_, _tmp51_);
						break;
					}
				}
			} else if (_tmp49_ == ((0 != _tmp48_label1) ? _tmp48_label1 : (_tmp48_label1 = g_quark_from_static_string ("ListenPort")))) {
				switch (0) {
					default:
					{
						QeteshConfigFile* _tmp52_ = NULL;
						const gchar* _tmp53_ = NULL;
						gint _tmp54_ = 0;
						_tmp52_ = cfg;
						_tmp53_ = arg;
						_tmp54_ = atoi (_tmp53_);
						qetesh_config_file_set_ListenPort (_tmp52_, (guint16) _tmp54_);
						break;
					}
				}
			} else if (_tmp49_ == ((0 != _tmp48_label2) ? _tmp48_label2 : (_tmp48_label2 = g_quark_from_static_string ("MaxThreads")))) {
				switch (0) {
					default:
					{
						QeteshConfigFile* _tmp55_ = NULL;
						const gchar* _tmp56_ = NULL;
						gint _tmp57_ = 0;
						_tmp55_ = cfg;
						_tmp56_ = arg;
						_tmp57_ = atoi (_tmp56_);
						qetesh_config_file_set_MaxThreads (_tmp55_, _tmp57_);
						break;
					}
				}
			} else if (_tmp49_ == ((0 != _tmp48_label3) ? _tmp48_label3 : (_tmp48_label3 = g_quark_from_static_string ("Module")))) {
				switch (0) {
					default:
					{
						QeteshConfigFileModConfig* _tmp58_ = NULL;
						_tmp58_ = qetesh_config_file_mod_config_new ();
						_qetesh_config_file_mod_config_unref0 (self->priv->currentMod);
						self->priv->currentMod = _tmp58_;
						break;
					}
				}
			} else if (_tmp49_ == ((0 != _tmp48_label4) ? _tmp48_label4 : (_tmp48_label4 = g_quark_from_static_string ("Database")))) {
				switch (0) {
					default:
					{
						QeteshConfigFileDBConfig* _tmp59_ = NULL;
						_tmp59_ = qetesh_config_file_db_config_new ();
						_qetesh_config_file_db_config_unref0 (self->priv->currentDB);
						self->priv->currentDB = _tmp59_;
						break;
					}
				}
			}
			_g_free0 (arg);
			_g_free0 (dir);
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (statement);
		}
		_g_free0 (line);
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		QeteshWebServerContext* _tmp60_ = NULL;
		QeteshErrorManager* _tmp61_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp60_ = self->priv->context;
		_tmp61_ = _tmp60_->Err;
		qetesh_error_manager_WriteMessage (_tmp61_, "Error reading HTML line", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING, NULL);
		_g_error_free0 (e);
	}
	__finally5:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void qetesh_config_file_parser_ParseModule (QeteshConfigFileParser* self, const gchar* dir, const gchar* arg) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	static GQuark _tmp2_label3 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (dir != NULL);
	g_return_if_fail (arg != NULL);
	_tmp0_ = dir;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("LibPath")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileModConfig* _tmp4_ = NULL;
				const gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				_tmp4_ = self->priv->currentMod;
				_tmp5_ = arg;
				_tmp6_ = g_strdup (_tmp5_);
				_g_free0 (_tmp4_->LibPath);
				_tmp4_->LibPath = _tmp6_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("Nick")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileModConfig* _tmp7_ = NULL;
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				_tmp7_ = self->priv->currentMod;
				_tmp8_ = arg;
				_tmp9_ = g_strdup (_tmp8_);
				_g_free0 (_tmp7_->Nick);
				_tmp7_->Nick = _tmp9_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("LoaderName")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileModConfig* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				_tmp10_ = self->priv->currentMod;
				_tmp11_ = arg;
				_tmp12_ = g_strdup (_tmp11_);
				_g_free0 (_tmp10_->LoaderName);
				_tmp10_->LoaderName = _tmp12_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("Host")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileModConfig* _tmp13_ = NULL;
				GeeLinkedList* _tmp14_ = NULL;
				const gchar* _tmp15_ = NULL;
				_tmp13_ = self->priv->currentMod;
				_tmp14_ = _tmp13_->Hosts;
				_tmp15_ = arg;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, _tmp15_);
				break;
			}
		}
	}
}


static void qetesh_config_file_parser_ParseDatabase (QeteshConfigFileParser* self, const gchar* dir, const gchar* arg) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	static GQuark _tmp2_label3 = 0;
	static GQuark _tmp2_label4 = 0;
	static GQuark _tmp2_label5 = 0;
	static GQuark _tmp2_label6 = 0;
	static GQuark _tmp2_label7 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (dir != NULL);
	g_return_if_fail (arg != NULL);
	_tmp0_ = dir;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("Allow")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp4_ = NULL;
				GeeLinkedList* _tmp5_ = NULL;
				const gchar* _tmp6_ = NULL;
				_tmp4_ = self->priv->currentDB;
				_tmp5_ = _tmp4_->AllowedTypes;
				_tmp6_ = arg;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp5_, _tmp6_);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("Connector")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp7_ = NULL;
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				_tmp7_ = self->priv->currentDB;
				_tmp8_ = arg;
				_tmp9_ = g_strdup (_tmp8_);
				_g_free0 (_tmp7_->Connector);
				_tmp7_->Connector = _tmp9_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("Host")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				_tmp10_ = self->priv->currentDB;
				_tmp11_ = arg;
				_tmp12_ = g_strdup (_tmp11_);
				_g_free0 (_tmp10_->Host);
				_tmp10_->Host = _tmp12_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("Port")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp13_ = NULL;
				const gchar* _tmp14_ = NULL;
				gint _tmp15_ = 0;
				_tmp13_ = self->priv->currentDB;
				_tmp14_ = arg;
				_tmp15_ = atoi (_tmp14_);
				_tmp13_->Port = (guint16) _tmp15_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string ("Username")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				_tmp16_ = self->priv->currentDB;
				_tmp17_ = arg;
				_tmp18_ = g_strdup (_tmp17_);
				_g_free0 (_tmp16_->Username);
				_tmp16_->Username = _tmp18_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string ("Password")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp19_ = NULL;
				const gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				_tmp19_ = self->priv->currentDB;
				_tmp20_ = arg;
				_tmp21_ = g_strdup (_tmp20_);
				_g_free0 (_tmp19_->Password);
				_tmp19_->Password = _tmp21_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label6) ? _tmp2_label6 : (_tmp2_label6 = g_quark_from_static_string ("DBName")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				gchar* _tmp24_ = NULL;
				_tmp22_ = self->priv->currentDB;
				_tmp23_ = arg;
				_tmp24_ = g_strdup (_tmp23_);
				_g_free0 (_tmp22_->DBName);
				_tmp22_->DBName = _tmp24_;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label7) ? _tmp2_label7 : (_tmp2_label7 = g_quark_from_static_string ("Nick")))) {
		switch (0) {
			default:
			{
				QeteshConfigFileDBConfig* _tmp25_ = NULL;
				const gchar* _tmp26_ = NULL;
				gchar* _tmp27_ = NULL;
				_tmp25_ = self->priv->currentDB;
				_tmp26_ = arg;
				_tmp27_ = g_strdup (_tmp26_);
				_g_free0 (_tmp25_->Nick);
				_tmp25_->Nick = _tmp27_;
				break;
			}
		}
	}
}


static void qetesh_config_file_parser_class_init (QeteshConfigFileParserClass * klass) {
	qetesh_config_file_parser_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshConfigFileParserPrivate));
	G_OBJECT_CLASS (klass)->finalize = qetesh_config_file_parser_finalize;
}


static void qetesh_config_file_parser_instance_init (QeteshConfigFileParser * self) {
	self->priv = QETESH_CONFIG_FILE_PARSER_GET_PRIVATE (self);
	self->priv->currentMod = NULL;
	self->priv->currentDB = NULL;
}


static void qetesh_config_file_parser_finalize (GObject* obj) {
	QeteshConfigFileParser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_CONFIG_FILE_PARSER, QeteshConfigFileParser);
	_qetesh_config_file_mod_config_unref0 (self->priv->currentMod);
	_qetesh_config_file_db_config_unref0 (self->priv->currentDB);
	_g_object_unref0 (self->priv->context);
	_g_object_unref0 (self->priv->file);
	G_OBJECT_CLASS (qetesh_config_file_parser_parent_class)->finalize (obj);
}


GType qetesh_config_file_parser_get_type (void) {
	static volatile gsize qetesh_config_file_parser_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_config_file_parser_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshConfigFileParserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_config_file_parser_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshConfigFileParser), 0, (GInstanceInitFunc) qetesh_config_file_parser_instance_init, NULL };
		GType qetesh_config_file_parser_type_id;
		qetesh_config_file_parser_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshConfigFileParser", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_config_file_parser_type_id__volatile, qetesh_config_file_parser_type_id);
	}
	return qetesh_config_file_parser_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



