/* DataManager.c generated by valac 0.22.1, the Vala compiler
 * generated from DataManager.vala, do not modify */

/*
 * DBManager.vala
 * 
 * Manages database connections and IO
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define QETESH_DATA_TYPE_DATA_MANAGER (qetesh_data_data_manager_get_type ())
#define QETESH_DATA_DATA_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManager))
#define QETESH_DATA_DATA_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManagerClass))
#define QETESH_DATA_IS_DATA_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DATA_MANAGER))
#define QETESH_DATA_IS_DATA_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DATA_MANAGER))
#define QETESH_DATA_DATA_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManagerClass))

typedef struct _QeteshDataDataManager QeteshDataDataManager;
typedef struct _QeteshDataDataManagerClass QeteshDataDataManagerClass;
typedef struct _QeteshDataDataManagerPrivate QeteshDataDataManagerPrivate;

#define QETESH_DATA_TYPE_QDATABASE_CONN (qetesh_data_qdatabase_conn_get_type ())
#define QETESH_DATA_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConn))
#define QETESH_DATA_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))
#define QETESH_DATA_IS_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_IS_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_QDATABASE_CONN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))

typedef struct _QeteshDataQDatabaseConn QeteshDataQDatabaseConn;
typedef struct _QeteshDataQDatabaseConnClass QeteshDataQDatabaseConnClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QETESH_DATA_TYPE_QDATABASE (qetesh_data_qdatabase_get_type ())
#define QETESH_DATA_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabase))
#define QETESH_DATA_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))
#define QETESH_DATA_IS_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_IS_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_QDATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))

typedef struct _QeteshDataQDatabase QeteshDataQDatabase;
typedef struct _QeteshDataQDatabaseClass QeteshDataQDatabaseClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _qetesh_data_qdatabase_conn_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_data_qdatabase_conn_unref (var), NULL)))

struct _QeteshDataDataManager {
	GObject parent_instance;
	QeteshDataDataManagerPrivate * priv;
};

struct _QeteshDataDataManagerClass {
	GObjectClass parent_class;
};

struct _QeteshDataDataManagerPrivate {
	GeeTreeMap* _handles;
	QeteshDataDBManager* manager;
};

typedef enum  {
	QETESH_DATA_QDB_ERROR_CONNECT,
	QETESH_DATA_QDB_ERROR_QUERY
} QeteshDataQDBError;
#define QETESH_DATA_QDB_ERROR qetesh_data_qdb_error_quark ()

static gpointer qetesh_data_data_manager_parent_class = NULL;

GType qetesh_data_data_manager_get_type (void) G_GNUC_CONST;
gpointer qetesh_data_qdatabase_conn_ref (gpointer instance);
void qetesh_data_qdatabase_conn_unref (gpointer instance);
GParamSpec* qetesh_data_param_spec_qdatabase_conn (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_value_set_qdatabase_conn (GValue* value, gpointer v_object);
void qetesh_data_value_take_qdatabase_conn (GValue* value, gpointer v_object);
gpointer qetesh_data_value_get_qdatabase_conn (const GValue* value);
GType qetesh_data_qdatabase_conn_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
#define QETESH_DATA_DATA_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManagerPrivate))
enum  {
	QETESH_DATA_DATA_MANAGER_DUMMY_PROPERTY
};
QeteshDataDataManager* qetesh_data_data_manager_new (QeteshDataDBManager* dbm);
QeteshDataDataManager* qetesh_data_data_manager_construct (GType object_type, QeteshDataDBManager* dbm);
static void qetesh_data_data_manager_set_handles (QeteshDataDataManager* self, GeeTreeMap* value);
GQuark qetesh_data_qdb_error_quark (void);
QeteshDataQDatabaseConn* qetesh_data_data_manager_GetConnection (QeteshDataDataManager* self, const gchar* dbNick, GError** error);
static GeeTreeMap* qetesh_data_data_manager_get_handles (QeteshDataDataManager* self);
GType qetesh_data_qdatabase_get_type (void) G_GNUC_CONST;
GeeTreeMap* qetesh_data_db_manager_get_DBs (QeteshDataDBManager* self);
QeteshDataQDatabaseConn* qetesh_data_qdatabase_Connect (QeteshDataQDatabase* self, GError** error);
static void qetesh_data_data_manager_finalize (GObject* obj);
static void _vala_qetesh_data_data_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_data_data_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


QeteshDataDataManager* qetesh_data_data_manager_construct (GType object_type, QeteshDataDBManager* dbm) {
	QeteshDataDataManager * self = NULL;
	GeeTreeMap* _tmp0_ = NULL;
	GeeTreeMap* _tmp1_ = NULL;
	QeteshDataDBManager* _tmp2_ = NULL;
	QeteshDataDBManager* _tmp3_ = NULL;
	g_return_val_if_fail (dbm != NULL, NULL);
	self = (QeteshDataDataManager*) g_object_new (object_type, NULL);
	_tmp0_ = gee_tree_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, QETESH_DATA_TYPE_QDATABASE_CONN, (GBoxedCopyFunc) qetesh_data_qdatabase_conn_ref, qetesh_data_qdatabase_conn_unref, NULL, NULL, NULL, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	qetesh_data_data_manager_set_handles (self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	_tmp2_ = dbm;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->priv->manager);
	self->priv->manager = _tmp3_;
	return self;
}


QeteshDataDataManager* qetesh_data_data_manager_new (QeteshDataDBManager* dbm) {
	return qetesh_data_data_manager_construct (QETESH_DATA_TYPE_DATA_MANAGER, dbm);
}


QeteshDataQDatabaseConn* qetesh_data_data_manager_GetConnection (QeteshDataDataManager* self, const gchar* dbNick, GError** error) {
	QeteshDataQDatabaseConn* result = NULL;
	GeeTreeMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (dbNick != NULL, NULL);
	_tmp0_ = self->priv->_handles;
	_tmp1_ = dbNick;
	_tmp2_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, _tmp1_);
	if (_tmp2_) {
		GeeTreeMap* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gpointer _tmp5_ = NULL;
		_tmp3_ = self->priv->_handles;
		_tmp4_ = dbNick;
		_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp4_);
		result = (QeteshDataQDatabaseConn*) _tmp5_;
		return result;
	} else {
		QeteshDataDBManager* _tmp6_ = NULL;
		GeeTreeMap* _tmp7_ = NULL;
		GeeTreeMap* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		QeteshDataQDatabaseConn* conn = NULL;
		QeteshDataDBManager* _tmp16_ = NULL;
		GeeTreeMap* _tmp17_ = NULL;
		GeeTreeMap* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gpointer _tmp20_ = NULL;
		QeteshDataQDatabase* _tmp21_ = NULL;
		QeteshDataQDatabaseConn* _tmp22_ = NULL;
		QeteshDataQDatabaseConn* _tmp23_ = NULL;
		GeeTreeMap* _tmp24_ = NULL;
		const gchar* _tmp25_ = NULL;
		QeteshDataQDatabaseConn* _tmp26_ = NULL;
		_tmp6_ = self->priv->manager;
		_tmp7_ = qetesh_data_db_manager_get_DBs (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = dbNick;
		_tmp10_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp8_, _tmp9_);
		if (!_tmp10_) {
			const gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			GError* _tmp14_ = NULL;
			GError* _tmp15_ = NULL;
			_tmp11_ = dbNick;
			_tmp12_ = g_strdup_printf ("Unable to find a database with nickname %s", _tmp11_);
			_tmp13_ = _tmp12_;
			_tmp14_ = g_error_new_literal (QETESH_DATA_QDB_ERROR, QETESH_DATA_QDB_ERROR_CONNECT, _tmp13_);
			_tmp15_ = _tmp14_;
			_g_free0 (_tmp13_);
			_inner_error_ = _tmp15_;
			if (_inner_error_->domain == QETESH_DATA_QDB_ERROR) {
				g_propagate_error (error, _inner_error_);
				return NULL;
			} else {
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return NULL;
			}
		}
		_tmp16_ = self->priv->manager;
		_tmp17_ = qetesh_data_db_manager_get_DBs (_tmp16_);
		_tmp18_ = _tmp17_;
		_tmp19_ = dbNick;
		_tmp20_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp18_, _tmp19_);
		_tmp21_ = (QeteshDataQDatabase*) _tmp20_;
		_tmp22_ = qetesh_data_qdatabase_Connect (_tmp21_, &_inner_error_);
		_tmp23_ = _tmp22_;
		_g_object_unref0 (_tmp21_);
		conn = _tmp23_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == QETESH_DATA_QDB_ERROR) {
				g_propagate_error (error, _inner_error_);
				return NULL;
			} else {
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return NULL;
			}
		}
		_tmp24_ = self->priv->_handles;
		_tmp25_ = dbNick;
		_tmp26_ = conn;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp24_, _tmp25_, _tmp26_);
		result = conn;
		return result;
	}
}


static GeeTreeMap* qetesh_data_data_manager_get_handles (QeteshDataDataManager* self) {
	GeeTreeMap* result;
	GeeTreeMap* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_handles;
	result = _tmp0_;
	return result;
}


static void qetesh_data_data_manager_set_handles (QeteshDataDataManager* self, GeeTreeMap* value) {
	GeeTreeMap* _tmp0_ = NULL;
	GeeTreeMap* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_handles);
	self->priv->_handles = _tmp1_;
}


static void qetesh_data_data_manager_class_init (QeteshDataDataManagerClass * klass) {
	qetesh_data_data_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshDataDataManagerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_data_data_manager_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_data_data_manager_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_data_data_manager_finalize;
}


static void qetesh_data_data_manager_instance_init (QeteshDataDataManager * self) {
	self->priv = QETESH_DATA_DATA_MANAGER_GET_PRIVATE (self);
}


static void qetesh_data_data_manager_finalize (GObject* obj) {
	QeteshDataDataManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManager);
	_g_object_unref0 (self->priv->_handles);
	_g_object_unref0 (self->priv->manager);
	G_OBJECT_CLASS (qetesh_data_data_manager_parent_class)->finalize (obj);
}


/**
 * Data access system
 * 
 * Operates at the request level
**/
GType qetesh_data_data_manager_get_type (void) {
	static volatile gsize qetesh_data_data_manager_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_data_data_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshDataDataManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_data_data_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshDataDataManager), 0, (GInstanceInitFunc) qetesh_data_data_manager_instance_init, NULL };
		GType qetesh_data_data_manager_type_id;
		qetesh_data_data_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshDataDataManager", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_data_data_manager_type_id__volatile, qetesh_data_data_manager_type_id);
	}
	return qetesh_data_data_manager_type_id__volatile;
}


static void _vala_qetesh_data_data_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshDataDataManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManager);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_data_data_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshDataDataManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_DATA_TYPE_DATA_MANAGER, QeteshDataDataManager);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



