/* DBManager.c generated by valac 0.22.1, the Vala compiler
 * generated from DBManager.vala, do not modify */

/*
 * DBManager.vala
 * 
 * Manages database connections and IO
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;
typedef struct _QeteshDataDBManagerPrivate QeteshDataDBManagerPrivate;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;

#define QETESH_DATA_TYPE_QDATABASE (qetesh_data_qdatabase_get_type ())
#define QETESH_DATA_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabase))
#define QETESH_DATA_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))
#define QETESH_DATA_IS_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_IS_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_QDATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))

typedef struct _QeteshDataQDatabase QeteshDataQDatabase;
typedef struct _QeteshDataQDatabaseClass QeteshDataQDatabaseClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QETESH_CONFIG_FILE_TYPE_DB_CONFIG (qetesh_config_file_db_config_get_type ())
#define QETESH_CONFIG_FILE_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfig))
#define QETESH_CONFIG_FILE_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_DB_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))

typedef struct _QeteshConfigFileDBConfig QeteshConfigFileDBConfig;
typedef struct _QeteshConfigFileDBConfigClass QeteshConfigFileDBConfigClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;

#define QETESH_DATA_TYPE_QDATABASE_CONN (qetesh_data_qdatabase_conn_get_type ())
#define QETESH_DATA_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConn))
#define QETESH_DATA_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))
#define QETESH_DATA_IS_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_IS_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_QDATABASE_CONN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))

typedef struct _QeteshDataQDatabaseConn QeteshDataQDatabaseConn;
typedef struct _QeteshDataQDatabaseConnClass QeteshDataQDatabaseConnClass;
typedef struct _QeteshConfigFileDBConfigPrivate QeteshConfigFileDBConfigPrivate;

#define QETESH_DATA_TYPE_QMYSQL_DB (qetesh_data_qmysql_db_get_type ())
#define QETESH_DATA_QMYSQL_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDB))
#define QETESH_DATA_QMYSQL_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDBClass))
#define QETESH_DATA_IS_QMYSQL_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QMYSQL_DB))
#define QETESH_DATA_IS_QMYSQL_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QMYSQL_DB))
#define QETESH_DATA_QMYSQL_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDBClass))

typedef struct _QeteshDataQMysqlDB QeteshDataQMysqlDB;
typedef struct _QeteshDataQMysqlDBClass QeteshDataQMysqlDBClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
#define _qetesh_data_qdatabase_conn_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_data_qdatabase_conn_unref (var), NULL)))
#define _qetesh_config_file_db_config_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_config_file_db_config_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _QeteshDataDBManager {
	GObject parent_instance;
	QeteshDataDBManagerPrivate * priv;
};

struct _QeteshDataDBManagerClass {
	GObjectClass parent_class;
};

struct _QeteshDataDBManagerPrivate {
	QeteshWebServerContext* context;
	GeeTreeMap* _DBs;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

struct _QeteshConfigFileDBConfig {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshConfigFileDBConfigPrivate * priv;
	GeeLinkedList* AllowedTypes;
	gchar* Connector;
	gchar* Host;
	guint16 Port;
	gchar* Username;
	gchar* Password;
	gchar* DBName;
	gchar* Nick;
};

struct _QeteshConfigFileDBConfigClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshConfigFileDBConfig *self);
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;

typedef enum  {
	QETESH_DATA_QDB_ERROR_CONNECT,
	QETESH_DATA_QDB_ERROR_QUERY
} QeteshDataQDBError;
#define QETESH_DATA_QDB_ERROR qetesh_data_qdb_error_quark ()

static gpointer qetesh_data_db_manager_parent_class = NULL;

GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
GType qetesh_data_qdatabase_get_type (void) G_GNUC_CONST;
#define QETESH_DATA_DB_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerPrivate))
enum  {
	QETESH_DATA_DB_MANAGER_DUMMY_PROPERTY,
	QETESH_DATA_DB_MANAGER_DBS
};
QeteshDataDBManager* qetesh_data_db_manager_new (QeteshWebServerContext* sc);
QeteshDataDBManager* qetesh_data_db_manager_construct (GType object_type, QeteshWebServerContext* sc);
static void qetesh_data_db_manager_set_DBs (QeteshDataDBManager* self, GeeTreeMap* value);
gpointer qetesh_config_file_db_config_ref (gpointer instance);
void qetesh_config_file_db_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_db_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_db_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_db_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_db_config (const GValue* value);
GType qetesh_config_file_db_config_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GeeLinkedList* qetesh_config_file_get_Databases (QeteshConfigFile* self);
gpointer qetesh_data_qdatabase_conn_ref (gpointer instance);
void qetesh_data_qdatabase_conn_unref (gpointer instance);
GParamSpec* qetesh_data_param_spec_qdatabase_conn (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_value_set_qdatabase_conn (GValue* value, gpointer v_object);
void qetesh_data_value_take_qdatabase_conn (GValue* value, gpointer v_object);
gpointer qetesh_data_value_get_qdatabase_conn (const GValue* value);
GType qetesh_data_qdatabase_conn_get_type (void) G_GNUC_CONST;
QeteshDataQMysqlDB* qetesh_data_qmysql_db_new (QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
QeteshDataQMysqlDB* qetesh_data_qmysql_db_construct (GType object_type, QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
GType qetesh_data_qmysql_db_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
GQuark qetesh_data_qdb_error_quark (void);
QeteshDataQDatabaseConn* qetesh_data_qdatabase_Connect (QeteshDataQDatabase* self, GError** error);
gboolean qetesh_data_qdatabase_conn_get_IsConnected (QeteshDataQDatabaseConn* self);
GeeTreeMap* qetesh_data_db_manager_get_DBs (QeteshDataDBManager* self);
static void qetesh_data_db_manager_finalize (GObject* obj);
static void _vala_qetesh_data_db_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_data_db_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Initialise a DB manager and connect to databases
 * 
 * @param conf Config to get connection data from
**/
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


QeteshDataDBManager* qetesh_data_db_manager_construct (GType object_type, QeteshWebServerContext* sc) {
	QeteshDataDBManager * self = NULL;
	QeteshWebServerContext* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	GeeTreeMap* _tmp2_ = NULL;
	GeeTreeMap* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (sc != NULL, NULL);
	self = (QeteshDataDBManager*) g_object_new (object_type, NULL);
	_tmp0_ = sc;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->context);
	self->priv->context = _tmp1_;
	_tmp2_ = gee_tree_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, QETESH_DATA_TYPE_QDATABASE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL);
	_tmp3_ = _tmp2_;
	qetesh_data_db_manager_set_DBs (self, _tmp3_);
	_g_object_unref0 (_tmp3_);
	{
		GeeLinkedList* _dbConf_list = NULL;
		QeteshWebServerContext* _tmp4_ = NULL;
		QeteshConfigFile* _tmp5_ = NULL;
		GeeLinkedList* _tmp6_ = NULL;
		GeeLinkedList* _tmp7_ = NULL;
		GeeLinkedList* _tmp8_ = NULL;
		gint _dbConf_size = 0;
		GeeLinkedList* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _dbConf_index = 0;
		_tmp4_ = self->priv->context;
		_tmp5_ = _tmp4_->Configuration;
		_tmp6_ = qetesh_config_file_get_Databases (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _g_object_ref0 (_tmp7_);
		_dbConf_list = _tmp8_;
		_tmp9_ = _dbConf_list;
		_tmp10_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp9_);
		_tmp11_ = _tmp10_;
		_dbConf_size = _tmp11_;
		_dbConf_index = -1;
		while (TRUE) {
			gint _tmp12_ = 0;
			gint _tmp13_ = 0;
			gint _tmp14_ = 0;
			QeteshConfigFileDBConfig* dbConf = NULL;
			GeeLinkedList* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			gpointer _tmp17_ = NULL;
			QeteshDataQDatabase* db = NULL;
			QeteshDataQDatabaseConn* conn = NULL;
			QeteshConfigFileDBConfig* _tmp18_ = NULL;
			const gchar* _tmp19_ = NULL;
			_tmp12_ = _dbConf_index;
			_dbConf_index = _tmp12_ + 1;
			_tmp13_ = _dbConf_index;
			_tmp14_ = _dbConf_size;
			if (!(_tmp13_ < _tmp14_)) {
				break;
			}
			_tmp15_ = _dbConf_list;
			_tmp16_ = _dbConf_index;
			_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, _tmp16_);
			dbConf = (QeteshConfigFileDBConfig*) _tmp17_;
			_tmp18_ = dbConf;
			_tmp19_ = _tmp18_->Connector;
			if (g_strcmp0 (_tmp19_, "MySQL") == 0) {
				QeteshConfigFileDBConfig* _tmp20_ = NULL;
				QeteshWebServerContext* _tmp21_ = NULL;
				QeteshDataQMysqlDB* _tmp22_ = NULL;
				QeteshWebServerContext* _tmp23_ = NULL;
				QeteshErrorManager* _tmp24_ = NULL;
				QeteshConfigFileDBConfig* _tmp25_ = NULL;
				const gchar* _tmp26_ = NULL;
				gchar* _tmp27_ = NULL;
				gchar* _tmp28_ = NULL;
				_tmp20_ = dbConf;
				_tmp21_ = self->priv->context;
				_tmp22_ = qetesh_data_qmysql_db_new (_tmp20_, _tmp21_);
				_g_object_unref0 (db);
				db = (QeteshDataQDatabase*) _tmp22_;
				_tmp23_ = self->priv->context;
				_tmp24_ = _tmp23_->Err;
				_tmp25_ = dbConf;
				_tmp26_ = _tmp25_->Nick;
				_tmp27_ = g_strdup_printf ("Attempting to connect to database: %s", _tmp26_);
				_tmp28_ = _tmp27_;
				qetesh_error_manager_WriteMessage (_tmp24_, _tmp28_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
				_g_free0 (_tmp28_);
				{
					QeteshDataQDatabaseConn* _tmp29_ = NULL;
					QeteshDataQDatabase* _tmp30_ = NULL;
					QeteshDataQDatabaseConn* _tmp31_ = NULL;
					QeteshDataQDatabaseConn* _tmp32_ = NULL;
					gboolean _tmp33_ = FALSE;
					gboolean _tmp34_ = FALSE;
					_tmp30_ = db;
					_tmp31_ = qetesh_data_qdatabase_Connect (_tmp30_, &_inner_error_);
					_tmp29_ = _tmp31_;
					if (_inner_error_ != NULL) {
						if (_inner_error_->domain == QETESH_DATA_QDB_ERROR) {
							goto __catch8_qetesh_data_qdb_error;
						}
						_qetesh_data_qdatabase_conn_unref0 (conn);
						_g_object_unref0 (db);
						_qetesh_config_file_db_config_unref0 (dbConf);
						_g_object_unref0 (_dbConf_list);
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					_qetesh_data_qdatabase_conn_unref0 (conn);
					conn = _tmp29_;
					_tmp32_ = conn;
					_tmp33_ = qetesh_data_qdatabase_conn_get_IsConnected (_tmp32_);
					_tmp34_ = _tmp33_;
					if (_tmp34_) {
						GeeTreeMap* _tmp35_ = NULL;
						QeteshConfigFileDBConfig* _tmp36_ = NULL;
						const gchar* _tmp37_ = NULL;
						QeteshDataQDatabase* _tmp38_ = NULL;
						_tmp35_ = self->priv->_DBs;
						_tmp36_ = dbConf;
						_tmp37_ = _tmp36_->Nick;
						_tmp38_ = db;
						gee_abstract_map_set ((GeeAbstractMap*) _tmp35_, _tmp37_, _tmp38_);
					}
				}
				goto __finally8;
				__catch8_qetesh_data_qdb_error:
				{
					GError* e = NULL;
					QeteshWebServerContext* _tmp39_ = NULL;
					QeteshErrorManager* _tmp40_ = NULL;
					QeteshConfigFileDBConfig* _tmp41_ = NULL;
					const gchar* _tmp42_ = NULL;
					gchar* _tmp43_ = NULL;
					gchar* _tmp44_ = NULL;
					e = _inner_error_;
					_inner_error_ = NULL;
					_tmp39_ = self->priv->context;
					_tmp40_ = _tmp39_->Err;
					_tmp41_ = dbConf;
					_tmp42_ = _tmp41_->Nick;
					_tmp43_ = g_strdup_printf ("Failed to connect to database: %s", _tmp42_);
					_tmp44_ = _tmp43_;
					qetesh_error_manager_WriteMessage (_tmp40_, _tmp44_, QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR, NULL);
					_g_free0 (_tmp44_);
					_g_error_free0 (e);
				}
				__finally8:
				if (_inner_error_ != NULL) {
					_qetesh_data_qdatabase_conn_unref0 (conn);
					_g_object_unref0 (db);
					_qetesh_config_file_db_config_unref0 (dbConf);
					_g_object_unref0 (_dbConf_list);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return NULL;
				}
			} else {
				QeteshWebServerContext* _tmp45_ = NULL;
				QeteshErrorManager* _tmp46_ = NULL;
				QeteshConfigFileDBConfig* _tmp47_ = NULL;
				const gchar* _tmp48_ = NULL;
				gchar* _tmp49_ = NULL;
				gchar* _tmp50_ = NULL;
				_tmp45_ = self->priv->context;
				_tmp46_ = _tmp45_->Err;
				_tmp47_ = dbConf;
				_tmp48_ = _tmp47_->Connector;
				_tmp49_ = g_strdup_printf ("No valid connector for %s found", _tmp48_);
				_tmp50_ = _tmp49_;
				qetesh_error_manager_WriteMessage (_tmp46_, _tmp50_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
				_g_free0 (_tmp50_);
			}
			_qetesh_data_qdatabase_conn_unref0 (conn);
			_g_object_unref0 (db);
			_qetesh_config_file_db_config_unref0 (dbConf);
		}
		_g_object_unref0 (_dbConf_list);
	}
	return self;
}


QeteshDataDBManager* qetesh_data_db_manager_new (QeteshWebServerContext* sc) {
	return qetesh_data_db_manager_construct (QETESH_DATA_TYPE_DB_MANAGER, sc);
}


GeeTreeMap* qetesh_data_db_manager_get_DBs (QeteshDataDBManager* self) {
	GeeTreeMap* result;
	GeeTreeMap* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_DBs;
	result = _tmp0_;
	return result;
}


static void qetesh_data_db_manager_set_DBs (QeteshDataDBManager* self, GeeTreeMap* value) {
	GeeTreeMap* _tmp0_ = NULL;
	GeeTreeMap* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_DBs);
	self->priv->_DBs = _tmp1_;
	g_object_notify ((GObject *) self, "DBs");
}


static void qetesh_data_db_manager_class_init (QeteshDataDBManagerClass * klass) {
	qetesh_data_db_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshDataDBManagerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_data_db_manager_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_data_db_manager_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_data_db_manager_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_DATA_DB_MANAGER_DBS, g_param_spec_object ("DBs", "DBs", "DBs", GEE_TYPE_TREE_MAP, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void qetesh_data_db_manager_instance_init (QeteshDataDBManager * self) {
	self->priv = QETESH_DATA_DB_MANAGER_GET_PRIVATE (self);
}


static void qetesh_data_db_manager_finalize (GObject* obj) {
	QeteshDataDBManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager);
	_g_object_unref0 (self->priv->context);
	_g_object_unref0 (self->priv->_DBs);
	G_OBJECT_CLASS (qetesh_data_db_manager_parent_class)->finalize (obj);
}


/**
 * DB access manager
 * 
 * Establishes and stores a set of database connections
 * Operates at the server level
**/
GType qetesh_data_db_manager_get_type (void) {
	static volatile gsize qetesh_data_db_manager_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_data_db_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshDataDBManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_data_db_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshDataDBManager), 0, (GInstanceInitFunc) qetesh_data_db_manager_instance_init, NULL };
		GType qetesh_data_db_manager_type_id;
		qetesh_data_db_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshDataDBManager", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_data_db_manager_type_id__volatile, qetesh_data_db_manager_type_id);
	}
	return qetesh_data_db_manager_type_id__volatile;
}


static void _vala_qetesh_data_db_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshDataDBManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager);
	switch (property_id) {
		case QETESH_DATA_DB_MANAGER_DBS:
		g_value_set_object (value, qetesh_data_db_manager_get_DBs (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_data_db_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshDataDBManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager);
	switch (property_id) {
		case QETESH_DATA_DB_MANAGER_DBS:
		qetesh_data_db_manager_set_DBs (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



