/* ErrorManager.c generated by valac 0.22.1, the Vala compiler
 * generated from ErrorManager.vala, do not modify */

/*
 * ErrorManager.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;
typedef struct _QeteshErrorManagerPrivate QeteshErrorManagerPrivate;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

struct _QeteshErrorManager {
	GObject parent_instance;
	QeteshErrorManagerPrivate * priv;
};

struct _QeteshErrorManagerClass {
	GObjectClass parent_class;
};

struct _QeteshErrorManagerPrivate {
	gboolean _ErrToConsole;
	GeeArrayList* outputs;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;


static gpointer qetesh_error_manager_parent_class = NULL;
static FILE* qetesh_error_manager_consoleErr;
static FILE* qetesh_error_manager_consoleErr = NULL;

GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
#define QETESH_ERROR_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerPrivate))
enum  {
	QETESH_ERROR_MANAGER_DUMMY_PROPERTY,
	QETESH_ERROR_MANAGER_ERR_TO_CONSOLE
};
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
gchar* qetesh_error_manager_qerror_class_to_string (QeteshErrorManagerQErrorClass self);
#define QETESH_ERROR_MANAGER_FILE_PATH "/var/log/qetesh.log"
#define QETESH_ERROR_MANAGER_LOG_TO_CONSOLE TRUE
QeteshErrorManager* qetesh_error_manager_new (void);
QeteshErrorManager* qetesh_error_manager_construct (GType object_type);
void qetesh_error_manager_set_ErrToConsole (QeteshErrorManager* self, gboolean value);
void qetesh_error_manager_AddErrorStream (QeteshErrorManager* self, GDataOutputStream* outStr);
void qetesh_error_manager_AddErrorFile (QeteshErrorManager* self, const gchar* path);
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
gboolean qetesh_error_manager_get_ErrToConsole (QeteshErrorManager* self);
static void qetesh_error_manager_finalize (GObject* obj);
static void _vala_qetesh_error_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_error_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


gchar* qetesh_error_manager_qerror_class_to_string (QeteshErrorManagerQErrorClass self) {
	gchar* result = NULL;
	switch (self) {
		case QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR:
		{
			gchar* _tmp0_ = NULL;
			_tmp0_ = g_strdup ("Error");
			result = _tmp0_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL:
		{
			gchar* _tmp1_ = NULL;
			_tmp1_ = g_strdup ("Critical");
			result = _tmp1_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG:
		{
			gchar* _tmp2_ = NULL;
			_tmp2_ = g_strdup ("Debug");
			result = _tmp2_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING:
		{
			gchar* _tmp3_ = NULL;
			_tmp3_ = g_strdup ("Warning");
			result = _tmp3_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE:
		{
			gchar* _tmp4_ = NULL;
			_tmp4_ = g_strdup ("Best Practice");
			result = _tmp4_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR:
		{
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup ("Module Error");
			result = _tmp5_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL:
		{
			gchar* _tmp6_ = NULL;
			_tmp6_ = g_strdup ("Module Critical");
			result = _tmp6_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG:
		{
			gchar* _tmp7_ = NULL;
			_tmp7_ = g_strdup ("Module Debug");
			result = _tmp7_;
			return result;
		}
		case QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING:
		{
			gchar* _tmp8_ = NULL;
			_tmp8_ = g_strdup ("Module Warning");
			result = _tmp8_;
			return result;
		}
		default:
		{
			g_assert_not_reached ();
		}
	}
}


/**
 * Error class
 * 
 * Enumeration of error levels
**/
GType qetesh_error_manager_qerror_class_get_type (void) {
	static volatile gsize qetesh_error_manager_qerror_class_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_error_manager_qerror_class_type_id__volatile)) {
		static const GEnumValue values[] = {{QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR", "qetesh-error"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL", "qetesh-critical"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG", "qetesh-debug"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING", "qetesh-warning"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE", "qetesh-best-practice"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL", "qetesh-internal"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV, "QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV", "qetesh-internal-dev"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR, "QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR", "module-error"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL, "QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL", "module-critical"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG, "QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG", "module-debug"}, {QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING, "QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING", "module-warning"}, {0, NULL, NULL}};
		GType qetesh_error_manager_qerror_class_type_id;
		qetesh_error_manager_qerror_class_type_id = g_enum_register_static ("QeteshErrorManagerQErrorClass", values);
		g_once_init_leave (&qetesh_error_manager_qerror_class_type_id__volatile, qetesh_error_manager_qerror_class_type_id);
	}
	return qetesh_error_manager_qerror_class_type_id__volatile;
}


/**
 * Create a new error manager with no outputs, except stderr
 * if LOG_TO_CONSOLE is true in defaults above and not 
 * subsequently changed.
**/
QeteshErrorManager* qetesh_error_manager_construct (GType object_type) {
	QeteshErrorManager * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	FILE* _tmp1_ = NULL;
	self = (QeteshErrorManager*) g_object_new (object_type, NULL);
	qetesh_error_manager_set_ErrToConsole (self, QETESH_ERROR_MANAGER_LOG_TO_CONSOLE);
	_tmp0_ = gee_array_list_new (g_data_output_stream_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->outputs);
	self->priv->outputs = _tmp0_;
	_tmp1_ = stderr;
	qetesh_error_manager_consoleErr = _tmp1_;
	return self;
}


QeteshErrorManager* qetesh_error_manager_new (void) {
	return qetesh_error_manager_construct (QETESH_TYPE_ERROR_MANAGER);
}


/**
 * Add a stream for text error output
 * @param outStr Stream to write to
**/
void qetesh_error_manager_AddErrorStream (QeteshErrorManager* self, GDataOutputStream* outStr) {
	GeeArrayList* _tmp0_ = NULL;
	GDataOutputStream* _tmp1_ = NULL;
	GDataOutputStream* _tmp2_ = NULL;
	GDataOutputStream* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (outStr != NULL);
	_tmp0_ = self->priv->outputs;
	_tmp1_ = outStr;
	_tmp2_ = g_data_output_stream_new ((GOutputStream*) _tmp1_);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}


/**
 * Add a file for text error output
 * @param path Full path to file
**/
void qetesh_error_manager_AddErrorFile (QeteshErrorManager* self, const gchar* path) {
	const gchar* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	_tmp0_ = path;
	if (g_strcmp0 (_tmp0_, "") == 0) {
		qetesh_error_manager_WriteMessage (self, "Unable to open error log: file path not specified", QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL, NULL);
	}
	{
		GFile* errFile = NULL;
		const gchar* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		GFileOutputStream* _tmp3_ = NULL;
		GFileOutputStream* _tmp4_ = NULL;
		GFileOutputStream* _tmp5_ = NULL;
		GDataOutputStream* _tmp6_ = NULL;
		GDataOutputStream* _tmp7_ = NULL;
		_tmp1_ = path;
		_tmp2_ = g_file_new_for_path (_tmp1_);
		errFile = _tmp2_;
		_tmp4_ = g_file_append_to (errFile, G_FILE_CREATE_NONE, NULL, &_inner_error_);
		_tmp3_ = _tmp4_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (errFile);
			goto __catch1_g_error;
		}
		_tmp5_ = _tmp3_;
		_tmp6_ = g_data_output_stream_new ((GOutputStream*) _tmp5_);
		_tmp7_ = _tmp6_;
		qetesh_error_manager_AddErrorStream (self, _tmp7_);
		_g_object_unref0 (_tmp7_);
		_g_object_unref0 (_tmp5_);
		_g_object_unref0 (errFile);
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = path;
		_tmp9_ = g_strdup_printf ("Unable to open error log: %s", _tmp8_);
		_tmp10_ = _tmp9_;
		qetesh_error_manager_WriteMessage (self, _tmp10_, QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL, NULL);
		_g_free0 (_tmp10_);
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


/**
 * Write an error message to current output streams
 * @param message Message to write
 * @param errorClass Error classification
 * @param modName Module name (optional)
**/
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName) {
	GString* err = NULL;
	GString* _tmp0_ = NULL;
	GDateTime* dt = NULL;
	GDateTime* _tmp1_ = NULL;
	GString* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GString* _tmp11_ = NULL;
	QeteshErrorManagerQErrorClass _tmp12_ = 0;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	GString* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	GString* _tmp19_ = NULL;
	gboolean _tmp36_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = g_string_new ("");
	err = _tmp0_;
	_tmp1_ = g_date_time_new_now_local ();
	dt = _tmp1_;
	_tmp2_ = err;
	_tmp3_ = dt;
	_tmp4_ = g_date_time_format (_tmp3_, "[%F %R]");
	_tmp5_ = _tmp4_;
	g_string_append (_tmp2_, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = modName;
	if (_tmp6_ != NULL) {
		GString* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		_tmp7_ = err;
		_tmp8_ = modName;
		_tmp9_ = g_strdup_printf (" [%s]", _tmp8_);
		_tmp10_ = _tmp9_;
		g_string_append (_tmp7_, _tmp10_);
		_g_free0 (_tmp10_);
	}
	_tmp11_ = err;
	_tmp12_ = errorClass;
	_tmp13_ = qetesh_error_manager_qerror_class_to_string (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strdup_printf (" [%s] ", _tmp14_);
	_tmp16_ = _tmp15_;
	g_string_append (_tmp11_, _tmp16_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_tmp17_ = err;
	_tmp18_ = message;
	g_string_append (_tmp17_, _tmp18_);
	_tmp19_ = err;
	g_string_append (_tmp19_, "\n");
	{
		{
			GeeArrayList* _str_list = NULL;
			GeeArrayList* _tmp20_ = NULL;
			GeeArrayList* _tmp21_ = NULL;
			gint _str_size = 0;
			GeeArrayList* _tmp22_ = NULL;
			gint _tmp23_ = 0;
			gint _tmp24_ = 0;
			gint _str_index = 0;
			_tmp20_ = self->priv->outputs;
			_tmp21_ = _g_object_ref0 (_tmp20_);
			_str_list = _tmp21_;
			_tmp22_ = _str_list;
			_tmp23_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp22_);
			_tmp24_ = _tmp23_;
			_str_size = _tmp24_;
			_str_index = -1;
			while (TRUE) {
				gint _tmp25_ = 0;
				gint _tmp26_ = 0;
				gint _tmp27_ = 0;
				GDataOutputStream* str = NULL;
				GeeArrayList* _tmp28_ = NULL;
				gint _tmp29_ = 0;
				gpointer _tmp30_ = NULL;
				GDataOutputStream* _tmp31_ = NULL;
				GString* _tmp32_ = NULL;
				const gchar* _tmp33_ = NULL;
				guint8* _tmp34_ = NULL;
				gint _tmp34__length1 = 0;
				guint8* _tmp35_ = NULL;
				gint _tmp35__length1 = 0;
				_tmp25_ = _str_index;
				_str_index = _tmp25_ + 1;
				_tmp26_ = _str_index;
				_tmp27_ = _str_size;
				if (!(_tmp26_ < _tmp27_)) {
					break;
				}
				_tmp28_ = _str_list;
				_tmp29_ = _str_index;
				_tmp30_ = gee_abstract_list_get ((GeeAbstractList*) _tmp28_, _tmp29_);
				str = (GDataOutputStream*) _tmp30_;
				_tmp31_ = str;
				_tmp32_ = err;
				_tmp33_ = _tmp32_->str;
				_tmp34_ = string_get_data (_tmp33_, &_tmp34__length1);
				_tmp35_ = _tmp34_;
				_tmp35__length1 = _tmp34__length1;
				g_output_stream_write ((GOutputStream*) _tmp31_, _tmp35_, (gsize) _tmp35__length1, NULL, &_inner_error_);
				if (_inner_error_ != NULL) {
					_g_object_unref0 (str);
					_g_object_unref0 (_str_list);
					goto __catch2_g_error;
				}
				_g_object_unref0 (str);
			}
			_g_object_unref0 (_str_list);
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		qetesh_error_manager_WriteMessage (self, "Error writing to log file", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR, NULL);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_date_time_unref0 (dt);
		_g_string_free0 (err);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp36_ = self->priv->_ErrToConsole;
	if (_tmp36_) {
		FILE* _tmp37_ = NULL;
		GString* _tmp38_ = NULL;
		const gchar* _tmp39_ = NULL;
		_tmp37_ = qetesh_error_manager_consoleErr;
		_tmp38_ = err;
		_tmp39_ = _tmp38_->str;
		fprintf (_tmp37_, "%s", _tmp39_);
	}
	_g_date_time_unref0 (dt);
	_g_string_free0 (err);
}


gboolean qetesh_error_manager_get_ErrToConsole (QeteshErrorManager* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_ErrToConsole;
	result = _tmp0_;
	return result;
}


void qetesh_error_manager_set_ErrToConsole (QeteshErrorManager* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ErrToConsole = _tmp0_;
	g_object_notify ((GObject *) self, "ErrToConsole");
}


static void qetesh_error_manager_class_init (QeteshErrorManagerClass * klass) {
	qetesh_error_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshErrorManagerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_error_manager_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_error_manager_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_error_manager_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_ERROR_MANAGER_ERR_TO_CONSOLE, g_param_spec_boolean ("ErrToConsole", "ErrToConsole", "ErrToConsole", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void qetesh_error_manager_instance_init (QeteshErrorManager * self) {
	self->priv = QETESH_ERROR_MANAGER_GET_PRIVATE (self);
}


static void qetesh_error_manager_finalize (GObject* obj) {
	QeteshErrorManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager);
	_g_object_unref0 (self->priv->outputs);
	G_OBJECT_CLASS (qetesh_error_manager_parent_class)->finalize (obj);
}


/** 
 * Error Manager class
 * 
 * Centralises error and debug messages and controls
 * output sources
**/
GType qetesh_error_manager_get_type (void) {
	static volatile gsize qetesh_error_manager_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_error_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshErrorManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_error_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshErrorManager), 0, (GInstanceInitFunc) qetesh_error_manager_instance_init, NULL };
		GType qetesh_error_manager_type_id;
		qetesh_error_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshErrorManager", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_error_manager_type_id__volatile, qetesh_error_manager_type_id);
	}
	return qetesh_error_manager_type_id__volatile;
}


static void _vala_qetesh_error_manager_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshErrorManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager);
	switch (property_id) {
		case QETESH_ERROR_MANAGER_ERR_TO_CONSOLE:
		g_value_set_boolean (value, qetesh_error_manager_get_ErrToConsole (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_error_manager_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshErrorManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager);
	switch (property_id) {
		case QETESH_ERROR_MANAGER_ERR_TO_CONSOLE:
		qetesh_error_manager_set_ErrToConsole (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



