/* HTMLElement.c generated by valac 0.22.1, the Vala compiler
 * generated from HTMLElement.vala, do not modify */

/*
 * HTMLElement.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define QETESH_TYPE_HTML_ELEMENT (qetesh_html_element_get_type ())
#define QETESH_HTML_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElement))
#define QETESH_HTML_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElementClass))
#define QETESH_IS_HTML_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTML_ELEMENT))
#define QETESH_IS_HTML_ELEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTML_ELEMENT))
#define QETESH_HTML_ELEMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElementClass))

typedef struct _QeteshHTMLElement QeteshHTMLElement;
typedef struct _QeteshHTMLElementClass QeteshHTMLElementClass;
typedef struct _QeteshHTMLElementPrivate QeteshHTMLElementPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define QETESH_TYPE_QEVENT (qetesh_qevent_get_type ())
#define QETESH_QEVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QEVENT, QeteshQEvent))
#define QETESH_QEVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_QEVENT, QeteshQEventClass))
#define QETESH_IS_QEVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QEVENT))
#define QETESH_IS_QEVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_QEVENT))
#define QETESH_QEVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_QEVENT, QeteshQEventClass))

typedef struct _QeteshQEvent QeteshQEvent;
typedef struct _QeteshQEventClass QeteshQEventClass;

#define QETESH_DATA_TYPE_DATA_OBJECT (qetesh_data_data_object_get_type ())
#define QETESH_DATA_DATA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DATA_OBJECT, QeteshDataDataObject))
#define QETESH_DATA_DATA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DATA_OBJECT, QeteshDataDataObjectClass))
#define QETESH_DATA_IS_DATA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DATA_OBJECT))
#define QETESH_DATA_IS_DATA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DATA_OBJECT))
#define QETESH_DATA_DATA_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DATA_OBJECT, QeteshDataDataObjectClass))

typedef struct _QeteshDataDataObject QeteshDataDataObject;
typedef struct _QeteshDataDataObjectClass QeteshDataDataObjectClass;

struct _QeteshHTMLElement {
	GObject parent_instance;
	QeteshHTMLElementPrivate * priv;
};

struct _QeteshHTMLElementClass {
	GObjectClass parent_class;
};

struct _QeteshHTMLElementPrivate {
	GeeLinkedList* children;
	gchar* _Content;
	gchar* _Val;
	gchar* _Selector;
};

typedef void (*QeteshHTMLElementPropogateCallback) (QeteshDataDataObject* datum, QeteshHTMLElement* elem, void* user_data);

static gpointer qetesh_html_element_parent_class = NULL;

GType qetesh_html_element_get_type (void) G_GNUC_CONST;
#define QETESH_HTML_ELEMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElementPrivate))
enum  {
	QETESH_HTML_ELEMENT_DUMMY_PROPERTY,
	QETESH_HTML_ELEMENT_CONTENT,
	QETESH_HTML_ELEMENT_VAL,
	QETESH_HTML_ELEMENT_SIZE,
	QETESH_HTML_ELEMENT_SELECTOR
};
QeteshHTMLElement* qetesh_html_element_get (QeteshHTMLElement* self, const gchar* selector);
QeteshHTMLElement* qetesh_html_element_new (const gchar* selector);
QeteshHTMLElement* qetesh_html_element_construct (GType object_type, const gchar* selector);
void qetesh_html_element_set_Selector (QeteshHTMLElement* self, const gchar* value);
QeteshHTMLElement* qetesh_html_element_Propogate (QeteshHTMLElement* self);
QeteshHTMLElement* qetesh_html_element_Replicate (QeteshHTMLElement* self, gint copies);
gpointer qetesh_qevent_ref (gpointer instance);
void qetesh_qevent_unref (gpointer instance);
GParamSpec* qetesh_param_spec_qevent (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_value_set_qevent (GValue* value, gpointer v_object);
void qetesh_value_take_qevent (GValue* value, gpointer v_object);
gpointer qetesh_value_get_qevent (const GValue* value);
GType qetesh_qevent_get_type (void) G_GNUC_CONST;
void qetesh_html_element_Attach (QeteshHTMLElement* self, QeteshQEvent* ev);
const gchar* qetesh_html_element_get_Content (QeteshHTMLElement* self);
void qetesh_html_element_set_Content (QeteshHTMLElement* self, const gchar* value);
const gchar* qetesh_html_element_get_Val (QeteshHTMLElement* self);
void qetesh_html_element_set_Val (QeteshHTMLElement* self, const gchar* value);
gint qetesh_html_element_get_size (QeteshHTMLElement* self);
const gchar* qetesh_html_element_get_Selector (QeteshHTMLElement* self);
GType qetesh_data_data_object_get_type (void) G_GNUC_CONST;
static void qetesh_html_element_finalize (GObject* obj);
static void _vala_qetesh_html_element_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_html_element_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


QeteshHTMLElement* qetesh_html_element_get (QeteshHTMLElement* self, const gchar* selector) {
	QeteshHTMLElement* result = NULL;
	const gchar* _tmp0_ = NULL;
	QeteshHTMLElement* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (selector != NULL, NULL);
	_tmp0_ = selector;
	_tmp1_ = qetesh_html_element_new (_tmp0_);
	result = _tmp1_;
	return result;
}


QeteshHTMLElement* qetesh_html_element_construct (GType object_type, const gchar* selector) {
	QeteshHTMLElement * self = NULL;
	const gchar* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	g_return_val_if_fail (selector != NULL, NULL);
	self = (QeteshHTMLElement*) g_object_new (object_type, NULL);
	_tmp0_ = selector;
	qetesh_html_element_set_Selector (self, _tmp0_);
	_tmp1_ = gee_linked_list_new (QETESH_TYPE_HTML_ELEMENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->children);
	self->priv->children = _tmp1_;
	return self;
}


QeteshHTMLElement* qetesh_html_element_new (const gchar* selector) {
	return qetesh_html_element_construct (QETESH_TYPE_HTML_ELEMENT, selector);
}


QeteshHTMLElement* qetesh_html_element_Propogate (QeteshHTMLElement* self) {
	QeteshHTMLElement* result = NULL;
	QeteshHTMLElement* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = qetesh_html_element_new ("_");
	result = _tmp0_;
	return result;
}


QeteshHTMLElement* qetesh_html_element_Replicate (QeteshHTMLElement* self, gint copies) {
	QeteshHTMLElement* result = NULL;
	QeteshHTMLElement* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = qetesh_html_element_new ("_");
	result = _tmp0_;
	return result;
}


void qetesh_html_element_Attach (QeteshHTMLElement* self, QeteshQEvent* ev) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (ev != NULL);
}


const gchar* qetesh_html_element_get_Content (QeteshHTMLElement* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Content;
	result = _tmp0_;
	return result;
}


void qetesh_html_element_set_Content (QeteshHTMLElement* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_Content);
	self->priv->_Content = _tmp1_;
	g_object_notify ((GObject *) self, "Content");
}


const gchar* qetesh_html_element_get_Val (QeteshHTMLElement* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Val;
	result = _tmp0_;
	return result;
}


void qetesh_html_element_set_Val (QeteshHTMLElement* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_Val);
	self->priv->_Val = _tmp1_;
	g_object_notify ((GObject *) self, "Val");
}


gint qetesh_html_element_get_size (QeteshHTMLElement* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = 1;
	return result;
}


const gchar* qetesh_html_element_get_Selector (QeteshHTMLElement* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Selector;
	result = _tmp0_;
	return result;
}


void qetesh_html_element_set_Selector (QeteshHTMLElement* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_Selector);
	self->priv->_Selector = _tmp1_;
	g_object_notify ((GObject *) self, "Selector");
}


static void qetesh_html_element_class_init (QeteshHTMLElementClass * klass) {
	qetesh_html_element_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshHTMLElementPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_html_element_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_html_element_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_html_element_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTML_ELEMENT_CONTENT, g_param_spec_string ("Content", "Content", "Content", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTML_ELEMENT_VAL, g_param_spec_string ("Val", "Val", "Val", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTML_ELEMENT_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTML_ELEMENT_SELECTOR, g_param_spec_string ("Selector", "Selector", "Selector", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void qetesh_html_element_instance_init (QeteshHTMLElement * self) {
	self->priv = QETESH_HTML_ELEMENT_GET_PRIVATE (self);
}


static void qetesh_html_element_finalize (GObject* obj) {
	QeteshHTMLElement * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElement);
	_g_object_unref0 (self->priv->children);
	_g_free0 (self->priv->_Content);
	_g_free0 (self->priv->_Val);
	_g_free0 (self->priv->_Selector);
	G_OBJECT_CLASS (qetesh_html_element_parent_class)->finalize (obj);
}


/**
* Represents a HTML element, or set of elements, in the user interface.
* Remember that the Vala code is flying blind - it's up to the
* Javascript to check whether said elements actually exist
**/
GType qetesh_html_element_get_type (void) {
	static volatile gsize qetesh_html_element_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_html_element_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshHTMLElementClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_html_element_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshHTMLElement), 0, (GInstanceInitFunc) qetesh_html_element_instance_init, NULL };
		GType qetesh_html_element_type_id;
		qetesh_html_element_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshHTMLElement", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_html_element_type_id__volatile, qetesh_html_element_type_id);
	}
	return qetesh_html_element_type_id__volatile;
}


static void _vala_qetesh_html_element_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshHTMLElement * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElement);
	switch (property_id) {
		case QETESH_HTML_ELEMENT_CONTENT:
		g_value_set_string (value, qetesh_html_element_get_Content (self));
		break;
		case QETESH_HTML_ELEMENT_VAL:
		g_value_set_string (value, qetesh_html_element_get_Val (self));
		break;
		case QETESH_HTML_ELEMENT_SIZE:
		g_value_set_int (value, qetesh_html_element_get_size (self));
		break;
		case QETESH_HTML_ELEMENT_SELECTOR:
		g_value_set_string (value, qetesh_html_element_get_Selector (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_html_element_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshHTMLElement * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_HTML_ELEMENT, QeteshHTMLElement);
	switch (property_id) {
		case QETESH_HTML_ELEMENT_CONTENT:
		qetesh_html_element_set_Content (self, g_value_get_string (value));
		break;
		case QETESH_HTML_ELEMENT_VAL:
		qetesh_html_element_set_Val (self, g_value_get_string (value));
		break;
		case QETESH_HTML_ELEMENT_SELECTOR:
		qetesh_html_element_set_Selector (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



