/* HTTPResponse.c generated by valac 0.22.1, the Vala compiler
 * generated from HTTPResponse.vala, do not modify */

/*
 * HTTPResponse.vala
 * 
 * Base class for HTTP responses
 * Exend to respond with HTML, JSON, XML, &c
 * Can also be used as a bare HTTP responder
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define QETESH_TYPE_HTTP_RESPONSE (qetesh_http_response_get_type ())
#define QETESH_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse))
#define QETESH_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))
#define QETESH_IS_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_IS_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_HTTP_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))

typedef struct _QeteshHTTPResponse QeteshHTTPResponse;
typedef struct _QeteshHTTPResponseClass QeteshHTTPResponseClass;
typedef struct _QeteshHTTPResponsePrivate QeteshHTTPResponsePrivate;

#define QETESH_TYPE_WEB_APP_CONTEXT (qetesh_web_app_context_get_type ())
#define QETESH_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext))
#define QETESH_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))
#define QETESH_IS_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_IS_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_WEB_APP_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))

typedef struct _QeteshWebAppContext QeteshWebAppContext;
typedef struct _QeteshWebAppContextClass QeteshWebAppContextClass;

#define QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE (qetesh_data_data_object_data_node_get_type ())
#define QETESH_DATA_DATA_OBJECT_DATA_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNode))
#define QETESH_DATA_DATA_OBJECT_DATA_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNodeClass))
#define QETESH_DATA_DATA_OBJECT_IS_DATA_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE))
#define QETESH_DATA_DATA_OBJECT_IS_DATA_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE))
#define QETESH_DATA_DATA_OBJECT_DATA_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNodeClass))

typedef struct _QeteshDataDataObjectDataNode QeteshDataDataObjectDataNode;
typedef struct _QeteshDataDataObjectDataNodeClass QeteshDataDataObjectDataNodeClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _qetesh_data_data_object_data_node_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_data_data_object_data_node_unref (var), NULL)))

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _QeteshHTTPResponse {
	GObject parent_instance;
	QeteshHTTPResponsePrivate * priv;
	GString* Content;
};

struct _QeteshHTTPResponseClass {
	GObjectClass parent_class;
	void (*Respond) (QeteshHTTPResponse* self, GDataOutputStream* httpOut);
	void (*ComposeContent) (QeteshHTTPResponse* self);
};

struct _QeteshHTTPResponsePrivate {
	gint _ResponseCode;
	gchar* _ResponseMessage;
	gchar* _ContentType;
	QeteshWebAppContext* _Context;
	QeteshDataDataObjectDataNode* _DataTree;
	GeeLinkedList* _Messages;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;


static gpointer qetesh_http_response_parent_class = NULL;

GType qetesh_http_response_get_type (void) G_GNUC_CONST;
GType qetesh_web_app_context_get_type (void) G_GNUC_CONST;
gpointer qetesh_data_data_object_data_node_ref (gpointer instance);
void qetesh_data_data_object_data_node_unref (gpointer instance);
GParamSpec* qetesh_data_data_object_param_spec_data_node (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_data_object_value_set_data_node (GValue* value, gpointer v_object);
void qetesh_data_data_object_value_take_data_node (GValue* value, gpointer v_object);
gpointer qetesh_data_data_object_value_get_data_node (const GValue* value);
GType qetesh_data_data_object_data_node_get_type (void) G_GNUC_CONST;
#define QETESH_HTTP_RESPONSE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponsePrivate))
enum  {
	QETESH_HTTP_RESPONSE_DUMMY_PROPERTY,
	QETESH_HTTP_RESPONSE_RESPONSE_CODE,
	QETESH_HTTP_RESPONSE_RESPONSE_MESSAGE,
	QETESH_HTTP_RESPONSE_CONTENT_TYPE,
	QETESH_HTTP_RESPONSE_CONTEXT,
	QETESH_HTTP_RESPONSE_DATA_TREE,
	QETESH_HTTP_RESPONSE_MESSAGES
};
#define QETESH_HTTP_RESPONSE_DEFAULT_CODE 200
#define QETESH_HTTP_RESPONSE_DEFAULT_CT "text/html"
QeteshHTTPResponse* qetesh_http_response_construct (GType object_type, QeteshWebAppContext* ctx);
void qetesh_http_response_set_ResponseCode (QeteshHTTPResponse* self, gint value);
void qetesh_http_response_set_ContentType (QeteshHTTPResponse* self, const gchar* value);
static void qetesh_http_response_set_Context (QeteshHTTPResponse* self, QeteshWebAppContext* value);
QeteshDataDataObjectDataNode* qetesh_data_data_object_data_node_new (const gchar* name, gboolean isArray);
QeteshDataDataObjectDataNode* qetesh_data_data_object_data_node_construct (GType object_type, const gchar* name, gboolean isArray);
static void qetesh_http_response_set_DataTree (QeteshHTTPResponse* self, QeteshDataDataObjectDataNode* value);
QeteshDataDataObjectDataNode* qetesh_http_response_get_DataTree (QeteshHTTPResponse* self);
void qetesh_data_data_object_data_node_set_IsArray (QeteshDataDataObjectDataNode* self, gboolean value);
static void qetesh_http_response_set_Messages (QeteshHTTPResponse* self, GeeLinkedList* value);
void qetesh_http_response_Respond (QeteshHTTPResponse* self, GDataOutputStream* httpOut);
static void qetesh_http_response_real_Respond (QeteshHTTPResponse* self, GDataOutputStream* httpOut);
void qetesh_http_response_ComposeContent (QeteshHTTPResponse* self);
gint qetesh_http_response_get_ResponseCode (QeteshHTTPResponse* self);
const gchar* qetesh_http_response_get_ResponseMessage (QeteshHTTPResponse* self);
const gchar* qetesh_http_response_get_ContentType (QeteshHTTPResponse* self);
QeteshWebAppContext* qetesh_http_response_get_Context (QeteshHTTPResponse* self);
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
static void qetesh_http_response_real_ComposeContent (QeteshHTTPResponse* self);
void qetesh_http_response_set_ResponseMessage (QeteshHTTPResponse* self, const gchar* value);
GeeLinkedList* qetesh_http_response_get_Messages (QeteshHTTPResponse* self);
static void qetesh_http_response_finalize (GObject* obj);
static void _vala_qetesh_http_response_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_http_response_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


QeteshHTTPResponse* qetesh_http_response_construct (GType object_type, QeteshWebAppContext* ctx) {
	QeteshHTTPResponse * self = NULL;
	GString* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	QeteshDataDataObjectDataNode* _tmp2_ = NULL;
	QeteshDataDataObjectDataNode* _tmp3_ = NULL;
	QeteshDataDataObjectDataNode* _tmp4_ = NULL;
	GeeLinkedList* _tmp5_ = NULL;
	GeeLinkedList* _tmp6_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	self = (QeteshHTTPResponse*) g_object_new (object_type, NULL);
	qetesh_http_response_set_ResponseCode (self, QETESH_HTTP_RESPONSE_DEFAULT_CODE);
	qetesh_http_response_set_ContentType (self, QETESH_HTTP_RESPONSE_DEFAULT_CT);
	_tmp0_ = g_string_new ("");
	_g_string_free0 (self->Content);
	self->Content = _tmp0_;
	_tmp1_ = ctx;
	qetesh_http_response_set_Context (self, _tmp1_);
	_tmp2_ = qetesh_data_data_object_data_node_new ("Data", FALSE);
	_tmp3_ = _tmp2_;
	qetesh_http_response_set_DataTree (self, _tmp3_);
	_qetesh_data_data_object_data_node_unref0 (_tmp3_);
	_tmp4_ = self->priv->_DataTree;
	qetesh_data_data_object_data_node_set_IsArray (_tmp4_, TRUE);
	_tmp5_ = gee_linked_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	_tmp6_ = _tmp5_;
	qetesh_http_response_set_Messages (self, _tmp6_);
	_g_object_unref0 (_tmp6_);
	return self;
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


static void qetesh_http_response_real_Respond (QeteshHTTPResponse* self, GDataOutputStream* httpOut) {
	gchar* content = NULL;
	GString* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GString* header = NULL;
	GString* _tmp3_ = NULL;
	GString* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	GString* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GString* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (httpOut != NULL);
	qetesh_http_response_ComposeContent (self);
	_tmp0_ = self->Content;
	_tmp1_ = _tmp0_->str;
	_tmp2_ = g_strdup (_tmp1_);
	content = _tmp2_;
	_tmp3_ = g_string_new ("");
	header = _tmp3_;
	_tmp4_ = header;
	_tmp5_ = self->priv->_ResponseCode;
	_tmp6_ = self->priv->_ResponseMessage;
	_tmp7_ = g_strdup_printf ("HTTP/1.0 %d %s\r\n", _tmp5_, _tmp6_);
	_tmp8_ = _tmp7_;
	g_string_append (_tmp4_, _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = header;
	_tmp10_ = self->priv->_ContentType;
	_tmp11_ = g_strdup_printf ("Content-Type: %s\r\n", _tmp10_);
	_tmp12_ = _tmp11_;
	g_string_append (_tmp9_, _tmp12_);
	_g_free0 (_tmp12_);
	_tmp13_ = header;
	_tmp14_ = content;
	_tmp15_ = strlen (_tmp14_);
	_tmp16_ = _tmp15_;
	g_string_append_printf (_tmp13_, "Content-Length: %lu\r\n\r\n", (gulong) _tmp16_);
	{
		GDataOutputStream* _tmp17_ = NULL;
		GString* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		guint8* _tmp20_ = NULL;
		gint _tmp20__length1 = 0;
		guint8* _tmp21_ = NULL;
		gint _tmp21__length1 = 0;
		GDataOutputStream* _tmp22_ = NULL;
		const gchar* _tmp23_ = NULL;
		guint8* _tmp24_ = NULL;
		gint _tmp24__length1 = 0;
		guint8* _tmp25_ = NULL;
		gint _tmp25__length1 = 0;
		GDataOutputStream* _tmp26_ = NULL;
		_tmp17_ = httpOut;
		_tmp18_ = header;
		_tmp19_ = _tmp18_->str;
		_tmp20_ = string_get_data (_tmp19_, &_tmp20__length1);
		_tmp21_ = _tmp20_;
		_tmp21__length1 = _tmp20__length1;
		g_output_stream_write ((GOutputStream*) _tmp17_, _tmp21_, (gsize) _tmp21__length1, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp22_ = httpOut;
		_tmp23_ = content;
		_tmp24_ = string_get_data (_tmp23_, &_tmp24__length1);
		_tmp25_ = _tmp24_;
		_tmp25__length1 = _tmp24__length1;
		g_output_stream_write ((GOutputStream*) _tmp22_, _tmp25_, (gsize) _tmp25__length1, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp26_ = httpOut;
		g_output_stream_flush ((GOutputStream*) _tmp26_, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		QeteshWebAppContext* _tmp27_ = NULL;
		QeteshWebServerContext* _tmp28_ = NULL;
		QeteshWebServerContext* _tmp29_ = NULL;
		QeteshErrorManager* _tmp30_ = NULL;
		GError* _tmp31_ = NULL;
		const gchar* _tmp32_ = NULL;
		gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp27_ = self->priv->_Context;
		_tmp28_ = qetesh_web_app_context_get_Server (_tmp27_);
		_tmp29_ = _tmp28_;
		_tmp30_ = _tmp29_->Err;
		_tmp31_ = e;
		_tmp32_ = _tmp31_->message;
		_tmp33_ = g_strdup_printf ("Unable to send response to client: %s", _tmp32_);
		_tmp34_ = _tmp33_;
		qetesh_error_manager_WriteMessage (_tmp30_, _tmp34_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING, NULL);
		_g_free0 (_tmp34_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_string_free0 (header);
		_g_free0 (content);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_string_free0 (header);
	_g_free0 (content);
}


void qetesh_http_response_Respond (QeteshHTTPResponse* self, GDataOutputStream* httpOut) {
	g_return_if_fail (self != NULL);
	QETESH_HTTP_RESPONSE_GET_CLASS (self)->Respond (self, httpOut);
}


/**
 * Implement depending on format, e.g. JSON, XML, HTML 
**/
static void qetesh_http_response_real_ComposeContent (QeteshHTTPResponse* self) {
	g_critical ("Type `%s' does not implement abstract method `qetesh_http_response_ComposeContent'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void qetesh_http_response_ComposeContent (QeteshHTTPResponse* self) {
	g_return_if_fail (self != NULL);
	QETESH_HTTP_RESPONSE_GET_CLASS (self)->ComposeContent (self);
}


gint qetesh_http_response_get_ResponseCode (QeteshHTTPResponse* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_ResponseCode;
	result = _tmp0_;
	return result;
}


void qetesh_http_response_set_ResponseCode (QeteshHTTPResponse* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ResponseCode = _tmp0_;
	g_object_notify ((GObject *) self, "ResponseCode");
}


const gchar* qetesh_http_response_get_ResponseMessage (QeteshHTTPResponse* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ResponseMessage;
	result = _tmp0_;
	return result;
}


void qetesh_http_response_set_ResponseMessage (QeteshHTTPResponse* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ResponseMessage);
	self->priv->_ResponseMessage = _tmp1_;
	g_object_notify ((GObject *) self, "ResponseMessage");
}


const gchar* qetesh_http_response_get_ContentType (QeteshHTTPResponse* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ContentType;
	result = _tmp0_;
	return result;
}


void qetesh_http_response_set_ContentType (QeteshHTTPResponse* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ContentType);
	self->priv->_ContentType = _tmp1_;
	g_object_notify ((GObject *) self, "ContentType");
}


QeteshWebAppContext* qetesh_http_response_get_Context (QeteshHTTPResponse* self) {
	QeteshWebAppContext* result;
	QeteshWebAppContext* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Context;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void qetesh_http_response_set_Context (QeteshHTTPResponse* self, QeteshWebAppContext* value) {
	QeteshWebAppContext* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Context);
	self->priv->_Context = _tmp1_;
	g_object_notify ((GObject *) self, "Context");
}


QeteshDataDataObjectDataNode* qetesh_http_response_get_DataTree (QeteshHTTPResponse* self) {
	QeteshDataDataObjectDataNode* result;
	QeteshDataDataObjectDataNode* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_DataTree;
	result = _tmp0_;
	return result;
}


static gpointer _qetesh_data_data_object_data_node_ref0 (gpointer self) {
	return self ? qetesh_data_data_object_data_node_ref (self) : NULL;
}


static void qetesh_http_response_set_DataTree (QeteshHTTPResponse* self, QeteshDataDataObjectDataNode* value) {
	QeteshDataDataObjectDataNode* _tmp0_ = NULL;
	QeteshDataDataObjectDataNode* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _qetesh_data_data_object_data_node_ref0 (_tmp0_);
	_qetesh_data_data_object_data_node_unref0 (self->priv->_DataTree);
	self->priv->_DataTree = _tmp1_;
	g_object_notify ((GObject *) self, "DataTree");
}


GeeLinkedList* qetesh_http_response_get_Messages (QeteshHTTPResponse* self) {
	GeeLinkedList* result;
	GeeLinkedList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Messages;
	result = _tmp0_;
	return result;
}


static void qetesh_http_response_set_Messages (QeteshHTTPResponse* self, GeeLinkedList* value) {
	GeeLinkedList* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Messages);
	self->priv->_Messages = _tmp1_;
	g_object_notify ((GObject *) self, "Messages");
}


static void qetesh_http_response_class_init (QeteshHTTPResponseClass * klass) {
	qetesh_http_response_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshHTTPResponsePrivate));
	QETESH_HTTP_RESPONSE_CLASS (klass)->Respond = qetesh_http_response_real_Respond;
	QETESH_HTTP_RESPONSE_CLASS (klass)->ComposeContent = qetesh_http_response_real_ComposeContent;
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_http_response_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_http_response_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_http_response_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_RESPONSE_CODE, g_param_spec_int ("ResponseCode", "ResponseCode", "ResponseCode", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_RESPONSE_MESSAGE, g_param_spec_string ("ResponseMessage", "ResponseMessage", "ResponseMessage", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_CONTENT_TYPE, g_param_spec_string ("ContentType", "ContentType", "ContentType", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_CONTEXT, g_param_spec_object ("Context", "Context", "Context", QETESH_TYPE_WEB_APP_CONTEXT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_DATA_TREE, qetesh_data_data_object_param_spec_data_node ("DataTree", "DataTree", "DataTree", QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_HTTP_RESPONSE_MESSAGES, g_param_spec_object ("Messages", "Messages", "Messages", GEE_TYPE_LINKED_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void qetesh_http_response_instance_init (QeteshHTTPResponse * self) {
	self->priv = QETESH_HTTP_RESPONSE_GET_PRIVATE (self);
}


static void qetesh_http_response_finalize (GObject* obj) {
	QeteshHTTPResponse * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse);
	_g_free0 (self->priv->_ResponseMessage);
	_g_free0 (self->priv->_ContentType);
	_g_string_free0 (self->Content);
	_g_object_unref0 (self->priv->_Context);
	_qetesh_data_data_object_data_node_unref0 (self->priv->_DataTree);
	_g_object_unref0 (self->priv->_Messages);
	G_OBJECT_CLASS (qetesh_http_response_parent_class)->finalize (obj);
}


GType qetesh_http_response_get_type (void) {
	static volatile gsize qetesh_http_response_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_http_response_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshHTTPResponseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_http_response_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshHTTPResponse), 0, (GInstanceInitFunc) qetesh_http_response_instance_init, NULL };
		GType qetesh_http_response_type_id;
		qetesh_http_response_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshHTTPResponse", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&qetesh_http_response_type_id__volatile, qetesh_http_response_type_id);
	}
	return qetesh_http_response_type_id__volatile;
}


static void _vala_qetesh_http_response_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshHTTPResponse * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse);
	switch (property_id) {
		case QETESH_HTTP_RESPONSE_RESPONSE_CODE:
		g_value_set_int (value, qetesh_http_response_get_ResponseCode (self));
		break;
		case QETESH_HTTP_RESPONSE_RESPONSE_MESSAGE:
		g_value_set_string (value, qetesh_http_response_get_ResponseMessage (self));
		break;
		case QETESH_HTTP_RESPONSE_CONTENT_TYPE:
		g_value_set_string (value, qetesh_http_response_get_ContentType (self));
		break;
		case QETESH_HTTP_RESPONSE_CONTEXT:
		g_value_set_object (value, qetesh_http_response_get_Context (self));
		break;
		case QETESH_HTTP_RESPONSE_DATA_TREE:
		qetesh_data_data_object_value_set_data_node (value, qetesh_http_response_get_DataTree (self));
		break;
		case QETESH_HTTP_RESPONSE_MESSAGES:
		g_value_set_object (value, qetesh_http_response_get_Messages (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_http_response_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshHTTPResponse * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse);
	switch (property_id) {
		case QETESH_HTTP_RESPONSE_RESPONSE_CODE:
		qetesh_http_response_set_ResponseCode (self, g_value_get_int (value));
		break;
		case QETESH_HTTP_RESPONSE_RESPONSE_MESSAGE:
		qetesh_http_response_set_ResponseMessage (self, g_value_get_string (value));
		break;
		case QETESH_HTTP_RESPONSE_CONTENT_TYPE:
		qetesh_http_response_set_ContentType (self, g_value_get_string (value));
		break;
		case QETESH_HTTP_RESPONSE_CONTEXT:
		qetesh_http_response_set_Context (self, g_value_get_object (value));
		break;
		case QETESH_HTTP_RESPONSE_DATA_TREE:
		qetesh_http_response_set_DataTree (self, qetesh_data_data_object_value_get_data_node (value));
		break;
		case QETESH_HTTP_RESPONSE_MESSAGES:
		qetesh_http_response_set_Messages (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



