/* JSONResponse.c generated by valac 0.22.1, the Vala compiler
 * generated from JSONResponse.vala, do not modify */

/*
 * JSONResponse.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define QETESH_TYPE_HTTP_RESPONSE (qetesh_http_response_get_type ())
#define QETESH_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponse))
#define QETESH_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))
#define QETESH_IS_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_IS_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTTP_RESPONSE))
#define QETESH_HTTP_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTTP_RESPONSE, QeteshHTTPResponseClass))

typedef struct _QeteshHTTPResponse QeteshHTTPResponse;
typedef struct _QeteshHTTPResponseClass QeteshHTTPResponseClass;
typedef struct _QeteshHTTPResponsePrivate QeteshHTTPResponsePrivate;

#define QETESH_TYPE_JSON_RESPONSE (qetesh_json_response_get_type ())
#define QETESH_JSON_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponse))
#define QETESH_JSON_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponseClass))
#define QETESH_IS_JSON_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_JSON_RESPONSE))
#define QETESH_IS_JSON_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_JSON_RESPONSE))
#define QETESH_JSON_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponseClass))

typedef struct _QeteshJSONResponse QeteshJSONResponse;
typedef struct _QeteshJSONResponseClass QeteshJSONResponseClass;
typedef struct _QeteshJSONResponsePrivate QeteshJSONResponsePrivate;

#define QETESH_TYPE_WEB_APP_CONTEXT (qetesh_web_app_context_get_type ())
#define QETESH_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext))
#define QETESH_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))
#define QETESH_IS_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_IS_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_WEB_APP_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))

typedef struct _QeteshWebAppContext QeteshWebAppContext;
typedef struct _QeteshWebAppContextClass QeteshWebAppContextClass;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())

#define QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE (qetesh_data_data_object_data_node_get_type ())
#define QETESH_DATA_DATA_OBJECT_DATA_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNode))
#define QETESH_DATA_DATA_OBJECT_DATA_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNodeClass))
#define QETESH_DATA_DATA_OBJECT_IS_DATA_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE))
#define QETESH_DATA_DATA_OBJECT_IS_DATA_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE))
#define QETESH_DATA_DATA_OBJECT_DATA_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_DATA_OBJECT_TYPE_DATA_NODE, QeteshDataDataObjectDataNodeClass))

typedef struct _QeteshDataDataObjectDataNode QeteshDataDataObjectDataNode;
typedef struct _QeteshDataDataObjectDataNodeClass QeteshDataDataObjectDataNodeClass;
#define _qetesh_data_data_object_data_node_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_data_data_object_data_node_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _QeteshHTTPResponse {
	GObject parent_instance;
	QeteshHTTPResponsePrivate * priv;
	GString* Content;
};

struct _QeteshHTTPResponseClass {
	GObjectClass parent_class;
	void (*Respond) (QeteshHTTPResponse* self, GDataOutputStream* httpOut);
	void (*ComposeContent) (QeteshHTTPResponse* self);
};

struct _QeteshJSONResponse {
	QeteshHTTPResponse parent_instance;
	QeteshJSONResponsePrivate * priv;
};

struct _QeteshJSONResponseClass {
	QeteshHTTPResponseClass parent_class;
};

struct _QeteshJSONResponsePrivate {
	gint tabDepth;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;


static gpointer qetesh_json_response_parent_class = NULL;

GType qetesh_http_response_get_type (void) G_GNUC_CONST;
GType qetesh_json_response_get_type (void) G_GNUC_CONST;
#define QETESH_JSON_RESPONSE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponsePrivate))
enum  {
	QETESH_JSON_RESPONSE_DUMMY_PROPERTY
};
GType qetesh_web_app_context_get_type (void) G_GNUC_CONST;
QeteshJSONResponse* qetesh_json_response_new (QeteshWebAppContext* ctx);
QeteshJSONResponse* qetesh_json_response_construct (GType object_type, QeteshWebAppContext* ctx);
QeteshHTTPResponse* qetesh_http_response_construct (GType object_type, QeteshWebAppContext* ctx);
void qetesh_http_response_set_ContentType (QeteshHTTPResponse* self, const gchar* value);
void qetesh_json_response_Tab (QeteshJSONResponse* self);
static void qetesh_json_response_real_ComposeContent (QeteshHTTPResponse* base);
QeteshWebAppContext* qetesh_http_response_get_Context (QeteshHTTPResponse* self);
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
gpointer qetesh_data_data_object_data_node_ref (gpointer instance);
void qetesh_data_data_object_data_node_unref (gpointer instance);
GParamSpec* qetesh_data_data_object_param_spec_data_node (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_data_object_value_set_data_node (GValue* value, gpointer v_object);
void qetesh_data_data_object_value_take_data_node (GValue* value, gpointer v_object);
gpointer qetesh_data_data_object_value_get_data_node (const GValue* value);
GType qetesh_data_data_object_data_node_get_type (void) G_GNUC_CONST;
void qetesh_json_response_AddJson (QeteshJSONResponse* self, QeteshDataDataObjectDataNode* node, gboolean parentIsArray);
QeteshDataDataObjectDataNode* qetesh_http_response_get_DataTree (QeteshHTTPResponse* self);
const gchar* qetesh_data_data_object_data_node_get_Name (QeteshDataDataObjectDataNode* self);
const gchar* qetesh_data_data_object_data_node_get_Val (QeteshDataDataObjectDataNode* self);
GeeLinkedList* qetesh_data_data_object_data_node_get_Children (QeteshDataDataObjectDataNode* self);
gboolean qetesh_data_data_object_data_node_get_IsArray (QeteshDataDataObjectDataNode* self);
static void qetesh_json_response_finalize (GObject* obj);


QeteshJSONResponse* qetesh_json_response_construct (GType object_type, QeteshWebAppContext* ctx) {
	QeteshJSONResponse * self = NULL;
	QeteshWebAppContext* _tmp0_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	_tmp0_ = ctx;
	self = (QeteshJSONResponse*) qetesh_http_response_construct (object_type, _tmp0_);
	qetesh_http_response_set_ContentType ((QeteshHTTPResponse*) self, "text/javascript");
	self->priv->tabDepth = 0;
	return self;
}


QeteshJSONResponse* qetesh_json_response_new (QeteshWebAppContext* ctx) {
	return qetesh_json_response_construct (QETESH_TYPE_JSON_RESPONSE, ctx);
}


void qetesh_json_response_Tab (QeteshJSONResponse* self) {
	GString* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((QeteshHTTPResponse*) self)->Content;
	g_string_append (_tmp0_, "\r\n");
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_ = FALSE;
				gint _tmp4_ = 0;
				gint _tmp5_ = 0;
				GString* _tmp6_ = NULL;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = self->priv->tabDepth;
				_tmp5_ = i;
				if (!(_tmp4_ > _tmp5_)) {
					break;
				}
				_tmp6_ = ((QeteshHTTPResponse*) self)->Content;
				g_string_append (_tmp6_, "\t");
			}
		}
	}
}


static void qetesh_json_response_real_ComposeContent (QeteshHTTPResponse* base) {
	QeteshJSONResponse * self;
	QeteshWebAppContext* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	QeteshWebServerContext* _tmp2_ = NULL;
	QeteshWebServerContext* _tmp3_ = NULL;
	QeteshErrorManager* _tmp4_ = NULL;
	QeteshDataDataObjectDataNode* _tmp5_ = NULL;
	QeteshDataDataObjectDataNode* _tmp6_ = NULL;
	self = (QeteshJSONResponse*) base;
	_tmp0_ = qetesh_http_response_get_Context ((QeteshHTTPResponse*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = qetesh_web_app_context_get_Server (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_->Err;
	qetesh_error_manager_WriteMessage (_tmp4_, "JSONResponse composing output content", QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_tmp5_ = qetesh_http_response_get_DataTree ((QeteshHTTPResponse*) self);
	_tmp6_ = _tmp5_;
	qetesh_json_response_AddJson (self, _tmp6_, TRUE);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void qetesh_json_response_AddJson (QeteshJSONResponse* self, QeteshDataDataObjectDataNode* node, gboolean parentIsArray) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp8_ = FALSE;
	QeteshDataDataObjectDataNode* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gboolean _tmp15_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (node != NULL);
	_tmp0_ = parentIsArray;
	if (!_tmp0_) {
		GString* _tmp1_ = NULL;
		GString* _tmp2_ = NULL;
		QeteshDataDataObjectDataNode* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		GString* _tmp6_ = NULL;
		GString* _tmp7_ = NULL;
		_tmp1_ = ((QeteshHTTPResponse*) self)->Content;
		g_string_append (_tmp1_, "\"");
		_tmp2_ = ((QeteshHTTPResponse*) self)->Content;
		_tmp3_ = node;
		_tmp4_ = qetesh_data_data_object_data_node_get_Name (_tmp3_);
		_tmp5_ = _tmp4_;
		g_string_append (_tmp2_, _tmp5_);
		_tmp6_ = ((QeteshHTTPResponse*) self)->Content;
		g_string_append (_tmp6_, "\"");
		_tmp7_ = ((QeteshHTTPResponse*) self)->Content;
		g_string_append (_tmp7_, " : ");
	}
	_tmp9_ = node;
	_tmp10_ = qetesh_data_data_object_data_node_get_Val (_tmp9_);
	_tmp11_ = _tmp10_;
	if (_tmp11_ != NULL) {
		QeteshDataDataObjectDataNode* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		_tmp12_ = node;
		_tmp13_ = qetesh_data_data_object_data_node_get_Val (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp8_ = g_strcmp0 (_tmp14_, "") != 0;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp15_ = _tmp8_;
	if (_tmp15_) {
		GString* _tmp16_ = NULL;
		GString* _tmp17_ = NULL;
		QeteshDataDataObjectDataNode* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		GString* _tmp21_ = NULL;
		_tmp16_ = ((QeteshHTTPResponse*) self)->Content;
		g_string_append (_tmp16_, "\"");
		_tmp17_ = ((QeteshHTTPResponse*) self)->Content;
		_tmp18_ = node;
		_tmp19_ = qetesh_data_data_object_data_node_get_Val (_tmp18_);
		_tmp20_ = _tmp19_;
		g_string_append (_tmp17_, _tmp20_);
		_tmp21_ = ((QeteshHTTPResponse*) self)->Content;
		g_string_append (_tmp21_, "\"");
	} else {
		QeteshDataDataObjectDataNode* _tmp22_ = NULL;
		GeeLinkedList* _tmp23_ = NULL;
		GeeLinkedList* _tmp24_ = NULL;
		gint _tmp25_ = 0;
		gint _tmp26_ = 0;
		_tmp22_ = node;
		_tmp23_ = qetesh_data_data_object_data_node_get_Children (_tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp24_);
		_tmp26_ = _tmp25_;
		if (_tmp26_ > 0) {
			QeteshDataDataObjectDataNode* _tmp27_ = NULL;
			gboolean _tmp28_ = FALSE;
			gboolean _tmp29_ = FALSE;
			gint _tmp32_ = 0;
			gboolean first = FALSE;
			gint _tmp52_ = 0;
			QeteshDataDataObjectDataNode* _tmp53_ = NULL;
			gboolean _tmp54_ = FALSE;
			gboolean _tmp55_ = FALSE;
			_tmp27_ = node;
			_tmp28_ = qetesh_data_data_object_data_node_get_IsArray (_tmp27_);
			_tmp29_ = _tmp28_;
			if (!_tmp29_) {
				GString* _tmp30_ = NULL;
				_tmp30_ = ((QeteshHTTPResponse*) self)->Content;
				g_string_append (_tmp30_, " { ");
			} else {
				GString* _tmp31_ = NULL;
				_tmp31_ = ((QeteshHTTPResponse*) self)->Content;
				g_string_append (_tmp31_, " [ ");
			}
			_tmp32_ = self->priv->tabDepth;
			self->priv->tabDepth = _tmp32_ + 1;
			first = TRUE;
			{
				GeeLinkedList* _cn_list = NULL;
				QeteshDataDataObjectDataNode* _tmp33_ = NULL;
				GeeLinkedList* _tmp34_ = NULL;
				GeeLinkedList* _tmp35_ = NULL;
				GeeLinkedList* _tmp36_ = NULL;
				gint _cn_size = 0;
				GeeLinkedList* _tmp37_ = NULL;
				gint _tmp38_ = 0;
				gint _tmp39_ = 0;
				gint _cn_index = 0;
				_tmp33_ = node;
				_tmp34_ = qetesh_data_data_object_data_node_get_Children (_tmp33_);
				_tmp35_ = _tmp34_;
				_tmp36_ = _g_object_ref0 (_tmp35_);
				_cn_list = _tmp36_;
				_tmp37_ = _cn_list;
				_tmp38_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp37_);
				_tmp39_ = _tmp38_;
				_cn_size = _tmp39_;
				_cn_index = -1;
				while (TRUE) {
					gint _tmp40_ = 0;
					gint _tmp41_ = 0;
					gint _tmp42_ = 0;
					QeteshDataDataObjectDataNode* cn = NULL;
					GeeLinkedList* _tmp43_ = NULL;
					gint _tmp44_ = 0;
					gpointer _tmp45_ = NULL;
					gboolean _tmp46_ = FALSE;
					QeteshDataDataObjectDataNode* _tmp48_ = NULL;
					QeteshDataDataObjectDataNode* _tmp49_ = NULL;
					gboolean _tmp50_ = FALSE;
					gboolean _tmp51_ = FALSE;
					_tmp40_ = _cn_index;
					_cn_index = _tmp40_ + 1;
					_tmp41_ = _cn_index;
					_tmp42_ = _cn_size;
					if (!(_tmp41_ < _tmp42_)) {
						break;
					}
					_tmp43_ = _cn_list;
					_tmp44_ = _cn_index;
					_tmp45_ = gee_abstract_list_get ((GeeAbstractList*) _tmp43_, _tmp44_);
					cn = (QeteshDataDataObjectDataNode*) _tmp45_;
					_tmp46_ = first;
					if (!_tmp46_) {
						GString* _tmp47_ = NULL;
						_tmp47_ = ((QeteshHTTPResponse*) self)->Content;
						g_string_append (_tmp47_, ",");
					}
					qetesh_json_response_Tab (self);
					_tmp48_ = cn;
					_tmp49_ = node;
					_tmp50_ = qetesh_data_data_object_data_node_get_IsArray (_tmp49_);
					_tmp51_ = _tmp50_;
					qetesh_json_response_AddJson (self, _tmp48_, _tmp51_);
					first = FALSE;
					_qetesh_data_data_object_data_node_unref0 (cn);
				}
				_g_object_unref0 (_cn_list);
			}
			_tmp52_ = self->priv->tabDepth;
			self->priv->tabDepth = _tmp52_ - 1;
			qetesh_json_response_Tab (self);
			_tmp53_ = node;
			_tmp54_ = qetesh_data_data_object_data_node_get_IsArray (_tmp53_);
			_tmp55_ = _tmp54_;
			if (!_tmp55_) {
				GString* _tmp56_ = NULL;
				_tmp56_ = ((QeteshHTTPResponse*) self)->Content;
				g_string_append (_tmp56_, " } ");
			} else {
				GString* _tmp57_ = NULL;
				_tmp57_ = ((QeteshHTTPResponse*) self)->Content;
				g_string_append (_tmp57_, " ] ");
			}
		} else {
			GString* _tmp58_ = NULL;
			_tmp58_ = ((QeteshHTTPResponse*) self)->Content;
			g_string_append (_tmp58_, "\"\", ");
		}
	}
}


static void qetesh_json_response_class_init (QeteshJSONResponseClass * klass) {
	qetesh_json_response_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshJSONResponsePrivate));
	QETESH_HTTP_RESPONSE_CLASS (klass)->ComposeContent = qetesh_json_response_real_ComposeContent;
	G_OBJECT_CLASS (klass)->finalize = qetesh_json_response_finalize;
}


static void qetesh_json_response_instance_init (QeteshJSONResponse * self) {
	self->priv = QETESH_JSON_RESPONSE_GET_PRIVATE (self);
}


static void qetesh_json_response_finalize (GObject* obj) {
	QeteshJSONResponse * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_JSON_RESPONSE, QeteshJSONResponse);
	G_OBJECT_CLASS (qetesh_json_response_parent_class)->finalize (obj);
}


GType qetesh_json_response_get_type (void) {
	static volatile gsize qetesh_json_response_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_json_response_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshJSONResponseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_json_response_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshJSONResponse), 0, (GInstanceInitFunc) qetesh_json_response_instance_init, NULL };
		GType qetesh_json_response_type_id;
		qetesh_json_response_type_id = g_type_register_static (QETESH_TYPE_HTTP_RESPONSE, "QeteshJSONResponse", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_json_response_type_id__volatile, qetesh_json_response_type_id);
	}
	return qetesh_json_response_type_id__volatile;
}



