/* QDatabaseConn.c generated by valac 0.22.1, the Vala compiler
 * generated from QDatabaseConn.vala, do not modify */

/*
 * QMysqlDB.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define QETESH_DATA_TYPE_QDATABASE_CONN (qetesh_data_qdatabase_conn_get_type ())
#define QETESH_DATA_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConn))
#define QETESH_DATA_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))
#define QETESH_DATA_IS_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_IS_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_QDATABASE_CONN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))

typedef struct _QeteshDataQDatabaseConn QeteshDataQDatabaseConn;
typedef struct _QeteshDataQDatabaseConnClass QeteshDataQDatabaseConnClass;
typedef struct _QeteshDataQDatabaseConnPrivate QeteshDataQDatabaseConnPrivate;
typedef struct _QeteshDataParamSpecQDatabaseConn QeteshDataParamSpecQDatabaseConn;

typedef enum  {
	QETESH_DATA_QDB_ERROR_CONNECT,
	QETESH_DATA_QDB_ERROR_QUERY
} QeteshDataQDBError;
#define QETESH_DATA_QDB_ERROR qetesh_data_qdb_error_quark ()
struct _QeteshDataQDatabaseConn {
	GTypeInstance parent_instance;
	volatile int ref_count;
	QeteshDataQDatabaseConnPrivate * priv;
};

struct _QeteshDataQDatabaseConnClass {
	GTypeClass parent_class;
	void (*finalize) (QeteshDataQDatabaseConn *self);
	GeeLinkedList* (*Q) (QeteshDataQDatabaseConn* self, const gchar* qText, GError** error);
	void (*Connect) (QeteshDataQDatabaseConn* self, GError** error);
};

struct _QeteshDataQDatabaseConnPrivate {
	gboolean _IsConnected;
};

struct _QeteshDataParamSpecQDatabaseConn {
	GParamSpec parent_instance;
};


static gpointer qetesh_data_qdatabase_conn_parent_class = NULL;

gpointer qetesh_data_qdatabase_conn_ref (gpointer instance);
void qetesh_data_qdatabase_conn_unref (gpointer instance);
GParamSpec* qetesh_data_param_spec_qdatabase_conn (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_value_set_qdatabase_conn (GValue* value, gpointer v_object);
void qetesh_data_value_take_qdatabase_conn (GValue* value, gpointer v_object);
gpointer qetesh_data_value_get_qdatabase_conn (const GValue* value);
GType qetesh_data_qdatabase_conn_get_type (void) G_GNUC_CONST;
GQuark qetesh_data_qdb_error_quark (void);
#define QETESH_DATA_QDATABASE_CONN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnPrivate))
enum  {
	QETESH_DATA_QDATABASE_CONN_DUMMY_PROPERTY
};
GeeLinkedList* qetesh_data_qdatabase_conn_Q (QeteshDataQDatabaseConn* self, const gchar* qText, GError** error);
static GeeLinkedList* qetesh_data_qdatabase_conn_real_Q (QeteshDataQDatabaseConn* self, const gchar* qText, GError** error);
void qetesh_data_qdatabase_conn_Connect (QeteshDataQDatabaseConn* self, GError** error);
static void qetesh_data_qdatabase_conn_real_Connect (QeteshDataQDatabaseConn* self, GError** error);
QeteshDataQDatabaseConn* qetesh_data_qdatabase_conn_construct (GType object_type);
gboolean qetesh_data_qdatabase_conn_get_IsConnected (QeteshDataQDatabaseConn* self);
void qetesh_data_qdatabase_conn_set_IsConnected (QeteshDataQDatabaseConn* self, gboolean value);
static void qetesh_data_qdatabase_conn_finalize (QeteshDataQDatabaseConn* obj);


static GeeLinkedList* qetesh_data_qdatabase_conn_real_Q (QeteshDataQDatabaseConn* self, const gchar* qText, GError** error) {
	g_critical ("Type `%s' does not implement abstract method `qetesh_data_qdatabase_conn_Q'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return NULL;
}


GeeLinkedList* qetesh_data_qdatabase_conn_Q (QeteshDataQDatabaseConn* self, const gchar* qText, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return QETESH_DATA_QDATABASE_CONN_GET_CLASS (self)->Q (self, qText, error);
}


static void qetesh_data_qdatabase_conn_real_Connect (QeteshDataQDatabaseConn* self, GError** error) {
	g_critical ("Type `%s' does not implement abstract method `qetesh_data_qdatabase_conn_Connect'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void qetesh_data_qdatabase_conn_Connect (QeteshDataQDatabaseConn* self, GError** error) {
	g_return_if_fail (self != NULL);
	QETESH_DATA_QDATABASE_CONN_GET_CLASS (self)->Connect (self, error);
}


QeteshDataQDatabaseConn* qetesh_data_qdatabase_conn_construct (GType object_type) {
	QeteshDataQDatabaseConn* self = NULL;
	self = (QeteshDataQDatabaseConn*) g_type_create_instance (object_type);
	return self;
}


gboolean qetesh_data_qdatabase_conn_get_IsConnected (QeteshDataQDatabaseConn* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_IsConnected;
	result = _tmp0_;
	return result;
}


void qetesh_data_qdatabase_conn_set_IsConnected (QeteshDataQDatabaseConn* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_IsConnected = _tmp0_;
}


static void qetesh_data_value_qdatabase_conn_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void qetesh_data_value_qdatabase_conn_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		qetesh_data_qdatabase_conn_unref (value->data[0].v_pointer);
	}
}


static void qetesh_data_value_qdatabase_conn_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = qetesh_data_qdatabase_conn_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer qetesh_data_value_qdatabase_conn_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* qetesh_data_value_qdatabase_conn_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		QeteshDataQDatabaseConn* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = qetesh_data_qdatabase_conn_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* qetesh_data_value_qdatabase_conn_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	QeteshDataQDatabaseConn** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = qetesh_data_qdatabase_conn_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* qetesh_data_param_spec_qdatabase_conn (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	QeteshDataParamSpecQDatabaseConn* spec;
	g_return_val_if_fail (g_type_is_a (object_type, QETESH_DATA_TYPE_QDATABASE_CONN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer qetesh_data_value_get_qdatabase_conn (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_DATA_TYPE_QDATABASE_CONN), NULL);
	return value->data[0].v_pointer;
}


void qetesh_data_value_set_qdatabase_conn (GValue* value, gpointer v_object) {
	QeteshDataQDatabaseConn* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_DATA_TYPE_QDATABASE_CONN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_DATA_TYPE_QDATABASE_CONN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		qetesh_data_qdatabase_conn_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_data_qdatabase_conn_unref (old);
	}
}


void qetesh_data_value_take_qdatabase_conn (GValue* value, gpointer v_object) {
	QeteshDataQDatabaseConn* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, QETESH_DATA_TYPE_QDATABASE_CONN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, QETESH_DATA_TYPE_QDATABASE_CONN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		qetesh_data_qdatabase_conn_unref (old);
	}
}


static void qetesh_data_qdatabase_conn_class_init (QeteshDataQDatabaseConnClass * klass) {
	qetesh_data_qdatabase_conn_parent_class = g_type_class_peek_parent (klass);
	QETESH_DATA_QDATABASE_CONN_CLASS (klass)->finalize = qetesh_data_qdatabase_conn_finalize;
	g_type_class_add_private (klass, sizeof (QeteshDataQDatabaseConnPrivate));
	QETESH_DATA_QDATABASE_CONN_CLASS (klass)->Q = qetesh_data_qdatabase_conn_real_Q;
	QETESH_DATA_QDATABASE_CONN_CLASS (klass)->Connect = qetesh_data_qdatabase_conn_real_Connect;
}


static void qetesh_data_qdatabase_conn_instance_init (QeteshDataQDatabaseConn * self) {
	self->priv = QETESH_DATA_QDATABASE_CONN_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void qetesh_data_qdatabase_conn_finalize (QeteshDataQDatabaseConn* obj) {
	QeteshDataQDatabaseConn * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConn);
}


GType qetesh_data_qdatabase_conn_get_type (void) {
	static volatile gsize qetesh_data_qdatabase_conn_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_data_qdatabase_conn_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { qetesh_data_value_qdatabase_conn_init, qetesh_data_value_qdatabase_conn_free_value, qetesh_data_value_qdatabase_conn_copy_value, qetesh_data_value_qdatabase_conn_peek_pointer, "p", qetesh_data_value_qdatabase_conn_collect_value, "p", qetesh_data_value_qdatabase_conn_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (QeteshDataQDatabaseConnClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_data_qdatabase_conn_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshDataQDatabaseConn), 0, (GInstanceInitFunc) qetesh_data_qdatabase_conn_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType qetesh_data_qdatabase_conn_type_id;
		qetesh_data_qdatabase_conn_type_id = g_type_register_fundamental (g_type_fundamental_next (), "QeteshDataQDatabaseConn", &g_define_type_info, &g_define_type_fundamental_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&qetesh_data_qdatabase_conn_type_id__volatile, qetesh_data_qdatabase_conn_type_id);
	}
	return qetesh_data_qdatabase_conn_type_id__volatile;
}


gpointer qetesh_data_qdatabase_conn_ref (gpointer instance) {
	QeteshDataQDatabaseConn* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void qetesh_data_qdatabase_conn_unref (gpointer instance) {
	QeteshDataQDatabaseConn* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		QETESH_DATA_QDATABASE_CONN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



