/* QException.c generated by valac 0.22.1, the Vala compiler
 * generated from QException.vala, do not modify */

/*
 * QException.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


typedef enum  {
	QETESH_ERRORS_QERROR_UNSPECIFIED
} QeteshErrorsQError;
#define QETESH_ERRORS_QERROR qetesh_errors_qerror_quark ()
typedef enum  {
	QETESH_ERRORS_QFILE_ERROR_ACCESS,
	QETESH_ERRORS_QFILE_ERROR_READ,
	QETESH_ERRORS_QFILE_ERROR_WRITE,
	QETESH_ERRORS_QFILE_ERROR_FORMAT
} QeteshErrorsQFileError;
#define QETESH_ERRORS_QFILE_ERROR qetesh_errors_qfile_error_quark ()
typedef enum  {
	QETESH_ERRORS_QMODULE_ERROR_LOAD,
	QETESH_ERRORS_QMODULE_ERROR_CONFIG,
	QETESH_ERRORS_QMODULE_ERROR_STRUCTURE
} QeteshErrorsQModuleError;
#define QETESH_ERRORS_QMODULE_ERROR qetesh_errors_qmodule_error_quark ()
typedef enum  {
	QETESH_ERRORS_QSANITY_ERROR_UNSPECIFIED
} QeteshErrorsQSanityError;
#define QETESH_ERRORS_QSANITY_ERROR qetesh_errors_qsanity_error_quark ()


GQuark qetesh_errors_qerror_quark (void);
GQuark qetesh_errors_qfile_error_quark (void);
GQuark qetesh_errors_qmodule_error_quark (void);
GQuark qetesh_errors_qsanity_error_quark (void);


GQuark qetesh_errors_qerror_quark (void) {
	return g_quark_from_static_string ("qetesh_errors_qerror-quark");
}


GQuark qetesh_errors_qfile_error_quark (void) {
	return g_quark_from_static_string ("qetesh_errors_qfile_error-quark");
}


GQuark qetesh_errors_qmodule_error_quark (void) {
	return g_quark_from_static_string ("qetesh_errors_qmodule_error-quark");
}


GQuark qetesh_errors_qsanity_error_quark (void) {
	return g_quark_from_static_string ("qetesh_errors_qsanity_error-quark");
}



