/* QMysqlDB.c generated by valac 0.22.1, the Vala compiler
 * generated from QMysqlDB.vala, do not modify */

/*
 * QMysqlDB.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define QETESH_DATA_TYPE_QDATABASE (qetesh_data_qdatabase_get_type ())
#define QETESH_DATA_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabase))
#define QETESH_DATA_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))
#define QETESH_DATA_IS_QDATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_IS_QDATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE))
#define QETESH_DATA_QDATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE, QeteshDataQDatabaseClass))

typedef struct _QeteshDataQDatabase QeteshDataQDatabase;
typedef struct _QeteshDataQDatabaseClass QeteshDataQDatabaseClass;
typedef struct _QeteshDataQDatabasePrivate QeteshDataQDatabasePrivate;

#define QETESH_DATA_TYPE_QDATABASE_CONN (qetesh_data_qdatabase_conn_get_type ())
#define QETESH_DATA_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConn))
#define QETESH_DATA_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))
#define QETESH_DATA_IS_QDATABASE_CONN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_IS_QDATABASE_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QDATABASE_CONN))
#define QETESH_DATA_QDATABASE_CONN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QDATABASE_CONN, QeteshDataQDatabaseConnClass))

typedef struct _QeteshDataQDatabaseConn QeteshDataQDatabaseConn;
typedef struct _QeteshDataQDatabaseConnClass QeteshDataQDatabaseConnClass;

#define QETESH_DATA_TYPE_QMYSQL_DB (qetesh_data_qmysql_db_get_type ())
#define QETESH_DATA_QMYSQL_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDB))
#define QETESH_DATA_QMYSQL_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDBClass))
#define QETESH_DATA_IS_QMYSQL_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QMYSQL_DB))
#define QETESH_DATA_IS_QMYSQL_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QMYSQL_DB))
#define QETESH_DATA_QMYSQL_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QMYSQL_DB, QeteshDataQMysqlDBClass))

typedef struct _QeteshDataQMysqlDB QeteshDataQMysqlDB;
typedef struct _QeteshDataQMysqlDBClass QeteshDataQMysqlDBClass;
typedef struct _QeteshDataQMysqlDBPrivate QeteshDataQMysqlDBPrivate;

#define QETESH_CONFIG_FILE_TYPE_DB_CONFIG (qetesh_config_file_db_config_get_type ())
#define QETESH_CONFIG_FILE_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfig))
#define QETESH_CONFIG_FILE_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_IS_DB_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_CONFIG_FILE_TYPE_DB_CONFIG))
#define QETESH_CONFIG_FILE_DB_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_CONFIG_FILE_TYPE_DB_CONFIG, QeteshConfigFileDBConfigClass))

typedef struct _QeteshConfigFileDBConfig QeteshConfigFileDBConfig;
typedef struct _QeteshConfigFileDBConfigClass QeteshConfigFileDBConfigClass;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;

#define QETESH_DATA_TYPE_QMYSQL_CONN (qetesh_data_qmysql_conn_get_type ())
#define QETESH_DATA_QMYSQL_CONN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_QMYSQL_CONN, QeteshDataQMysqlConn))
#define QETESH_DATA_QMYSQL_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_QMYSQL_CONN, QeteshDataQMysqlConnClass))
#define QETESH_DATA_IS_QMYSQL_CONN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_QMYSQL_CONN))
#define QETESH_DATA_IS_QMYSQL_CONN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_QMYSQL_CONN))
#define QETESH_DATA_QMYSQL_CONN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_QMYSQL_CONN, QeteshDataQMysqlConnClass))

typedef struct _QeteshDataQMysqlConn QeteshDataQMysqlConn;
typedef struct _QeteshDataQMysqlConnClass QeteshDataQMysqlConnClass;
#define _qetesh_data_qdatabase_conn_unref0(var) ((var == NULL) ? NULL : (var = (qetesh_data_qdatabase_conn_unref (var), NULL)))

typedef enum  {
	QETESH_DATA_QDB_ERROR_CONNECT,
	QETESH_DATA_QDB_ERROR_QUERY
} QeteshDataQDBError;
#define QETESH_DATA_QDB_ERROR qetesh_data_qdb_error_quark ()
struct _QeteshDataQDatabase {
	GObject parent_instance;
	QeteshDataQDatabasePrivate * priv;
};

struct _QeteshDataQDatabaseClass {
	GObjectClass parent_class;
	QeteshDataQDatabaseConn* (*Connect) (QeteshDataQDatabase* self, GError** error);
};

struct _QeteshDataQMysqlDB {
	QeteshDataQDatabase parent_instance;
	QeteshDataQMysqlDBPrivate * priv;
};

struct _QeteshDataQMysqlDBClass {
	QeteshDataQDatabaseClass parent_class;
};


static gpointer qetesh_data_qmysql_db_parent_class = NULL;

GType qetesh_data_qdatabase_get_type (void) G_GNUC_CONST;
gpointer qetesh_data_qdatabase_conn_ref (gpointer instance);
void qetesh_data_qdatabase_conn_unref (gpointer instance);
GParamSpec* qetesh_data_param_spec_qdatabase_conn (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_data_value_set_qdatabase_conn (GValue* value, gpointer v_object);
void qetesh_data_value_take_qdatabase_conn (GValue* value, gpointer v_object);
gpointer qetesh_data_value_get_qdatabase_conn (const GValue* value);
GType qetesh_data_qdatabase_conn_get_type (void) G_GNUC_CONST;
GQuark qetesh_data_qdb_error_quark (void);
GType qetesh_data_qmysql_db_get_type (void) G_GNUC_CONST;
enum  {
	QETESH_DATA_QMYSQL_DB_DUMMY_PROPERTY
};
gpointer qetesh_config_file_db_config_ref (gpointer instance);
void qetesh_config_file_db_config_unref (gpointer instance);
GParamSpec* qetesh_config_file_param_spec_db_config (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void qetesh_config_file_value_set_db_config (GValue* value, gpointer v_object);
void qetesh_config_file_value_take_db_config (GValue* value, gpointer v_object);
gpointer qetesh_config_file_value_get_db_config (const GValue* value);
GType qetesh_config_file_db_config_get_type (void) G_GNUC_CONST;
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
QeteshDataQMysqlDB* qetesh_data_qmysql_db_new (QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
QeteshDataQMysqlDB* qetesh_data_qmysql_db_construct (GType object_type, QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
QeteshDataQDatabase* qetesh_data_qdatabase_construct (GType object_type, QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
static QeteshDataQDatabaseConn* qetesh_data_qmysql_db_real_Connect (QeteshDataQDatabase* base, GError** error);
GType qetesh_data_qmysql_conn_get_type (void) G_GNUC_CONST;
QeteshConfigFileDBConfig* qetesh_data_qdatabase_get_Conf (QeteshDataQDatabase* self);
QeteshWebServerContext* qetesh_data_qdatabase_get_Context (QeteshDataQDatabase* self);
QeteshDataQMysqlConn* qetesh_data_qmysql_conn_new (QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
QeteshDataQMysqlConn* qetesh_data_qmysql_conn_construct (GType object_type, QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc);
void qetesh_data_qdatabase_conn_Connect (QeteshDataQDatabaseConn* self, GError** error);


QeteshDataQMysqlDB* qetesh_data_qmysql_db_construct (GType object_type, QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc) {
	QeteshDataQMysqlDB * self = NULL;
	QeteshConfigFileDBConfig* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	g_return_val_if_fail (config != NULL, NULL);
	g_return_val_if_fail (sc != NULL, NULL);
	_tmp0_ = config;
	_tmp1_ = sc;
	self = (QeteshDataQMysqlDB*) qetesh_data_qdatabase_construct (object_type, _tmp0_, _tmp1_);
	return self;
}


QeteshDataQMysqlDB* qetesh_data_qmysql_db_new (QeteshConfigFileDBConfig* config, QeteshWebServerContext* sc) {
	return qetesh_data_qmysql_db_construct (QETESH_DATA_TYPE_QMYSQL_DB, config, sc);
}


static QeteshDataQDatabaseConn* qetesh_data_qmysql_db_real_Connect (QeteshDataQDatabase* base, GError** error) {
	QeteshDataQMysqlDB * self;
	QeteshDataQDatabaseConn* result = NULL;
	QeteshDataQMysqlConn* conn = NULL;
	QeteshConfigFileDBConfig* _tmp0_ = NULL;
	QeteshConfigFileDBConfig* _tmp1_ = NULL;
	QeteshWebServerContext* _tmp2_ = NULL;
	QeteshWebServerContext* _tmp3_ = NULL;
	QeteshDataQMysqlConn* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	self = (QeteshDataQMysqlDB*) base;
	_tmp0_ = qetesh_data_qdatabase_get_Conf ((QeteshDataQDatabase*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = qetesh_data_qdatabase_get_Context ((QeteshDataQDatabase*) self);
	_tmp3_ = _tmp2_;
	_tmp4_ = qetesh_data_qmysql_conn_new (_tmp1_, _tmp3_);
	conn = _tmp4_;
	qetesh_data_qdatabase_conn_Connect ((QeteshDataQDatabaseConn*) conn, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == QETESH_DATA_QDB_ERROR) {
			g_propagate_error (error, _inner_error_);
			_qetesh_data_qdatabase_conn_unref0 (conn);
			return NULL;
		} else {
			_qetesh_data_qdatabase_conn_unref0 (conn);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	result = (QeteshDataQDatabaseConn*) conn;
	return result;
}


static void qetesh_data_qmysql_db_class_init (QeteshDataQMysqlDBClass * klass) {
	qetesh_data_qmysql_db_parent_class = g_type_class_peek_parent (klass);
	QETESH_DATA_QDATABASE_CLASS (klass)->Connect = qetesh_data_qmysql_db_real_Connect;
}


static void qetesh_data_qmysql_db_instance_init (QeteshDataQMysqlDB * self) {
}


GType qetesh_data_qmysql_db_get_type (void) {
	static volatile gsize qetesh_data_qmysql_db_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_data_qmysql_db_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshDataQMysqlDBClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_data_qmysql_db_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshDataQMysqlDB), 0, (GInstanceInitFunc) qetesh_data_qmysql_db_instance_init, NULL };
		GType qetesh_data_qmysql_db_type_id;
		qetesh_data_qmysql_db_type_id = g_type_register_static (QETESH_DATA_TYPE_QDATABASE, "QeteshDataQMysqlDB", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_data_qmysql_db_type_id__volatile, qetesh_data_qmysql_db_type_id);
	}
	return qetesh_data_qmysql_db_type_id__volatile;
}



