/* QWebApp.c generated by valac 0.22.1, the Vala compiler
 * generated from QWebApp.vala, do not modify */

/*
 * QWebApp.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define QETESH_TYPE_QWEB_APP (qetesh_qweb_app_get_type ())
#define QETESH_QWEB_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QWEB_APP, QeteshQWebApp))
#define QETESH_QWEB_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_QWEB_APP, QeteshQWebAppClass))
#define QETESH_IS_QWEB_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QWEB_APP))
#define QETESH_IS_QWEB_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_QWEB_APP))
#define QETESH_QWEB_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_QWEB_APP, QeteshQWebAppClass))

typedef struct _QeteshQWebApp QeteshQWebApp;
typedef struct _QeteshQWebAppClass QeteshQWebAppClass;
typedef struct _QeteshQWebAppPrivate QeteshQWebAppPrivate;

#define QETESH_TYPE_QWEB_NODE (qetesh_qweb_node_get_type ())
#define QETESH_QWEB_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_QWEB_NODE, QeteshQWebNode))
#define QETESH_QWEB_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_QWEB_NODE, QeteshQWebNodeClass))
#define QETESH_IS_QWEB_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_QWEB_NODE))
#define QETESH_IS_QWEB_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_QWEB_NODE))
#define QETESH_QWEB_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_QWEB_NODE, QeteshQWebNodeClass))

typedef struct _QeteshQWebNode QeteshQWebNode;
typedef struct _QeteshQWebNodeClass QeteshQWebNodeClass;

#define QETESH_TYPE_WEB_APP_CONTEXT (qetesh_web_app_context_get_type ())
#define QETESH_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext))
#define QETESH_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))
#define QETESH_IS_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_IS_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_WEB_APP_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))

typedef struct _QeteshWebAppContext QeteshWebAppContext;
typedef struct _QeteshWebAppContextClass QeteshWebAppContextClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define QETESH_TYPE_HTTP_REQUEST (qetesh_http_request_get_type ())
#define QETESH_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequest))
#define QETESH_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequestClass))
#define QETESH_IS_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_HTTP_REQUEST))
#define QETESH_IS_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_HTTP_REQUEST))
#define QETESH_HTTP_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_HTTP_REQUEST, QeteshHTTPRequestClass))

typedef struct _QeteshHTTPRequest QeteshHTTPRequest;
typedef struct _QeteshHTTPRequestClass QeteshHTTPRequestClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;

#define QETESH_ERROR_MANAGER_TYPE_QERROR_CLASS (qetesh_error_manager_qerror_class_get_type ())
typedef struct _QeteshQWebNodePrivate QeteshQWebNodePrivate;

struct _QeteshQWebApp {
	GObject parent_instance;
	QeteshQWebAppPrivate * priv;
	QeteshQWebNode* RootNode;
	QeteshWebAppContext* appContext;
};

struct _QeteshQWebAppClass {
	GObjectClass parent_class;
};

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};

typedef enum  {
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_WARNING,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_BEST_PRACTICE,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_INTERNAL_DEV,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_ERROR,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_CRITICAL,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_DEBUG,
	QETESH_ERROR_MANAGER_QERROR_CLASS_MODULE_WARNING
} QeteshErrorManagerQErrorClass;

struct _QeteshQWebNode {
	GObject parent_instance;
	QeteshQWebNodePrivate * priv;
	GeeMap* Children;
};

struct _QeteshQWebNodeClass {
	GObjectClass parent_class;
};


static gpointer qetesh_qweb_app_parent_class = NULL;

GType qetesh_qweb_app_get_type (void) G_GNUC_CONST;
GType qetesh_qweb_node_get_type (void) G_GNUC_CONST;
GType qetesh_web_app_context_get_type (void) G_GNUC_CONST;
enum  {
	QETESH_QWEB_APP_DUMMY_PROPERTY
};
QeteshQWebApp* qetesh_qweb_app_new (QeteshWebAppContext* ctx);
QeteshQWebApp* qetesh_qweb_app_construct (GType object_type, QeteshWebAppContext* ctx);
QeteshQWebNode* qetesh_qweb_node_new (const gchar* path);
QeteshQWebNode* qetesh_qweb_node_construct (GType object_type, const gchar* path);
GType qetesh_http_request_get_type (void) G_GNUC_CONST;
QeteshQWebNode* qetesh_qweb_app_GetNode (QeteshQWebApp* self, QeteshHTTPRequest* req);
const gchar* qetesh_http_request_get_Path (QeteshHTTPRequest* self);
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self);
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_qerror_class_get_type (void) G_GNUC_CONST;
void qetesh_error_manager_WriteMessage (QeteshErrorManager* self, const gchar* message, QeteshErrorManagerQErrorClass errorClass, const gchar* modName);
static void qetesh_qweb_app_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


QeteshQWebApp* qetesh_qweb_app_construct (GType object_type, QeteshWebAppContext* ctx) {
	QeteshQWebApp * self = NULL;
	QeteshWebAppContext* _tmp0_ = NULL;
	QeteshWebAppContext* _tmp1_ = NULL;
	QeteshQWebNode* _tmp2_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	self = (QeteshQWebApp*) g_object_new (object_type, NULL);
	_tmp0_ = ctx;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->appContext);
	self->appContext = _tmp1_;
	_tmp2_ = qetesh_qweb_node_new ("");
	_g_object_unref0 (self->RootNode);
	self->RootNode = _tmp2_;
	return self;
}


QeteshQWebApp* qetesh_qweb_app_new (QeteshWebAppContext* ctx) {
	return qetesh_qweb_app_construct (QETESH_TYPE_QWEB_APP, ctx);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	gboolean _tmp3_ = FALSE;
	glong _tmp9_ = 0L;
	glong _tmp15_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	glong _tmp22_ = 0L;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		glong _tmp12_ = 0L;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_ = 0L;
		glong _tmp14_ = 0L;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_ = 0L;
		glong _tmp17_ = 0L;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


QeteshQWebNode* qetesh_qweb_app_GetNode (QeteshQWebApp* self, QeteshHTTPRequest* req) {
	QeteshQWebNode* result = NULL;
	QeteshQWebNode* node = NULL;
	gchar* path = NULL;
	QeteshHTTPRequest* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp5_ = NULL;
	gboolean _tmp7_ = FALSE;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	const gchar* _tmp16_ = NULL;
	gboolean _tmp17_ = FALSE;
	QeteshWebAppContext* _tmp22_ = NULL;
	QeteshWebServerContext* _tmp23_ = NULL;
	QeteshWebServerContext* _tmp24_ = NULL;
	QeteshErrorManager* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar** parts = NULL;
	const gchar* _tmp29_ = NULL;
	gchar** _tmp30_ = NULL;
	gchar** _tmp31_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	QeteshWebAppContext* _tmp32_ = NULL;
	QeteshWebServerContext* _tmp33_ = NULL;
	QeteshWebServerContext* _tmp34_ = NULL;
	QeteshErrorManager* _tmp35_ = NULL;
	gchar** _tmp36_ = NULL;
	gint _tmp36__length1 = 0;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	QeteshQWebNode* _tmp39_ = NULL;
	QeteshQWebNode* _tmp40_ = NULL;
	gchar** _tmp41_ = NULL;
	gint _tmp41__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (req != NULL, NULL);
	node = NULL;
	_tmp0_ = req;
	_tmp1_ = qetesh_http_request_get_Path (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	path = _tmp3_;
	_tmp5_ = path;
	if (g_strcmp0 (_tmp5_, "/") == 0) {
		_tmp4_ = TRUE;
	} else {
		const gchar* _tmp6_ = NULL;
		_tmp6_ = path;
		_tmp4_ = g_strcmp0 (_tmp6_, "") == 0;
	}
	_tmp7_ = _tmp4_;
	if (_tmp7_) {
		QeteshQWebNode* _tmp8_ = NULL;
		QeteshQWebNode* _tmp9_ = NULL;
		_tmp8_ = self->RootNode;
		_tmp9_ = _g_object_ref0 (_tmp8_);
		result = _tmp9_;
		_g_free0 (path);
		_g_object_unref0 (node);
		return result;
	}
	_tmp10_ = path;
	_tmp11_ = string_strip (_tmp10_);
	_g_free0 (path);
	path = _tmp11_;
	_tmp12_ = path;
	_tmp13_ = g_str_has_prefix (_tmp12_, "/");
	if (_tmp13_) {
		const gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		_tmp14_ = path;
		_tmp15_ = string_substring (_tmp14_, (glong) 1, (glong) (-1));
		_g_free0 (path);
		path = _tmp15_;
	}
	_tmp16_ = path;
	_tmp17_ = g_str_has_suffix (_tmp16_, "/");
	if (_tmp17_) {
		const gchar* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		gchar* _tmp21_ = NULL;
		_tmp18_ = path;
		_tmp19_ = path;
		_tmp20_ = g_utf8_strlen (_tmp19_, (gssize) (-1));
		_tmp21_ = string_substring (_tmp18_, (glong) 0, (glong) _tmp20_);
		_g_free0 (path);
		path = _tmp21_;
	}
	_tmp22_ = self->appContext;
	_tmp23_ = qetesh_web_app_context_get_Server (_tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = _tmp24_->Err;
	_tmp26_ = path;
	_tmp27_ = g_strdup_printf ("Trying to find node for %s", _tmp26_);
	_tmp28_ = _tmp27_;
	qetesh_error_manager_WriteMessage (_tmp25_, _tmp28_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_g_free0 (_tmp28_);
	_tmp29_ = path;
	_tmp31_ = _tmp30_ = g_strsplit (_tmp29_, "/", 0);
	parts = _tmp31_;
	parts_length1 = _vala_array_length (_tmp30_);
	_parts_size_ = parts_length1;
	_tmp32_ = self->appContext;
	_tmp33_ = qetesh_web_app_context_get_Server (_tmp32_);
	_tmp34_ = _tmp33_;
	_tmp35_ = _tmp34_->Err;
	_tmp36_ = parts;
	_tmp36__length1 = parts_length1;
	_tmp37_ = g_strdup_printf ("Node should be %d deep", _tmp36__length1);
	_tmp38_ = _tmp37_;
	qetesh_error_manager_WriteMessage (_tmp35_, _tmp38_, QETESH_ERROR_MANAGER_QERROR_CLASS_QETESH_DEBUG, NULL);
	_g_free0 (_tmp38_);
	_tmp39_ = self->RootNode;
	_tmp40_ = _g_object_ref0 (_tmp39_);
	_g_object_unref0 (node);
	node = _tmp40_;
	_tmp41_ = parts;
	_tmp41__length1 = parts_length1;
	{
		gchar** sp_collection = NULL;
		gint sp_collection_length1 = 0;
		gint _sp_collection_size_ = 0;
		gint sp_it = 0;
		sp_collection = _tmp41_;
		sp_collection_length1 = _tmp41__length1;
		for (sp_it = 0; sp_it < _tmp41__length1; sp_it = sp_it + 1) {
			gchar* _tmp42_ = NULL;
			gchar* sp = NULL;
			_tmp42_ = g_strdup (sp_collection[sp_it]);
			sp = _tmp42_;
			{
				QeteshQWebNode* _tmp43_ = NULL;
				GeeMap* _tmp44_ = NULL;
				const gchar* _tmp45_ = NULL;
				gboolean _tmp46_ = FALSE;
				_tmp43_ = node;
				_tmp44_ = _tmp43_->Children;
				_tmp45_ = sp;
				_tmp46_ = gee_map_has_key (_tmp44_, _tmp45_);
				if (_tmp46_) {
					QeteshQWebNode* _tmp47_ = NULL;
					GeeMap* _tmp48_ = NULL;
					const gchar* _tmp49_ = NULL;
					gpointer _tmp50_ = NULL;
					_tmp47_ = node;
					_tmp48_ = _tmp47_->Children;
					_tmp49_ = sp;
					_tmp50_ = gee_map_get (_tmp48_, _tmp49_);
					_g_object_unref0 (node);
					node = (QeteshQWebNode*) _tmp50_;
				} else {
					result = NULL;
					_g_free0 (sp);
					parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (path);
					_g_object_unref0 (node);
					return result;
				}
				_g_free0 (sp);
			}
		}
	}
	result = node;
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (path);
	return result;
}


static void qetesh_qweb_app_class_init (QeteshQWebAppClass * klass) {
	qetesh_qweb_app_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = qetesh_qweb_app_finalize;
}


static void qetesh_qweb_app_instance_init (QeteshQWebApp * self) {
}


static void qetesh_qweb_app_finalize (GObject* obj) {
	QeteshQWebApp * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_QWEB_APP, QeteshQWebApp);
	_g_object_unref0 (self->RootNode);
	_g_object_unref0 (self->appContext);
	G_OBJECT_CLASS (qetesh_qweb_app_parent_class)->finalize (obj);
}


/**
 * Base class to be inherited by module entry classes
 * 
**/
GType qetesh_qweb_app_get_type (void) {
	static volatile gsize qetesh_qweb_app_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_qweb_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshQWebAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_qweb_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshQWebApp), 0, (GInstanceInitFunc) qetesh_qweb_app_instance_init, NULL };
		GType qetesh_qweb_app_type_id;
		qetesh_qweb_app_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshQWebApp", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_qweb_app_type_id__volatile, qetesh_qweb_app_type_id);
	}
	return qetesh_qweb_app_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



