/* WebAppContext.c generated by valac 0.22.1, the Vala compiler
 * generated from WebAppContext.vala, do not modify */

/*
 * AppContext.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define QETESH_TYPE_WEB_APP_CONTEXT (qetesh_web_app_context_get_type ())
#define QETESH_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext))
#define QETESH_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))
#define QETESH_IS_WEB_APP_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_IS_WEB_APP_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_APP_CONTEXT))
#define QETESH_WEB_APP_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextClass))

typedef struct _QeteshWebAppContext QeteshWebAppContext;
typedef struct _QeteshWebAppContextClass QeteshWebAppContextClass;
typedef struct _QeteshWebAppContextPrivate QeteshWebAppContextPrivate;

#define QETESH_TYPE_APP_MODULE (qetesh_app_module_get_type ())
#define QETESH_APP_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_APP_MODULE, QeteshAppModule))
#define QETESH_APP_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_APP_MODULE, QeteshAppModuleClass))
#define QETESH_IS_APP_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_APP_MODULE))
#define QETESH_IS_APP_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_APP_MODULE))
#define QETESH_APP_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_APP_MODULE, QeteshAppModuleClass))

typedef struct _QeteshAppModule QeteshAppModule;
typedef struct _QeteshAppModuleClass QeteshAppModuleClass;

#define QETESH_TYPE_EVENT_MANAGER (qetesh_event_manager_get_type ())
#define QETESH_EVENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_EVENT_MANAGER, QeteshEventManager))
#define QETESH_EVENT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_EVENT_MANAGER, QeteshEventManagerClass))
#define QETESH_IS_EVENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_EVENT_MANAGER))
#define QETESH_IS_EVENT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_EVENT_MANAGER))
#define QETESH_EVENT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_EVENT_MANAGER, QeteshEventManagerClass))

typedef struct _QeteshEventManager QeteshEventManager;
typedef struct _QeteshEventManagerClass QeteshEventManagerClass;

#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _QeteshWebAppContext {
	GObject parent_instance;
	QeteshWebAppContextPrivate * priv;
};

struct _QeteshWebAppContextClass {
	GObjectClass parent_class;
};

struct _QeteshWebAppContextPrivate {
	QeteshAppModule* _Mod;
	QeteshEventManager* _Events;
	QeteshWebServerContext* _Server;
};


static gpointer qetesh_web_app_context_parent_class = NULL;

GType qetesh_web_app_context_get_type (void) G_GNUC_CONST;
GType qetesh_app_module_get_type (void) G_GNUC_CONST;
GType qetesh_event_manager_get_type (void) G_GNUC_CONST;
GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
#define QETESH_WEB_APP_CONTEXT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContextPrivate))
enum  {
	QETESH_WEB_APP_CONTEXT_DUMMY_PROPERTY,
	QETESH_WEB_APP_CONTEXT_MOD,
	QETESH_WEB_APP_CONTEXT_EVENTS,
	QETESH_WEB_APP_CONTEXT_SERVER
};
QeteshWebAppContext* qetesh_web_app_context_new (void);
QeteshWebAppContext* qetesh_web_app_context_construct (GType object_type);
QeteshAppModule* qetesh_web_app_context_get_Mod (QeteshWebAppContext* self);
void qetesh_web_app_context_set_Mod (QeteshWebAppContext* self, QeteshAppModule* value);
QeteshEventManager* qetesh_web_app_context_get_Events (QeteshWebAppContext* self);
void qetesh_web_app_context_set_Events (QeteshWebAppContext* self, QeteshEventManager* value);
QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self);
void qetesh_web_app_context_set_Server (QeteshWebAppContext* self, QeteshWebServerContext* value);
static void qetesh_web_app_context_finalize (GObject* obj);
static void _vala_qetesh_web_app_context_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_qetesh_web_app_context_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


QeteshWebAppContext* qetesh_web_app_context_construct (GType object_type) {
	QeteshWebAppContext * self = NULL;
	self = (QeteshWebAppContext*) g_object_new (object_type, NULL);
	return self;
}


QeteshWebAppContext* qetesh_web_app_context_new (void) {
	return qetesh_web_app_context_construct (QETESH_TYPE_WEB_APP_CONTEXT);
}


QeteshAppModule* qetesh_web_app_context_get_Mod (QeteshWebAppContext* self) {
	QeteshAppModule* result;
	QeteshAppModule* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Mod;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void qetesh_web_app_context_set_Mod (QeteshWebAppContext* self, QeteshAppModule* value) {
	QeteshAppModule* _tmp0_ = NULL;
	QeteshAppModule* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Mod);
	self->priv->_Mod = _tmp1_;
	g_object_notify ((GObject *) self, "Mod");
}


QeteshEventManager* qetesh_web_app_context_get_Events (QeteshWebAppContext* self) {
	QeteshEventManager* result;
	QeteshEventManager* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Events;
	result = _tmp0_;
	return result;
}


void qetesh_web_app_context_set_Events (QeteshWebAppContext* self, QeteshEventManager* value) {
	QeteshEventManager* _tmp0_ = NULL;
	QeteshEventManager* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Events);
	self->priv->_Events = _tmp1_;
	g_object_notify ((GObject *) self, "Events");
}


QeteshWebServerContext* qetesh_web_app_context_get_Server (QeteshWebAppContext* self) {
	QeteshWebServerContext* result;
	QeteshWebServerContext* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_Server;
	result = _tmp0_;
	return result;
}


void qetesh_web_app_context_set_Server (QeteshWebAppContext* self, QeteshWebServerContext* value) {
	QeteshWebServerContext* _tmp0_ = NULL;
	QeteshWebServerContext* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_Server);
	self->priv->_Server = _tmp1_;
	g_object_notify ((GObject *) self, "Server");
}


static void qetesh_web_app_context_class_init (QeteshWebAppContextClass * klass) {
	qetesh_web_app_context_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (QeteshWebAppContextPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_qetesh_web_app_context_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_qetesh_web_app_context_set_property;
	G_OBJECT_CLASS (klass)->finalize = qetesh_web_app_context_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_WEB_APP_CONTEXT_MOD, g_param_spec_object ("Mod", "Mod", "Mod", QETESH_TYPE_APP_MODULE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_WEB_APP_CONTEXT_EVENTS, g_param_spec_object ("Events", "Events", "Events", QETESH_TYPE_EVENT_MANAGER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), QETESH_WEB_APP_CONTEXT_SERVER, g_param_spec_object ("Server", "Server", "Server", QETESH_TYPE_WEB_SERVER_CONTEXT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void qetesh_web_app_context_instance_init (QeteshWebAppContext * self) {
	self->priv = QETESH_WEB_APP_CONTEXT_GET_PRIVATE (self);
}


static void qetesh_web_app_context_finalize (GObject* obj) {
	QeteshWebAppContext * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext);
	_g_object_unref0 (self->priv->_Mod);
	_g_object_unref0 (self->priv->_Events);
	_g_object_unref0 (self->priv->_Server);
	G_OBJECT_CLASS (qetesh_web_app_context_parent_class)->finalize (obj);
}


/**
 * Context data for a single web application
 * 
**/
GType qetesh_web_app_context_get_type (void) {
	static volatile gsize qetesh_web_app_context_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_web_app_context_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshWebAppContextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_web_app_context_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshWebAppContext), 0, (GInstanceInitFunc) qetesh_web_app_context_instance_init, NULL };
		GType qetesh_web_app_context_type_id;
		qetesh_web_app_context_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshWebAppContext", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_web_app_context_type_id__volatile, qetesh_web_app_context_type_id);
	}
	return qetesh_web_app_context_type_id__volatile;
}


static void _vala_qetesh_web_app_context_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	QeteshWebAppContext * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext);
	switch (property_id) {
		case QETESH_WEB_APP_CONTEXT_MOD:
		g_value_set_object (value, qetesh_web_app_context_get_Mod (self));
		break;
		case QETESH_WEB_APP_CONTEXT_EVENTS:
		g_value_set_object (value, qetesh_web_app_context_get_Events (self));
		break;
		case QETESH_WEB_APP_CONTEXT_SERVER:
		g_value_set_object (value, qetesh_web_app_context_get_Server (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_qetesh_web_app_context_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	QeteshWebAppContext * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, QETESH_TYPE_WEB_APP_CONTEXT, QeteshWebAppContext);
	switch (property_id) {
		case QETESH_WEB_APP_CONTEXT_MOD:
		qetesh_web_app_context_set_Mod (self, g_value_get_object (value));
		break;
		case QETESH_WEB_APP_CONTEXT_EVENTS:
		qetesh_web_app_context_set_Events (self, g_value_get_object (value));
		break;
		case QETESH_WEB_APP_CONTEXT_SERVER:
		qetesh_web_app_context_set_Server (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



