/* WebServerContext.c generated by valac 0.22.1, the Vala compiler
 * generated from WebServerContext.vala, do not modify */

/*
 * ServerContext.vala
 * 
 * Copyright 2014 Dan Ladds <Dan@el-topo.co.uk>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */

#include <glib.h>
#include <glib-object.h>


#define QETESH_TYPE_WEB_SERVER_CONTEXT (qetesh_web_server_context_get_type ())
#define QETESH_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext))
#define QETESH_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))
#define QETESH_IS_WEB_SERVER_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_IS_WEB_SERVER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_WEB_SERVER_CONTEXT))
#define QETESH_WEB_SERVER_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContextClass))

typedef struct _QeteshWebServerContext QeteshWebServerContext;
typedef struct _QeteshWebServerContextClass QeteshWebServerContextClass;
typedef struct _QeteshWebServerContextPrivate QeteshWebServerContextPrivate;

#define QETESH_TYPE_ERROR_MANAGER (qetesh_error_manager_get_type ())
#define QETESH_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManager))
#define QETESH_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))
#define QETESH_IS_ERROR_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_IS_ERROR_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_ERROR_MANAGER))
#define QETESH_ERROR_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_ERROR_MANAGER, QeteshErrorManagerClass))

typedef struct _QeteshErrorManager QeteshErrorManager;
typedef struct _QeteshErrorManagerClass QeteshErrorManagerClass;

#define QETESH_DATA_TYPE_DB_MANAGER (qetesh_data_db_manager_get_type ())
#define QETESH_DATA_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManager))
#define QETESH_DATA_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))
#define QETESH_DATA_IS_DB_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_IS_DB_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_DATA_TYPE_DB_MANAGER))
#define QETESH_DATA_DB_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_DATA_TYPE_DB_MANAGER, QeteshDataDBManagerClass))

typedef struct _QeteshDataDBManager QeteshDataDBManager;
typedef struct _QeteshDataDBManagerClass QeteshDataDBManagerClass;

#define QETESH_TYPE_MODULE_MANAGER (qetesh_module_manager_get_type ())
#define QETESH_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManager))
#define QETESH_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))
#define QETESH_IS_MODULE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_IS_MODULE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_MODULE_MANAGER))
#define QETESH_MODULE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_MODULE_MANAGER, QeteshModuleManagerClass))

typedef struct _QeteshModuleManager QeteshModuleManager;
typedef struct _QeteshModuleManagerClass QeteshModuleManagerClass;

#define QETESH_TYPE_CONFIG_FILE (qetesh_config_file_get_type ())
#define QETESH_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFile))
#define QETESH_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))
#define QETESH_IS_CONFIG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), QETESH_TYPE_CONFIG_FILE))
#define QETESH_IS_CONFIG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), QETESH_TYPE_CONFIG_FILE))
#define QETESH_CONFIG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), QETESH_TYPE_CONFIG_FILE, QeteshConfigFileClass))

typedef struct _QeteshConfigFile QeteshConfigFile;
typedef struct _QeteshConfigFileClass QeteshConfigFileClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _QeteshWebServerContext {
	GObject parent_instance;
	QeteshWebServerContextPrivate * priv;
	QeteshErrorManager* Err;
	QeteshDataDBManager* Databases;
	QeteshModuleManager* Modules;
	QeteshConfigFile* Configuration;
};

struct _QeteshWebServerContextClass {
	GObjectClass parent_class;
};


static gpointer qetesh_web_server_context_parent_class = NULL;

GType qetesh_web_server_context_get_type (void) G_GNUC_CONST;
GType qetesh_error_manager_get_type (void) G_GNUC_CONST;
GType qetesh_data_db_manager_get_type (void) G_GNUC_CONST;
GType qetesh_module_manager_get_type (void) G_GNUC_CONST;
GType qetesh_config_file_get_type (void) G_GNUC_CONST;
enum  {
	QETESH_WEB_SERVER_CONTEXT_DUMMY_PROPERTY
};
QeteshWebServerContext* qetesh_web_server_context_new (void);
QeteshWebServerContext* qetesh_web_server_context_construct (GType object_type);
static void qetesh_web_server_context_finalize (GObject* obj);


QeteshWebServerContext* qetesh_web_server_context_construct (GType object_type) {
	QeteshWebServerContext * self = NULL;
	self = (QeteshWebServerContext*) g_object_new (object_type, NULL);
	return self;
}


QeteshWebServerContext* qetesh_web_server_context_new (void) {
	return qetesh_web_server_context_construct (QETESH_TYPE_WEB_SERVER_CONTEXT);
}


static void qetesh_web_server_context_class_init (QeteshWebServerContextClass * klass) {
	qetesh_web_server_context_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = qetesh_web_server_context_finalize;
}


static void qetesh_web_server_context_instance_init (QeteshWebServerContext * self) {
}


static void qetesh_web_server_context_finalize (GObject* obj) {
	QeteshWebServerContext * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, QETESH_TYPE_WEB_SERVER_CONTEXT, QeteshWebServerContext);
	_g_object_unref0 (self->Err);
	_g_object_unref0 (self->Databases);
	_g_object_unref0 (self->Modules);
	_g_object_unref0 (self->Configuration);
	G_OBJECT_CLASS (qetesh_web_server_context_parent_class)->finalize (obj);
}


/**
 * Context data for a single Qetesh server instance
 * 
**/
GType qetesh_web_server_context_get_type (void) {
	static volatile gsize qetesh_web_server_context_type_id__volatile = 0;
	if (g_once_init_enter (&qetesh_web_server_context_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (QeteshWebServerContextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) qetesh_web_server_context_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (QeteshWebServerContext), 0, (GInstanceInitFunc) qetesh_web_server_context_instance_init, NULL };
		GType qetesh_web_server_context_type_id;
		qetesh_web_server_context_type_id = g_type_register_static (G_TYPE_OBJECT, "QeteshWebServerContext", &g_define_type_info, 0);
		g_once_init_leave (&qetesh_web_server_context_type_id__volatile, qetesh_web_server_context_type_id);
	}
	return qetesh_web_server_context_type_id__volatile;
}



